<?php

namespace BNETDocs\Libraries;

use \SplEnum;

class EventTypes {

  const LOG_NOTE = 0;
  const SITE_DEPLOY = 1;
  const BLIZZARD_VISIT = 2;
  const EMAIL_SENT = 3;
  const USER_CREATED = 4;
  const USER_EDITED = 5;
  const USER_DELETED = 6;
  const USER_LOGIN = 7;
  const USER_LOGOUT = 8;
  const USER_PASSWORD_CHANGE = 9;
  const USER_PASSWORD_RESET = 10;
  const USER_EMAIL_CHANGE = 11;
  const USER_VERIFIED = 12;
  const NEWS_CREATED = 13;
  const NEWS_EDITED = 14;
  const NEWS_DELETED = 15;
  const PACKET_CREATED = 16;
  const PACKET_EDITED = 17;
  const PACKET_DELETED = 18;
  const DOCUMENT_CREATED = 19;
  const DOCUMENT_EDITED = 20;
  const DOCUMENT_DELETED = 21;
  const COMMENT_CREATED_NEWS = 22;
  const COMMENT_CREATED_PACKET = 23;
  const COMMENT_CREATED_DOCUMENT = 24;
  const COMMENT_CREATED_USER = 25;
  const COMMENT_EDITED_NEWS = 26;
  const COMMENT_EDITED_PACKET = 27;
  const COMMENT_EDITED_DOCUMENT = 28;
  const COMMENT_EDITED_USER = 29;
  const COMMENT_DELETED_NEWS = 30;
  const COMMENT_DELETED_PACKET = 31;
  const COMMENT_DELETED_DOCUMENT = 32;
  const COMMENT_DELETED_USER = 33;
  const COMMENT_CREATED_SERVER = 34;
  const COMMENT_CREATED_COMMENT = 35;
  const COMMENT_EDITED_SERVER = 36;
  const COMMENT_EDITED_COMMENT = 37;
  const COMMENT_DELETED_SERVER = 38;
  const COMMENT_DELETED_COMMENT = 39;
  const SERVER_CREATED = 40;
  const SERVER_EDITED = 41;
  const SERVER_DELETED = 42;

}
