<?php require("./email/header.plain.inc.phtml"); ?>
Welcome to BNETDocs!

Your account requires activation before being able to use this service. Click
or copy and paste the link below into your browser to activate your account.

https://dev.bnetdocs.org/user/activate?t=<?php echo rawurlencode($this->getContext()->token); ?>

Note: This link will only be available for 24 hours after registering. If you
wait until it expires, you will need to complete a password reset.
<?php require("./email/footer.plain.inc.phtml"); ?>
