<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\News;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Create News Post';
$description = 'This page enables a user to create news posts on the site.';
$this->opengraph->attach(new Pair('url', '/news/create'));
$this->opengraph->attach(new Pair('type', 'article'));
$error = $this->getContext()->error;
switch ($error)
{
  case 'ACL_NOT_SET': $message = 'You do not have the privilege to create news posts.'; break;
  case 'EMPTY_TITLE': $message = 'The title of the news post is required.'; break;
  case 'EMPTY_CONTENT': $message = 'The content of the news post is required.'; break;
  case 'INTERNAL_ERROR': $message = 'An internal error occurred while processing your request. Our staff have been notified of the issue. Try again later.'; break;
  default: $message = $error;
}
$form_content = filter_var($this->getContext()->content, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$form_markdown = $this->getContext()->markdown;
$form_rss_exempt = $this->getContext()->rss_exempt;
$form_title = filter_var($this->getContext()->title, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$news_post_id = null;
$news_post_url = null;
require('./header.inc.phtml');
if (!$this->getContext()->acl_allowed) {
  echo '<div class="container">';
  require('./LoginRequired.inc.phtml');
  echo '</div>';
  require('./footer.inc.phtml');
  return;
} ?>
<div class="container">
  <h1><?=$title?></h1>
  <p><?=$description?></p>
<?  if ($error !== false) {
     if (!empty($message)) { ?>
  <div class="alert alert-danger">
    <p class="mb-0"><?=$message?></p>
  </div>
<?    }
      require('./News/Form.inc.phtml');
    } else { ?>
  <div class="alert alert-success">
    <p class="mb-0">Your news post has been created.</p>
  </div>
<?  } ?>
</div>
<? require('./footer.inc.phtml'); ?>
