<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Common;
use \BNETDocs\Libraries\Gravatar;
use \BNETDocs\Libraries\NewsPost;
use \BNETDocs\Libraries\Pair;
use \BNETDocs\Libraries\User;

$comments     = $this->getContext()->comments;
$object       = $this->getContext()->news_post;
$object_id    = $this->getContext()->news_post_id;
$user_session = $this->getContext()->user_session;
$logged_in    = ($user_session ? new User($user_session->user_id) : null);

$title       = ($object ? $object->getTitle() : "News Post Not Found");
$description = Common::stripUpTo(trim(filter_var(
  ($object ? $object->getContent(true) : "The requested news post does not exist or could not be found."),
  FILTER_SANITIZE_STRING
)), "\n", 300);

$this->opengraph->attach(new Pair("type", "article"));

$url = Common::relativeUrlToAbsolute("/news/" . urlencode($object_id));

if ($object) {

  $url = $object->getURI();

  $this->opengraph->attach(new Pair("image", "/a/news_categories/" . $object->getCategory()->getFilename()));
  $this->opengraph->attach(new Pair("article:published_time", $object->getCreatedDateTime()->format("c")));
  if (!is_null($object->getEditedDateTime())) {
    $this->opengraph->attach(new Pair("article:modified_time", $object->getEditedDateTime()->format("c")));
  }
  $this->opengraph->attach(new Pair("article:author:username", $object->getUser()->getName()));
  $this->opengraph->attach(new Pair("article:section", $object->getCategory()->getLabel()));

}

$this->opengraph->attach(new Pair("url", $url));

$edit_url       = Common::relativeUrlToAbsolute("/news/edit?id=" . urlencode($object_id));
$delete_url     = Common::relativeUrlToAbsolute("/news/delete?id=" . urlencode($object_id));
$edit_visible   = ($logged_in && ($logged_in->getOptionsBitmask()
                & User::OPTION_ACL_NEWS_MODIFY));
$delete_visible = ($logged_in && ($logged_in->getOptionsBitmask()
                & User::OPTION_ACL_NEWS_DELETE));

if ($object) {
  $user_name   = $object->getUser()->getName();
  $user_id     = $object->getUserId();
  $user_url    = $object->getUser()->getURI();
  $user_avatar = "https:" . (new Gravatar($object->getUser()->getEmail()))->getUrl(22, "identicon");
}

$this->additional_css[] = "/a/news.css";
$this->additional_css[] = "/a/comments.css";
if ($logged_in) $this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
<?php if ($object) { ?>
        <a href="https://plus.google.com/share?url=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-gplus-24px.png"); ?>"/></a>
        <a href="https://twitter.com/share?text=<?php echo urlencode($object->getTitle()); ?>&amp;url=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-twitter-24px.png"); ?>"/></a>
        <a href="https://facebook.com/sharer/sharer.php?u=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-facebook-24px.png"); ?>"/></a>
<?php if ($edit_visible) { ?>
        <a href="<?php echo $edit_url; ?>" class="header-button float-right">Edit</a>
<?php } ?>
<?php if ($delete_visible) { ?>
        <a href="<?php echo $delete_url; ?>" class="header-button float-right">Delete</a>
<?php } ?>
        <header><a href="<?php echo $url; ?>"><?php echo $object->getTitle(); ?></a></header>
<?php if (!($object->getOptionsBitmask() & NewsPost::OPTION_PUBLISHED)) { ?>
        <section class="red"><p><strong>Warning:</strong> This news post is not yet published. You can view this because you are allowed to create, modify, or delete news posts.</p></section>
<?php } ?>
        <section class="news"><img class="category" alt="<?php echo $object->getCategory()->getLabel(); ?>" title="<?php echo $object->getCategory()->getLabel(); ?>" src="<?php echo Common::relativeUrlToAbsolute("/a/news_categories/" . $object->getCategory()->getFilename()); ?>"/><?php echo $object->getContent(true); ?></section>
        <footer>
          <span class="float-left"><a href="<?php echo $user_url; ?>"><img class="avatar" src="<?php echo $user_avatar; ?>"/> <?php echo htmlspecialchars($user_name, ENT_HTML5, "UTF-8"); ?></a></span>
          <span class="float-right"><?php echo $object->getPublishedDateTime()->format("l, F j, Y"); ?></span>
        </footer>
      </article>
      <article>
        <header>Comments</header>
        <section>
<?php if (!$comments) { ?>
          <p class="center"><em>no one has commented yet.</em></p>
<?php } else { ?>
          <table class="comments"><tbody>
<?php foreach ($comments as $c) {
        $c_user        = $c->getUser();
        $c_user_name   = $c_user->getName();
        $c_user_id     = $c->getUserId();
        $c_user_url    = $c_user->getURI();
        $c_user_avatar = "https:" . (new Gravatar($c_user->getEmail()))->getUrl(22, "identicon");
?>
            <tr><td><a href="<?php echo $c_user_url; ?>"><img class="avatar" src="<?php echo $c_user_avatar; ?>"/> <?php echo htmlspecialchars($c_user_name, ENT_HTML5, "UTF-8"); ?></a><br/><time class="comment_timestamp" datetime="<?php echo $c->getCreatedDateTime()->format("c"); ?>"><?php echo $c->getCreatedDateTime()->format("D M j, Y g:ia T"); ?></time></td><td><?php echo $c->getContent(true); ?></td></tr>
<?php } ?>
          </tbody></table>
<?php } ?>
        </section>
<?php if ($logged_in) { ?>
        <section>
          <form method="POST" action="?">
            <p class="center"><label for="comment-content">Comment on this post:</label></p>
            <p class="center"><textarea id="comment-content" name="comment-content" cols="80" rows="5"></textarea></p>
            <p class="center"><input type="submit" value="Comment"/></p>
          </form>
        </section>
<?php } ?>
<?php } else { ?>
        <header class="red"><?php echo htmlspecialchars($title, ENT_HTML5, "UTF-8"); ?></header>
        <section class="red"><?php echo htmlspecialchars($description, ENT_HTML5, "UTF-8"); ?></section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
