---
version: "3.3"
services:

  nginx:
    image: nginx:stable-alpine
    container_name: bnetdocs-nginx
    restart: always
    depends_on:
      - mariadb
      - php
    volumes:
      - ./etc/nginx/conf.d/nginx-vhost-docker.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8080:80"

  php:
    build: './etc/docker/php'
    container_name: bnetdocs-php
    restart: always
    volumes:
      - mariadb-vol-1:/var/lib/mysql/:Z
      - .:/var/www/html
    expose:
      - "9000"

  mariadb:
    image: mariadb:10.7
    container_name: bnetdocs-mariadb
    restart: always
    volumes:
      - mariadb-vol-1:/var/lib/mysql/:Z
    expose:
      - "3306"
    environment:
      - MARIADB_DATABASE=bnetdocs_docker
      - MARIADB_ROOT_PASSWORD=bnetdocs_docker_rootpw420
      - MARIADB_USER=bnetdocs_docker
      - MARIADB_PASSWORD=bnetdocs_docker
      - MARIADB_AUTO_UPGRADE=yes
      - MARIADB_DISABLE_UPGRADE_BACKUP=yes

volumes:
  mariadb-vol-1:
