<? global $language, $groupname, $commentizer; ?>
<?=$commentizer;?> PacketID Constants for <?=$language;?> 
<?=$commentizer;?> Generated by BNETDocs: Redux on <? echo date('F j, Y');?> 
<?=$commentizer;?> BNETDocs: Redux software written by Don Cullen AKA Kyro
<?=$commentizer;?> Original BNETDocs content compiled by Arta & Skywing

