<?php

namespace BNETDocs\Templates\User;

use \CarlBennett\MVC\Libraries\Pair;

$title       = "Change Password";
$description = "This form allows an individual to change the password to their account.";
$this->opengraph->attach(new Pair("url", "/user/changepassword"));

switch ($this->getContext()->error) {
  case "NOT_LOGGED_IN":
    $message = "You were not logged in to begin with.";
    break;
  case "NONMATCHING_PASSWORD":
    $message = "The new password does not match its confirmation.";
    break;
  case "PASSWORD_CONTAINS_EMAIL":
    $message = "The password contains the email address, "
      . "use a better password.";
    break;
  case "PASSWORD_CONTAINS_USERNAME":
    $message = "The password contains the username, use a better password.";
    break;
  case "PASSWORD_INCORRECT":
    $message = "You did not enter your correct current password.";
    break;
  case "PASSWORD_TOO_LONG":
    $message = "The password is too long, shorten it.";
    break;
  case "PASSWORD_TOO_SHORT":
    $message = "The password is too short, use a better password.";
    break;
  case "PASSWORD_BLACKLIST":
    $message = $this->getContext()->error_extra;
    if (empty($message)) $message = "The new password is blacklisted.";
    break;
  case "INTERNAL_ERROR":
    $message = "An internal error occurred while processing your request. "
      . "Our staff have been notified of the issue. Try again later.";
    break;
  default:
    $message = $this->getContext()->error;
}

$this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
<?php if ($this->getContext()->error !== false) { ?>
        <header>Change Password</header>
<?php if (!empty($message)) { ?>
        <section class="red">
          <p><?php echo $message; ?></p>
        </section>
<?php } ?>
        <form method="POST" action="?">
          <section>
            <table><tbody><tr>
              <td colspan="2">
                <label for="pw1">Current password:</label><br/>
                <input type="password" name="pw1" id="pw1" tabindex="1"
                  value="" required autofocus="autofocus"/>
              </td></tr><tr><td>
                <label for="pw2">New password:</label><br/>
                <input type="password" name="pw2" id="pw2" tabindex="2"
                  value="" required/>
              </td><td>
                <label for="pw3">Confirm password:</label><br/>
                <input type="password" name="pw3" id="pw3" tabindex="3"
                  value="" required/>
              </td></tr><tr><td colspan="2" style="padding-top:16px;">
                <input type="submit" value="Submit" tabindex="4"/>
              </td>
            </tr></tbody></table>
          </section>
        </form>
<?php } else { ?>
        <header class="green">Password Changed</header>
        <section class="green">
          <p>You have successfully changed your password!</p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
