<?php

namespace BNETDocs\Templates\User;

use \CarlBennett\MVC\Libraries\Pair;

$title       = "Create Password";
$description = "This form allows an individual to create a password hash and salt for their account. DEVELOPMENT PURPOSES ONLY";
$this->opengraph->attach(new Pair("url", "/user/createpassword"));

require("./header.inc.phtml");
?>
      <article>
        <header>Create Password</header>
        <form method="POST" action="?">
          <section>
            <p>This form is for creating a password to your user account. It generates values that need to be given to the BNETDocs Staff for facilitating your account's creation or password reset.</p>
          </section>
          <section>
            <label for="input">Password:</label><br/>
            <input
              type="password"
              name="input"
              id="input"
              value="<?php echo filter_var($this->getContext()->input, FILTER_SANITIZE_FULL_SPECIAL_CHARS); ?>"
              tabindex="1"
              required
              autofocus="autofocus"
            />
          </section>
          <section>
            <input
              type="submit"
              value="Get Hash &amp; Salt"
              tabindex="2"
            />
          </section>
        </form>
<?php if (!empty($this->getContext()->output)) { ?>
      </article>
      <article>
        <header class="green">Secret Data</header>
        <section class="green">
          <p>These values with your email address or username must be given to BNETDocs Staff, message them now.</p>
          <table>
            <thead></thead>
            <tbody>
              <tr><th>Hash:</th><td><code><?php echo filter_var($this->getContext()->output[0], FILTER_SANITIZE_FULL_SPECIAL_CHARS); ?></code></td></tr>
              <tr><th>Salt:</th><td><code><?php echo filter_var($this->getContext()->output[1], FILTER_SANITIZE_FULL_SPECIAL_CHARS); ?></code></td></tr>
            </tbody>
          </table>
          <p>Please allow BNETDocs Staff a few moments to put these values into your account.</p>
        </section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
