<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Create Password';
$description = 'This page creates a password suitable for a user account.';
$this->opengraph->attach(new Pair('url', '/user/createpassword'));
$output = $this->getContext()->output;
require('./header.inc.phtml'); ?>
<div class="container">
  <h1><?=$title?></h1>
  <p><?=$description?></p>
  <div class="alert alert-info"><p class="mb-0">Our <a href="<?=Common::relativeUrlToAbsolute('/privacy')?>">privacy policy</a> page clarifies your data rights. You agree to giving (or not giving) the info contained herein on this page.</p></div>
  <div class="alert alert-warning"><p class="mb-0"><strong>Warning:</strong> This page is to be used with permission by site staff only. Use without permission is <strong>prohibited</strong> and may result in this page being shutdown in the future.</p></div>
  <form method="POST" action="?">
    <div class="form-group">
      <label class="font-weight-bold" for="input">Password:</label><br/>
      <input class="bg-dark border border-primary form-control text-light" type="password" name="input" id="input" placeholder="Enter the password here" value="<?=filter_var($this->getContext()->input, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>" tabindex="1" required autocomplete="new-password" autofocus="autofocus"/>
    </div>
    <div class="form-group">
      <input class="btn btn-success" type="submit" value="Submit" tabindex="2"/>
    </div>
  </form>
<? if (!empty($output)) { ?>
  <div class="container border border-success p-2 rounded">
    <h3 class="text-success">Output</h3>
<? if (is_string($output)) { ?>
    <pre><code class="language-plaintext"><?=filter_var($output, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></code></pre>
<? } else { ?>
    <ul>
      <li><strong>Hash:</strong> <code><?=filter_var($output[0], FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></code></li>
      <li><strong>Salt:</strong> <code><?=filter_var($output[1], FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></code></li>
    </ul>
<? } ?>
    <p class="mb-0">Please copy the output above and send it to the staff member for integration into your user account.</p>
  </div>
<? } ?>
</div>
<? require('./footer.inc.phtml'); ?>
