<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\User;
use \BNETDocs\Libraries\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
use \DateTime;
$title = 'All Users';
$description = 'All users currently registered on BNETDocs';
$this->opengraph->attach(new Pair('url', '/user/index'));
$active_user = $this->getContext()->active_user;
$acl_user_delete = ($active_user && $active_user->getOption(User::OPTION_ACL_USER_DELETE));
$acl_user_modify = ($active_user && $active_user->getOption(User::OPTION_ACL_USER_MODIFY));
$page = $this->getContext()->page;
$pages = $this->getContext()->pages;
$limit = $this->getContext()->limit;
$order = $this->getContext()->order;
$no_prev = ($page <= 1);
$no_next = ($page >= $pages);
$form_order_by = [
  'id-asc' => 'User Id (Ascending)',
  'id-desc' => 'User Id (Descending)',
  'username-asc' => 'Username (Ascending)',
  'username-desc' => 'Username (Descending)',
  'registered-asc' => 'Registered (Ascending)',
  'registered-desc' => 'Registered (Descending)',
];
$now = new DateTime('now');
require('./header.inc.phtml'); ?>
<div class="container">
  <h1><?=$title?></h1>
  <p><?=$description?></p>
  <form method="GET" id="order_by_form">
    <input type="hidden" name="page" value="<?=$page?>"/>
    <input type="hidden" name="limit" value="<?=$limit?>"/>
    <label for="order" class="font-weight-bold m-1">Order by:</label>
    <select class="form-control form-control-sm" name="order" id="order" onchange="form.submit();" style="display:inline-block;width:200px;">
<?  foreach ($form_order_by as $item_value => $item_label) {
      $item_selected = ($order === $item_value ? ' selected="selected"' : '');
      printf('<option value="%s"%s>%s</option>%s', $item_value, $item_selected, $item_label, PHP_EOL);
    } ?>
    </select>
    <input class="btn btn-sm btn-secondary" type="submit" value="Reorder"/>
  </form>
  <table class="table table-hover table-sm table-striped" id="users_tbl">
    <thead><tr><th>Account</th><th>Member for</th><?=($acl_user_modify || $acl_user_delete ? '<th>Action</th>' : '')?></tr></thead><tbody>
<?  foreach ($this->getContext()->users as $user)
    {
      printf(
        '<tr><td><a href="%s"><img class="mr-2" src="%s"/>%s</a></td><td>%s</td>%s</tr>%s',
        $user->getURI(),
        $user->getAvatarURI(22),
        filter_var($user->getName(), FILTER_SANITIZE_FULL_SPECIAL_CHARS),
        ($user->getCreatedEstimate() ?? '<em>(null)</em>'),
        ($acl_user_modify || $acl_user_delete ? (
          sprintf('<td>%s%s</td>', (
            $acl_user_modify ? sprintf('<a class="mr-1 btn btn-sm btn-secondary" href="%s" title="Modify">📝</a>', Common::relativeUrlToAbsolute('/user/update?id=' . rawurlencode($user->getId()))) : ''
          ), (
            $acl_user_delete ? sprintf('<a class="ml-1 btn btn-sm btn-danger" href="%s" title="Delete">❌</a>', Common::relativeUrlToAbsolute('/user/delete?id=' . rawurlencode($user->getId()))) : ''
          ))
        ) : ''),
        PHP_EOL
      );
    } ?>
  </tbody></table>
  <nav aria-label="User list navigation" class="d-flex justify-content-center">
    <ul class="pagination">
  <?  if (!$no_prev) { ?>
      <li class="page-item"><a class="page-link" href="<?=Common::relativeUrlToAbsolute('/user/index?page=' . ($page - 1) . '&limit=' . $limit . '&order=' . $order)?>">Previous</a></li>
  <?  } else { ?>
      <li class="page-item disabled"><span class="page-link">Previous</span></li>
  <?  } ?>
      <li class="page-item disabled"><span class="page-link"><?=number_format($page)?> of <?=number_format($pages)?></span></li>
  <?  if (!$no_next) { ?>
      <li class="page-item"><a class="page-link" href="<?=Common::relativeUrlToAbsolute('/user/index?page=' . ($page + 1) . '&limit=' . $limit . '&order=' . $order)?>">Next</a></li>
  <?  } else { ?>
      <li class="page-item disabled"><span class="page-link">Next</span></li>
  <?  } ?>
    </ul>
  </nav>
</div>
<? require("./footer.inc.phtml"); ?>
