<?php

namespace BNETDocs\Templates\User;

use \BNETDocs\Libraries\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;

$title       = 'User Index';
$description = 'The index for users on BNETDocs';
$this->opengraph->attach(new Pair('url', '/user/index'));

$page = $this->getContext()->page;
$pages = $this->getContext()->pages;
$limit = $this->getContext()->limit;
$order = $this->getContext()->order;

$no_prev = ($page <= 1);
$no_next = ($page >= $pages);

$this->additional_css[] = '/a/forms.css';
require('./header.inc.phtml');
?>
      <article>
        <header>User Index</header>
        <section>
          <form method="GET">
            <input type="hidden" name="page" value="<?php echo $page; ?>"/>
            <input type="hidden" name="limit" value="<?php echo $limit; ?>"/>
            <label for="order">Order by:</label>
            <select name="order" id="order" onchange="form.submit();"
              style="display:inline-block;width:200px;">
              <option value="id-asc"<?php
                if ($order === 'id-asc') { echo ' selected="selected"';
                } ?>>User Id (Ascending)</option>
              <option value="id-desc"<?php
                if ($order === 'id-desc') { echo ' selected="selected"';
                } ?>>User Id (Descending)</option>
              <option value="username-asc"<?php
                if ($order === 'username-asc') { echo ' selected="selected"';
                } ?>>Username (Ascending)</option>
              <option value="username-desc"<?php
                if ($order === 'username-desc') { echo ' selected="selected"';
                } ?>>Username (Descending)</option>
              <option value="registered-asc"<?php
                if ($order === 'registered-asc') { echo ' selected="selected"';
                } ?>>Registered (Ascending)</option>
              <option value="registered-desc"<?php
                if ($order === 'registered-desc') { echo ' selected="selected"';
                } ?>>Registered (Descending)</option>
            </select>
            <input type="submit" value="Reorder"/>
          </form>
          <table>
            <thead>
              <tr>
                <th class="left">Account</th>
                <th class="left">Registered</th>
              </tr>
            </thead><tbody>
<?php foreach ($this->getContext()->users as $user) {
        $user_url   = $user->getURI();
        $avatar_url = $user->getAvatarURI(22);
?>
              <tr>
                <td><a href="<?php echo $user_url; ?>"><img class="avatar" src="<?php echo $avatar_url; ?>"/>&nbsp;<?php echo filter_var($user->getName(), FILTER_SANITIZE_FULL_SPECIAL_CHARS); ?></a></td>
                <td><time datetime="<?php echo $user->getCreatedDateTime()->format('c'); ?>"><?php echo $user->getCreatedDateTime()->format('l, F j, Y'); ?></time></td>
              </tr>
<?php } ?>
          </tbody></table>
        </section>
        <section>
          <hr/>
          <span class="float-left">
<?php if (!$no_prev) { ?>
            <a class="button" href="<?php echo Common::relativeUrlToAbsolute('/user/index?page=' . ($page - 1) . '&limit=' . $limit . '&order=' . $order); ?>">Prev</a>
<?php } else { ?>
            <button class="button button-disabled" disabled="disabled">Prev</button>
<?php } ?>
          </span>
          <span class="float-right">
<?php if (!$no_next) { ?>
              <a class="button" href="<?php echo Common::relativeUrlToAbsolute('/user/index?page=' . ($page + 1) . '&limit=' . $limit . '&order=' . $order); ?>">Next</a>
  <?php } else { ?>
            <button class="button button-disabled" disabled="disabled">Next</button>
<?php } ?>
          </span>
          <p class="center" style="line-height:24px;">
            <strong><?php echo number_format($page); ?></strong> of <?php echo number_format($pages); ?>
          </p>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
