<?php
namespace BNETDocs\Templates;

use \CarlBennett\MVC\Libraries\Common;
use \BNETDocs\Libraries\Pair;

$title       = "Account Login";
$description = "This form allows an individual to log in to their account on BNETDocs";
$this->opengraph->attach(new Pair("url", "/user/login"));

switch ($this->getContext()->error) {
  case "INVALID_CSRF":
    $message = "The Cross-Site Request Forgery token was invalid. "
      . "Either the log in form expired, or "
      . "this may have been a malicious attempt to log you in.";
    break;
  case "ALREADY_LOGGED_IN":
    $message = "You are already logged in, you must log out first.";
    break;
  case "EMPTY_EMAIL":
    $message = "The email address was left blank.";
    break;
  case "USER_NOT_FOUND":
  case "PASSWORD_INCORRECT":
    $message = "Incorrect email address or password.";
    break;
  case "USER_DISABLED":
    $message = "The account has been administratively disabled.";
    break;
  case "USER_NOT_VERIFIED":
    $message = "The account's identity has not been verified yet.";
    break;
  case "LOGIN_DISABLED":
    $message = "Logging in has been administratively disabled indefinitely.";
    break;
  default:
    $message = $this->getContext()->error;
}

$this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
<?php if ($this->getContext()->error !== false) { ?>
        <header>Account Login</header>
<?php if (!empty($message)) { ?>
        <section class="red">
          <p><?php echo $message; ?></p>
        </section>
<?php } ?>
        <form method="POST" action="?">
          <input type="hidden" name="csrf_id" value="<?php echo $this->getContext()->csrf_id; ?>"/>
          <input type="hidden" name="csrf_token" value="<?php echo $this->getContext()->csrf_token; ?>"/>
          <section>
            <label for="email">Email address:</label><br/>
            <input
              type="email"
              name="email"
              id="email"
              value=""
              tabindex="1"
              required
              autocomplete="email"
              autofocus="autofocus"
            />
          </section>
          <section>
            <label for="password">Password:</label><br/>
            <input
              type="password"
              name="password"
              id="password"
              value=""
              tabindex="2"
            />
          </section>
          <section>
            <input
              type="submit"
              value="Log In"
              tabindex="3"
            />
            <a class="button" style="margin-left:8px;"
              href="<?php echo Common::relativeUrlToAbsolute("/user/resetpassword"); ?>"
              tabindex="4"
            >Recover Password</a>
          </section>
        </form>
<?php } else { ?>
        <header class="green">Logged In</header>
        <section class="green">
          <p>You have successfully logged in!</p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
