<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\User;
$title = 'Logout';
$description = 'Log out of the BNETDocs website';
$this->opengraph->attach(new \CarlBennett\MVC\Libraries\Pair('url', '/user/logout'));
require('./header.inc.phtml'); ?>
<div class="container">
<? if (!$this->getContext()->active_user) { ?>
  <h1 class="text-success">Logged Out</h1>
  <div class="alert alert-success">
    <p class="mb-0">You have been successfully logged out!</p>
  </div>
<? } else if ($this->getContext()->error === false) { ?>
  <h1 class="text-danger"><?=$title?></h1>
  <p class="text-danger">If you are sure you wish to log out, press the button below.</p>
  <form method="POST" action="?">
    <input class="btn btn-danger" type="submit" value="Log Out"/>
  </form>
<? } else { ?>
  <h1 class="text-danger">Log out failure</h1>
  <div class="alert alert-danger">
    <p class="mb-0">An error occurred while attempting to log out.</p>
  </secton>
<? } ?>
</div>
<? require('./footer.inc.phtml'); ?>
