<?php

namespace BNETDocs\Templates\User;

use \CarlBennett\MVC\Libraries\Pair;

$title       = "Logout";
$description = "Log out of the BNETDocs website";
$this->opengraph->attach(new Pair("url", "/user/logout"));

switch ($this->getContext()->error) {
  case "NOT_LOGGED_IN":
    $message = "You were not logged in to begin with.";
    break;
  default:
    $message = $this->getContext()->error;
}

$this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
<?php if (is_null($this->getContext()->error)) { ?>
        <header>Account Logout</header>
        <form method="POST" action="?">
          <section>
            <p>If you are sure you wish to log out, press the button below.</p>
            <p><input type="submit" value="Log Out"/></p>
          </section>
        </form>
<?php } else if ($this->getContext()->error === false) { ?>
        <header class="green">Logged Out</header>
        <section class="green">
          <p>You have been successfully logged out!</p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } else { ?>
        <header class="red">Log out failure</header>
        <section class="red">
          <p>An error occurred while attempting to log out.</p>
          <p><?php echo $message; ?></p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
