<?php

namespace BNETDocs\Templates\User;

use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;

$title       = "Reset Password";
$description = "This form allows an individual to reset the password to their account.";
$this->opengraph->attach(new Pair("url", "/user/resetpassword"));

switch ($this->getContext()->error) {
  case "INVALID_CSRF":
    $message = "The Cross-Site Request Forgery token was invalid. Either the"
      . "reset password form expired, or this may have been a malicious"
      . "attempt to reset your password.";
    break;
  case "ALREADY_LOGGED_IN":
    $message = "You are already logged in, you must log out first.";
    break;
  case "EMPTY_EMAIL":
    $message = "The email address was left blank.";
    break;
  case "USER_NOT_FOUND":
    $message = "The email address was not found in our system.";
    break;
  case "USER_DISABLED":
    $message = "The account has been administratively disabled.";
    break;
  default:
    $message = $this->getContext()->error;
}

$this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
<?php if ($this->getContext()->error !== false) { ?>
        <header>Reset Password</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
<?php if (!empty($message)) { ?>
        <section class="red">
          <p><?php echo $message; ?></p>
        </section>
<?php } ?>
        <form method="POST" action="?">
          <input type="hidden" name="csrf_id" value="<?php echo $this->getContext()->csrf_id; ?>"/>
          <input type="hidden" name="csrf_token" value="<?php echo $this->getContext()->csrf_token; ?>"/>
          <section>
            <label for="email">Email address:</label><br/>
            <input
              type="email"
              name="email"
              id="email"
              value="<?php echo filter_var($this->getContext()->email, FILTER_SANITIZE_FULL_SPECIAL_CHARS); ?>"
              tabindex="1"
              required
              autocomplete="email"
              autofocus="autofocus"
            />
          </section>
          <section>
            <input
              type="submit"
              value="Reset Password"
              tabindex="2"
            />
          </section>
        </form>
<?php } else { ?>
        <header class="green">Email Sent</header>
        <section class="green">
          <p>An email has been sent with a link to reset the password.</p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
