<?php

namespace BNETDocs\Templates\User;

use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;

$title       = 'Reset Password';
$description = 'This form allows an individual to reset the password to their account.';
$this->opengraph->attach(new Pair('url', '/user/resetpassword'));

switch ($this->getContext()->error) {
  case 'INVALID_CSRF':
    $message = 'The Cross-Site Request Forgery token was invalid. Either the'
      . 'reset password form expired, or this may have been a malicious'
      . 'attempt to reset your password.';
    break;
  case 'EMPTY_EMAIL':
    $message = 'The email address was left blank.';
    break;
  case 'USER_NOT_FOUND':
    $message = 'The email address was not found in our system.';
    break;
  case 'EMAIL_FAILURE':
    $message = 'The server failed to queue the password reset email.';
    break;
  case 'INVALID_TOKEN':
    $message = 'The token is expired or invalid and therefore cannot be used.';
    break;
  case 'PASSWORD_TOO_LONG':
    $message = 'The password is too long, shorten it.';
    break;
  case 'PASSWORD_TOO_SHORT':
    $message = 'The password is too short, use a better password.';
    break;
  case 'PASSWORD_CONTAINS_EMAIL':
    $message = 'The password contains the email address, '
      . 'use a better password.';
    break;
  case 'PASSWORD_CONTAINS_USERNAME':
    $message = 'The password contains the username, use a better password.';
    break;
  case 'PASSWORD_MISMATCH':
    $message = 'The passwords did not match, please try again.';
    break;
  case 'USER_DISABLED':
    $message = 'The account has been administratively disabled.';
    break;
  default:
    $message = $this->getContext()->error;
}

$this->additional_css[] = '/a/forms.css';
require('./header.inc.phtml');
?>
      <article>
<?php if ($this->getContext()->error !== false) { ?>
        <header>Reset Password</header>
<?php if (!empty($message)) { ?>
        <section class="red">
          <p><?php echo $message; ?></p>
        </section>
<?php } ?>
        <form method="POST" action="?">
          <input type="hidden" name="csrf_id" value="<?=filter_var($this->getContext()->csrf_id, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>"/>
          <input type="hidden" name="csrf_token" value="<?=filter_var($this->getContext()->csrf_token, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>"/>
<?php if (empty($this->getContext()->token)) { ?>
          <section>
            <label for="email">Email address:</label><br/>
            <input
              type="email"
              name="email"
              id="email"
              value="<?=filter_var($this->getContext()->email, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>"
              tabindex="1"
              required
              autocomplete="email"
              autofocus="autofocus"
            />
          </section>
          <section>
            <input
              type="submit"
              value="Reset Password"
              tabindex="2"
            />
          </section>
<?php } else { ?>
          <input type="hidden" name="email" value="<?=filter_var($this->getContext()->email, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>"/>
          <input type="hidden" name="t" value="<?=filter_var($this->getContext()->token, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>"/>
          <section>
            <label for="email">Email address:</label><br/>
            <input type="email" id="email" readonly disabled tabindex="1" value="<?=filter_var($this->getContext()->email, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>"/>
          </section>
          <section>
            <label for="pw1">New Password:</label><br/>
            <input
              type="password"
              name="pw1"
              id="pw1"
              value=""
              tabindex="2"
              required
              autocomplete="new-password"
              autofocus="autofocus"
            />
          </section>
          <section>
            <label for="pw2">Confirm Password:</label><br/>
            <input
              type="password"
              name="pw2"
              id="pw2"
              value=""
              tabindex="3"
              required
              autocomplete="new-password"
            />
          </section>
          <section>
            <input
              type="submit"
              value="Change Password"
              tabindex="4"
            />
          </section>
<?php } ?>
        </form>
<?php } else { ?>
<?php if (empty($this->getContext()->token)) { ?>
        <header class="green">Email Sent</header>
        <section class="green">
          <p>An email has been sent with a link to reset the password.</p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } else { ?>
        <header class="green">Password Changed</header>
        <section class="green">
          <p>Your password has been changed, you may now log in.</p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } ?>
<?php } ?>
      </article>
<?php require('./footer.inc.phtml'); ?>
