<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Verify Account';
$description = 'This form allows an individual to verify their account with a token.';
$this->opengraph->attach( new Pair( 'url', '/user/verify' ));
$error = $this->getContext()->error;
switch ($error)
{
  case 'INVALID_TOKEN': $message = 'The token is expired or invalid and therefore cannot be used.'; break;
  case 'INTERNAL_ERROR': $message = 'An internal error occurred while processing your request. Our staff have been notified of the issue. Try again later.'; break;
  default: $message = $error;
}
$token = filter_var($this->getContext()->token, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$user_id = filter_var($this->getContext()->user_id, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
require('./header.inc.phtml'); ?>
<div class="container">
<? if ($this->getContext()->error !== false) { ?>
  <h1>Verify Account</h1>
<? if (!empty($message)) { ?>
  <div class="alert alert-danger">
    <p class="mb-0"><?=$message?></p>
  </div>
<? } ?>
  <form method="GET" action="?">
    <div class="form-group">
      <label class="font-weight-bold" for="u">User Id:</label>
      <input class="bg-dark border border-primary form-control text-light" type="text" name="u" id="user_id" placeholder="Enter the user id here" value="<?=$user_id?>" tabindex="1"
        required
      /><br/>
    <div class="form-group">
    </div>
      <label class="font-weight-bold" for="t">Token:</label>
      <input class="bg-dark border border-primary form-control text-light" type="text" name="t" id="token" placeholder="Enter the token here" value="<?=$token?>" tabindex="2" required autofocus="autofocus"/>
    </div>
    <div class="form-group">
      <input class="btn btn-success" type="submit" value="Verify Account" tabindex="3"/>
    </div>
  </form>
<? } else { ?>
  <h1 class="text-success">Account Verified</h1>
  <div class="alert alert-success">
    <p class="mb-0">Your account has been verified successfully!</p>
  </div>
<? } ?>
</div>
<? require('./footer.inc.phtml'); ?>
