<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Common;
use \BNETDocs\Libraries\Document;
use \BNETDocs\Libraries\Gravatar;
use \BNETDocs\Libraries\Pair;

$object_id = $this->getContext()->user_id;
$object    = $this->getContext()->user;

$title       = ($object ? $object->getName() : "User Not Found");
$description = ($object ? $object->getName() . "'s user profile on BNETDocs" : "The requested user does not exist or could not be found.");
$this->opengraph->attach(new Pair("url", "/user/" . urlencode($object_id)));
$this->opengraph->attach(new Pair("type", "profile"));

if ($object) {
  $this->opengraph->attach(new Pair("profile:username", $object->getName()));
  
  $gravatar = new Gravatar($object->getEmail());
  $this->opengraph->attach(new Pair("image", "https:" . $gravatar->getUrl(null, "identicon")));

  $safe_name = htmlspecialchars($object->getName(), ENT_HTML5, "UTF-8");

  if ($this->getContext()->biography) $description = $this->getContext()->biography;
  $safe_biography = htmlspecialchars($this->getContext()->biography, ENT_HTML5, "UTF-8");
}

$this->additional_css[] = "/a/userprofile.css";
require("./header.inc.phtml");
?>
      <article>
<?php if ($object) { ?>
        <header>User Profile</header>
        <section class="accountinfo">
          <img class="avatar" src="https:<?php echo $gravatar->getUrl(75, "identicon"); ?>" />
          <strong><?php echo $safe_name; ?></strong><br />
<?php if (!$this->getContext()->biography) { ?>
          <p class="biography"><em>(no biography information.)</em></p>
<?php } else { ?>
          <p class="biography"><?php echo $safe_biography; ?></p>
<?php } ?>
<?php if ($this->getContext()->profiledata) { ?>
          <table class="profiledata"><tbody>
<?php if ($this->getContext()->github) { ?>
            <tr><th class="right">GitHub:</th><td class="left"><a href="<?php echo $this->getContext()->github_uri; ?>"><?php echo htmlspecialchars($this->getContext()->github, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
<?php if ($this->getContext()->reddit) { ?>
            <tr><th class="right">Reddit:</th><td class="left"><a href="<?php echo $this->getContext()->reddit_uri; ?>"><?php echo htmlspecialchars($this->getContext()->reddit, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
<?php if ($this->getContext()->steam_id) { ?>
            <tr><th class="right">Steam:</th><td class="left"><a href="<?php echo $this->getContext()->steam_uri; ?>"><?php echo htmlspecialchars($this->getContext()->steam_id, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
<?php if ($this->getContext()->facebook) { ?>
            <tr><th class="right">Facebook:</th><td class="left"><a href="<?php echo $this->getContext()->facebook_uri; ?>"><?php echo htmlspecialchars($this->getContext()->facebook, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
<?php if ($this->getContext()->twitter) { ?>
            <tr><th class="right">Twitter:</th><td class="left"><a href="<?php echo $this->getContext()->twitter_uri; ?>"><?php echo htmlspecialchars($this->getContext()->twitter, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
<?php if ($this->getContext()->instagram) { ?>
            <tr><th class="right">Instagram:</th><td class="left"><a href="<?php echo $this->getContext()->instagram_uri; ?>"><?php echo htmlspecialchars($this->getContext()->instagram, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
<?php if ($this->getContext()->skype) { ?>
            <tr><th class="right">Skype:</th><td class="left"><a href="skype:<?php echo $this->getContext()->skype_uri; ?>"><?php echo htmlspecialchars($this->getContext()->skype, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
<?php if ($this->getContext()->website) { ?>
            <tr><th class="right">Website:</th><td class="left"><a href="<?php echo $this->getContext()->website_uri; ?>"><?php echo htmlspecialchars($this->getContext()->website, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
          </tbody></table>
<?php } ?>
        </section>
        <header>User Statistics</header>
        <section>
          <table class="stats"><tbody><tr>
          <td><p><strong>Member Since:</strong><br/><time datetime="<?php echo $object->getCreatedDateTime()->format("c"); ?>"><?php echo $object->getCreatedDateTime()->format("D M n, Y"); ?></time> (<?php echo $this->getContext()->user_est; ?>)</p></td>
          <td><p><strong>Owner/Author Of:</strong><br/><?php if ($this->getContext()->contributions == 0) { ?><em>(nothing)</em><?php } else {
            if ($this->getContext()->sum_documents) echo number_format($this->getContext()->sum_documents) . " document" . ($this->getContext()->sum_documents  != 1 ? "s" : "") . "<br/>";
            if ($this->getContext()->sum_news_posts) echo number_format($this->getContext()->sum_news_posts) . " news post" . ($this->getContext()->sum_news_posts  != 1 ? "s" : "") . "<br/>";
            if ($this->getContext()->sum_packets) echo number_format($this->getContext()->sum_packets) . " packet" . ($this->getContext()->sum_packets  != 1 ? "s" : "") . "<br/>";
            if ($this->getContext()->sum_servers) echo number_format($this->getContext()->sum_servers) . " server" . ($this->getContext()->sum_servers  != 1 ? "s" : "") . "<br/>";
          } ?></p></td>
          </tr></tbody></table>
        </section>
<?php } else { ?>
        <header class="red"><?php echo htmlspecialchars($title, ENT_HTML5, "UTF-8"); ?></header>
        <section class="red"><?php echo htmlspecialchars($description, ENT_HTML5, "UTF-8"); ?></section>
<?php } ?>
      </article>
<?php if (isset($this->getContext()->documents)) { ?>
      <article>
        <header>Documents</header>
        <section>
          <ul>
<?php foreach ($this->getContext()->documents as $document) { ?>
            <li><a href="<?php echo Common::relativeUrlToAbsolute("/document/" . urlencode($document->getId()) . "/" . Common::sanitizeForUrl($document->getTitle(), true)); ?>"><?php echo htmlspecialchars($document->getTitle()); ?></a></li>
<?php } ?>
          </ul>
        </section>
      </article>
<?php } ?>
<?php if (isset($this->getContext()->news_posts)) { ?>
      <article>
        <header>News Posts</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php } ?>
<?php if (isset($this->getContext()->packets)) { ?>
      <article>
        <header>Packets</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php } ?>
<?php if (isset($this->getContext()->servers)) { ?>
      <article>
        <header>Servers</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php } ?>
<?php require("./footer.inc.phtml"); ?>
