<?php

namespace BNETDocs\Templates\User;

use \BNETDocs\Libraries\Document;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;

$object_id = $this->getContext()->user_id;
$object    = $this->getContext()->user;

$title       = ($object ? $object->getName() : "User Not Found");
$description = ($object ? $object->getName() . "'s user profile on BNETDocs" : "The requested user does not exist or could not be found.");

$this->opengraph->attach(new Pair("type", "profile"));

$url = Common::relativeUrlToAbsolute("/user/" . urlencode($object_id));

if ($object) {

  $url = $object->getURI();

  $this->opengraph->attach(new Pair("profile:username", $object->getName()));

  $this->opengraph->attach(new Pair("image", $object->getAvatarURI(null)));

  $safe_name = htmlspecialchars($object->getName(), ENT_HTML5, "UTF-8");

  if ($this->getContext()->biography) $description = $this->getContext()->biography;
  $safe_biography = htmlspecialchars($this->getContext()->biography, ENT_HTML5, "UTF-8");

}

$this->opengraph->attach(new Pair("url", $url));

$this->additional_css[] = "/a/userprofile.css";
require("./header.inc.phtml");
?>
      <article>
<?php if ($object) { ?>
        <a href="https://twitter.com/share?text=<?php echo urlencode($title); ?>&amp;url=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-twitter-24px.png"); ?>"/></a>
        <a href="https://facebook.com/sharer/sharer.php?u=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-facebook-24px.png"); ?>"/></a>
        <header>User Profile</header>
        <section class="accountinfo">
          <img class="avatar" src="<?php echo $object->getAvatarURI(80); ?>" />
          <strong><?php echo $safe_name; ?></strong><br />
<?php if (!$this->getContext()->biography) { ?>
          <p class="biography"><em>(no biography information.)</em></p>
<?php } else { ?>
          <p class="biography"><?php echo $safe_biography; ?></p>
<?php } ?>
        </section>
<?php if ($this->getContext()->profiledata) { ?>
        <section class="profiledata">
<?php if ($this->getContext()->github) { ?>
          <span><strong>GitHub:</strong> <a href="<?php echo $this->getContext()->github_uri; ?>"><?php echo htmlspecialchars($this->getContext()->github, ENT_HTML5, "UTF-8"); ?></a></span>
<?php } ?>
<?php if ($this->getContext()->reddit) { ?>
          <span><strong>Reddit:</strong> <a href="<?php echo $this->getContext()->reddit_uri; ?>"><?php echo htmlspecialchars($this->getContext()->reddit, ENT_HTML5, "UTF-8"); ?></a></span>
<?php } ?>
<?php if ($this->getContext()->steam_id) { ?>
          <span><strong>Steam:</strong> <a href="<?php echo $this->getContext()->steam_uri; ?>"><?php echo htmlspecialchars($this->getContext()->steam_id, ENT_HTML5, "UTF-8"); ?></a></span>
<?php } ?>
<?php if ($this->getContext()->facebook) { ?>
          <span><strong>Facebook:</strong> <a href="<?php echo $this->getContext()->facebook_uri; ?>"><?php echo htmlspecialchars($this->getContext()->facebook, ENT_HTML5, "UTF-8"); ?></a></span>
<?php } ?>
<?php if ($this->getContext()->twitter) { ?>
          <span><strong>Twitter:</strong> <a href="<?php echo $this->getContext()->twitter_uri; ?>"><?php echo htmlspecialchars($this->getContext()->twitter, ENT_HTML5, "UTF-8"); ?></a></span>
<?php } ?>
<?php if ($this->getContext()->instagram) { ?>
          <span><strong>Instagram:</strong> <a href="<?php echo $this->getContext()->instagram_uri; ?>"><?php echo htmlspecialchars($this->getContext()->instagram, ENT_HTML5, "UTF-8"); ?></a></span>
<?php } ?>
<?php if ($this->getContext()->skype) { ?>
          <span><strong>Skype:</strong> <a href="<?php echo $this->getContext()->skype_uri; ?>"><?php echo htmlspecialchars($this->getContext()->skype, ENT_HTML5, "UTF-8"); ?></a></span>
<?php } ?>
<?php if ($this->getContext()->website) { ?>
          <span><strong>Website:</strong> <a href="<?php echo $this->getContext()->website_uri; ?>"><?php echo htmlspecialchars($this->getContext()->website, ENT_HTML5, "UTF-8"); ?></a></span>
<?php } ?>
        </section>
<?php } ?>
        <header>User Statistics</header>
        <section>
          <table class="stats"><tbody><tr>
          <td><p><strong>Member Since:</strong><br/><time datetime="<?php echo $object->getCreatedDateTime()->format("c"); ?>"><?php echo $object->getCreatedDateTime()->format("D M j, Y"); ?></time> (<?php echo $this->getContext()->user_est; ?>)</p></td>
          <td><p><strong>Owner/Author Of:</strong><br/><?php if ($this->getContext()->contributions == 0) { ?><em>(nothing)</em><?php } else {
            if ($this->getContext()->sum_documents) echo number_format($this->getContext()->sum_documents) . " document" . ($this->getContext()->sum_documents  != 1 ? "s" : "") . "<br/>";
            if ($this->getContext()->sum_news_posts) echo number_format($this->getContext()->sum_news_posts) . " news post" . ($this->getContext()->sum_news_posts  != 1 ? "s" : "") . "<br/>";
            if ($this->getContext()->sum_packets) echo number_format($this->getContext()->sum_packets) . " packet" . ($this->getContext()->sum_packets  != 1 ? "s" : "") . "<br/>";
            if ($this->getContext()->sum_servers) echo number_format($this->getContext()->sum_servers) . " server" . ($this->getContext()->sum_servers  != 1 ? "s" : "") . "<br/>";
          } ?></p></td>
          </tr></tbody></table>
        </section>
<?php } else { ?>
        <header class="red"><?php echo htmlspecialchars($title, ENT_HTML5, "UTF-8"); ?></header>
        <section class="red"><?php echo htmlspecialchars($description, ENT_HTML5, "UTF-8"); ?></section>
<?php } ?>
      </article>
<?php if (isset($this->getContext()->documents)) { ?>
      <article>
        <header>Documents</header>
        <section>
          <table><tbody>
<?php foreach ($this->getContext()->documents as $document) { ?>
            <tr><td><a href="<?php echo $document->getURI(); ?>"><?php echo htmlspecialchars($document->getTitle()); ?></a></td></tr>
<?php } ?>
          </tbody></table>
        </section>
      </article>
<?php } ?>
<?php if (isset($this->getContext()->news_posts)) { ?>
      <article>
        <header>News Posts</header>
        <section>
          <table><tbody>
<?php foreach ($this->getContext()->news_posts as $news_post) { ?>
            <tr><td><a href="<?php echo $news_post->getURI(); ?>"><?php echo htmlspecialchars($news_post->getTitle()); ?></a></td></tr>
<?php } ?>
          </tbody></table>
        </section>
      </article>
<?php } ?>
<?php if (isset($this->getContext()->packets)) { ?>
      <article>
        <header>Packets</header>
        <section>
          <table><tbody>
<?php foreach ($this->getContext()->packets as $packet) { ?>
            <tr><td><a href="<?php echo $packet->getURI(); ?>"><?php echo htmlspecialchars($packet->getPacketDirectionTag(), ENT_HTML5, "UTF-8"); ?> <?php echo htmlspecialchars($packet->getPacketId(true), ENT_HTML5, "UTF-8"); ?> <?php echo htmlspecialchars($packet->getPacketName()); ?></a></td></tr>
<?php } ?>
          </tbody></table>
        </section>
      </article>
<?php } ?>
<?php if (isset($this->getContext()->servers)) { ?>
      <article>
        <header>Servers</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php } ?>
<?php require("./footer.inc.phtml"); ?>
