<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Common;
use \BNETDocs\Libraries\Gravatar;
use \BNETDocs\Libraries\Pair;
use \BNETDocs\Libraries\User;

$title       = "Contributors";
$description = "The top contributors to BNETDocs grouped by different types of content.";
$this->opengraph->attach(new Pair("url", "/credits"));

$users = [];

$avatars = [];
$getAvatar = function(&$avatars, User $user) {
  $user_id = $user->getId();
  if (isset($avatars[$user_id])) {
    return $avatars[$user_id];
  }
  $avatars[$user_id] = new Gravatar($user->getEmail());
  return $avatars[$user_id];
};

$this->additional_css[] = "/a/credits.css";
require("./header.inc.phtml");
?>
      <article>
        <header>Contributors</header>
        <section>
          <p>We have a total of <?php echo number_format($this->context->total_users); ?> users, of which the following are our top contributors grouped by content.</p>
        </section>
        <header>Documents</header>
        <section>
          <table><thead>
            <tr>
              <th class="rank">Rank</th>
              <th class="who">Who</th>
              <th class="sum">Sum</th>
            </tr>
          </thead><tbody>
<?php $rank = 0; foreach ($this->context->top_contributors_by_documents as $item) {
        ++$rank;
        if (is_null($item->user_id)) {
          $pfx = ""; $sfx = "";
        } else {
          if (!isset($users[$item->user_id])) $users[$item->user_id] = new User($item->user_id);
          $pfx = "<a href=\"" . Common::relativeUrlToAbsolute("/user/" . urlencode($item->user_id) . "/"
            . Common::sanitizeForUrl($users[$item->user_id]->getName(), true)) . "\">"
            . "<img class=\"avatar\" src=\"https:"
            . $getAvatar($avatars, $users[$item->user_id])->getUrl(22, "identicon")
            . "\"/> ";
          $sfx = "</a>";
        }
?>
            <tr><td><?php echo $rank; ?></td><td><?php echo $pfx.$item->name.$sfx; ?></td><td><?php echo number_format($item->documents_authored); ?> document<?php echo ($item->documents_authored != 1 ? "s" : ""); ?></td></tr>
<?php } ?>
          </tbody></table>
        </section>
        <header>News Posts</header>
        <section>
          <table><thead>
            <tr>
              <th class="rank">Rank</th>
              <th class="who">Who</th>
              <th class="sum">Sum</th>
            </tr>
          </thead><tbody>
<?php $rank = 0; foreach ($this->context->top_contributors_by_news_posts as $item) {
        ++$rank;
        if (is_null($item->user_id)) {
          $pfx = ""; $sfx = "";
        } else {
          if (!isset($users[$item->user_id])) $users[$item->user_id] = new User($item->user_id);
          $pfx = "<a href=\"" . Common::relativeUrlToAbsolute("/user/" . urlencode($item->user_id) . "/"
            . Common::sanitizeForUrl($users[$item->user_id]->getName(), true)) . "\">"
            . "<img class=\"avatar\" src=\"https:"
            . $getAvatar($avatars, $users[$item->user_id])->getUrl(22, "identicon")
            . "\"/> ";
          $sfx = "</a>";
        }
?>
            <tr><td><?php echo $rank; ?></td><td><?php echo $pfx.$item->name.$sfx; ?></td><td><?php echo number_format($item->news_posts_created); ?> news post<?php echo ($item->news_posts_created != 1 ? "s" : ""); ?></td></tr>
<?php } ?>
          </tbody></table>
        </section>
        <header>Packets</header>
        <section>
          <table><thead>
            <tr>
              <th class="rank">Rank</th>
              <th class="who">Who</th>
              <th class="sum">Sum</th>
            </tr>
          </thead><tbody>
<?php $rank = 0; foreach ($this->context->top_contributors_by_packets as $item) {
        ++$rank;
        if (is_null($item->user_id)) {
          $pfx = ""; $sfx = "";
        } else {
          if (!isset($users[$item->user_id])) $users[$item->user_id] = new User($item->user_id);
          $pfx = "<a href=\"" . Common::relativeUrlToAbsolute("/user/" . urlencode($item->user_id) . "/"
            . Common::sanitizeForUrl($users[$item->user_id]->getName(), true)) . "\">"
            . "<img class=\"avatar\" src=\"https:"
            . $getAvatar($avatars, $users[$item->user_id])->getUrl(22, "identicon")
            . "\"/> ";
          $sfx = "</a>";
        }
?>
            <tr><td><?php echo $rank; ?></td><td><?php echo $pfx.$item->name.$sfx; ?></td><td><?php echo number_format($item->packets_authored); ?> packet<?php echo ($item->packets_authored != 1 ? "s" : ""); ?></td></tr>
<?php } ?>
          </tbody></table>
        </section>
        <header>Servers</header>
        <section>
          <table><thead>
            <tr>
              <th class="rank">Rank</th>
              <th class="who">Who</th>
              <th class="sum">Sum</th>
            </tr>
          </thead><tbody>
<?php $rank = 0; foreach ($this->context->top_contributors_by_servers as $item) {
        ++$rank;
        if (is_null($item->user_id)) {
          $pfx = ""; $sfx = "";
        } else {
          if (!isset($users[$item->user_id])) $users[$item->user_id] = new User($item->user_id);
          $pfx = "<a href=\"" . Common::relativeUrlToAbsolute("/user/" . urlencode($item->user_id) . "/"
            . Common::sanitizeForUrl($users[$item->user_id]->getName(), true)) . "\">"
            . "<img class=\"avatar\" src=\"https:"
            . $getAvatar($avatars, $users[$item->user_id])->getUrl(22, "identicon")
            . "\"/> ";
          $sfx = "</a>";
        }
?>
            <tr><td><?php echo $rank; ?></td><td><?php echo $pfx.$item->name.$sfx; ?></td><td><?php echo number_format($item->servers_owned); ?> server<?php echo ($item->servers_owned != 1 ? "s" : ""); ?></td></tr>
<?php } ?>
          </tbody></table>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
