<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Donate';
$description = 'Donate to BNETDocs to show your support for this project!';
$this->opengraph->attach(new Pair('url', '/donate'));
$this->opengraph->attach(new Pair('type', 'article'));
$btc_address = $this->getContext()->donations->btc_address;
$email_address = $this->getContext()->donations->email_address;
$paypal_url = $this->getContext()->donations->paypal_url;
$user_id = $this->getContext()->donations->user_id;
$user = (!empty($user_id) ? new \BNETDocs\Libraries\User($user_id) : null);
require('./header.inc.phtml'); ?>
<div class="container">
  <h1>Support Us</h1>
  <p>The following are the methods available for supporting us:</p>
  <ul type="circle">
<? if ($user) { ?>
  <li>Contact: <a href="<?=$user->getURI()?>"><?=filter_var($user->getName(), FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></a></li>
<? } ?>
<? if (!empty($paypal_url)) { ?>
  <li>PayPal: <a href="<?=filter_var($paypal_url, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>"><?=filter_var($paypal_url, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></a></li>
<? } ?>
<? if (!empty($btc_address)) { ?>
  <li>BTC: <code><?=$btc_address?></code></li>
<? } ?>
<? if (!empty($email_address)) { ?>
  <li>Email us: <a href="mailto:<?=rawurlencode($email_address)?>"><?=filter_var($email_address, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></a></li>
<? } ?>
  </ul>
  <h3>Disclaimer</h3>
  <p>By donating to BNETDocs, you understand the following:</p>
  <ol>
    <li>The donation is non-refundable.</li>
    <li>The donation's purpose is to pay for hosting of this website and all associated costs, and to further the development of open-source software (OSS).</li>
    <li>A donation is not acceptable as payment for goods, products, or merchant items.</li>
    <li>In absolutely no scenario will a donation be used to willfully violate Blizzard Entertainment's Terms of Service or Battle.net's Terms of Service.</li>
  </ol>
  <p>Please see our <a href="<?=Common::relativeUrlToAbsolute('/legal')?>">Legal</a> and <a href="<?=Common::relativeUrlToAbsolute('/privacy')?>">Privacy Policy</a> pages for more info.</p>
</div>
<? require('./footer.inc.phtml'); ?>
