<?php

namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Logger;
use \BNETDocs\Libraries\VersionInfo;
use \CarlBennett\MVC\Libraries\Common;

?>
    </main>
    <footer class="main-page<?php if (isset($slim_ui) && $slim_ui) { ?> slim<?php } ?>">
      <a href="https://github.com/BNETDocs/bnetdocs-web/tree/<?php echo VersionInfo::$version->bnetdocs[1]; ?>" rel="external" title="Contribute to the BNETDocs source code!">BNETDocs <?php echo VersionInfo::$version->bnetdocs[0]; ?></a> &copy; 2003-2018 <a href="<?php echo Common::relativeUrlToAbsolute("/legal"); ?>" rel="external" title="BNETDocs Legal Policies">BNETDocs</a><br/>
      BNETDocs is in no way affiliated with or endorsed by Blizzard Entertainment&trade; or its brands, and is not intended to compete with or undermine Blizzard Entertainment&trade; or Battle.net&trade;. Persons using this software understand that the information provided within is collected knowledge from years of observations and may be inaccurate. All aforementioned trademarks are the property of their respective owners.<br/>
    </footer>
<?php echo Logger::getTimingFooter(); ?>
  </body>
</html>
