<!DOCTYPE html>
<html>
  <head>
    <title>Error &ndash; BNETDocs</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <style type="text/css" media="all">
      body {
        background: #272727 url("/a/main_bg.png") repeat fixed center;
        color: #ddd;
        font: 11pt source sans pro, verdana, arial, sans-serif;
        margin: 48px 0px 0px 0px;
        padding: 0px;
      }
      a,a:focus {
        outline: none;
      }
      a:hover {
        text-decoration: underline;
      }
      a:link {
        color: #00c0ff;
        text-decoration: none;
      }
      a:visited {
        color: #00a0cf;
      }
      header.main-page {
        background-color: rgba(64,64,64,0.8);
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        cursor: default;
        color: rgba(0,222,180,0.9);
        font: 20pt source sans pro, verdana, arial, sans-serif;
        left: 0px;
        line-height: 32px;
        padding: 8px 12px;
        position: fixed;
        right: 0px;
        top: 0px;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      main {
        overflow: hidden;
        width: 100%;
      }
      main > article,
      main.slim > article {
        margin: 10px auto;
        max-width: 600px;
        overflow: hidden;
      }
      main > article:first-of-type,
      main.slim > article:first-of-type {
        margin-top: 10px;
      }
      main > article:last-of-type,
      main.slim > article:last-of-type {
        margin-bottom: 0px;
      }
      main > article > header {
        background-color: rgba(64,64,64,0.6);
        display: block;
        font: 14pt source sans pro;
        padding: 10px;
      }
      main > article header.red {
        background-color: rgba(128,64,64,0.6);
      }
      main > article .header-button {
        border-radius: 4px;
        box-shadow: inset 0 0 10px rgba(0,0,0,0.5);
        display: inline-block;
        height: 24px;
        line-height: 24px;
        margin: 4px 4px 4px 0px;
        padding: 6px;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        vertical-align: top;
      }
      main > article section {
        background-color: rgba(64,64,64,0.4);
        padding: 10px;
      }
      main > article section.red {
        background-color: rgba(128,64,64,0.4);
      }
      main > article section > p:first-of-type {
        margin-top: 0px;
      }
      main > article section > p:last-of-type {
        margin-bottom: 0px;
      }
      main > article section img {
        max-width: 100%;
      }
      main > article > footer {
        background-color: rgba(64, 64, 64, 0.6);
        display: block;
        font: 12pt source sans pro;
        margin: 0px;
        min-height: 20px;
        padding: 10px;
      }
    </style>
  </head>
  <body>
    <header class="main-page">BNETDocs</header>
    <main class="slim">
      <article>
        <header class="red">Internal Error</header>
        <section class="red">
          <p>An internal server error occurred while processing your request.</p>
          <p>The BNETDocs staff has been notified of this issue.</p>
          <p>Please <a href="https://github.com/BNETDocs/bnetdocs-web/issues/new?title=Internal+Error">report this issue to GitHub</a> if it persists.</p>
        </section>
      </article>
    </main>
  </body>
</html>
