<?php

namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Authentication;
use \BNETDocs\Libraries\Logger;
use \BNETDocs\Libraries\User;
use \BNETDocs\Libraries\VersionInfo;

use \CarlBennett\MVC\Libraries\Common;

if ( isset( Authentication::$user  )) {
  $_header_user     = Authentication::$user;
  $_header_user_url = $_header_user->getURI();
  $_header_staff    = ($_header_user && $_header_user->isStaff());
} else {
  $_header_user     = null;
  $_header_user_url = null;
  $_header_staff    = null;
}

$_header_navigation_config = Common::$config->bnetdocs->navigation;
$_header_user_register_disabled = Common::$config->bnetdocs->user_register_disabled;

if ( !Common::$config->bnetdocs->asset_versioning ) {
  $_unique_asset = '';
} else if ( !is_null( VersionInfo::$version->bnetdocs )) {
  $_unique_asset = '?v=' . VersionInfo::$version->bnetdocs[1];
} else {
  $_unique_asset = '?v=' . date('YmdHis');
}

$_campaign_battleforthenet = (
  !empty( Common::$config->bnetdocs->campaigns->battleforthenet ) ?
  '<script type="text/javascript" src="' .
  Common::relativeUrlToAbsolute(
    Common::$config->bnetdocs->campaigns->battleforthenet
  ) . '" async><![CDATA[]]></script>' . PHP_EOL : ''
);
$_campaign_vultr = (
  !empty( Common::$config->bnetdocs->campaigns->vultr ) ?
  '<a href="' . Common::relativeUrlToAbsolute(
    Common::$config->bnetdocs->campaigns->vultr
  ) . '"><img id="vultr-campaign" src="' . Common::relativeUrlToAbsolute(
    '/a/vultr_logo_ondark.svg'
  ) . '"/></a>'  : ''
);

?><!DOCTYPE html>
<html lang="en-US">
  <head>
<?php echo Logger::getTimingHeader(); ?>
    <title><?php echo $title; ?> - BNETDocs</title>
<?php if (isset($url) && !empty($url)) { ?>
    <link rel="canonical" href="<?php echo $url; ?>"/>
<?php } ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<?php if (Common::$config->bnetdocs->mobile_site_enabled) { ?>
    <link rel="stylesheet" href="<?php echo Common::relativeUrlToAbsolute('/a/main.css' . $_unique_asset); ?>" type="text/css" media="(min-width:1000px)"/>
    <link rel="stylesheet" href="<?php echo Common::relativeUrlToAbsolute('/a/main-mobile.css' . $_unique_asset); ?>" type="text/css" media="(max-width:999px)"/>
<?php } else { ?>
    <link rel="stylesheet" href="<?php echo Common::relativeUrlToAbsolute('/a/main.css' . $_unique_asset); ?>" type="text/css" media="all"/>
<?php }
      foreach ($this->additional_css as $path) { ?>
    <link rel="stylesheet" type="text/css" href="<?php echo Common::relativeUrlToAbsolute($path . $_unique_asset); ?>" media="all"/>
<?php } ?>
    <link rel="icon" href="<?php echo Common::relativeUrlToAbsolute('/a/VSZX0bJ.png'); ?>" type="image/png" sizes="156x174"/>
    <link rel="stylesheet" type="text/css" href="<?php echo Common::relativeUrlToAbsolute('/a/font/SourceSansPro-Regular-201508251844.css'); ?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo Common::relativeUrlToAbsolute('/a/font/SourceCodePro-Regular-201508251844.css'); ?>"/>
    <script type="text/javascript" src="<?php echo Common::relativeUrlToAbsolute('/a/BNETDocs.js' . $_unique_asset); ?>" async><![CDATA[]]></script>
    <?php echo $_campaign_battleforthenet; ?>
    <link rel="alternate" href="<?php echo Common::relativeUrlToAbsolute('/news.rss'); ?>" type="application/rss+xml" title="BNETDocs News"/>
    <link rel="license" href="<?php echo Common::relativeUrlToAbsolute('/legal'); ?>"/>
    <meta name="keywords" content="battle.net,starcraft,warcraft,diablo,blizzard,logon sequences,packets,information,protocols,reference,programming,coding"/>
<?php if (!empty($description)) { ?>
    <meta name="description" content="<?php echo $description; ?>"/>
    <meta property="og:description" content="<?php echo $description; ?>"/>
    <meta property="twitter:description" content="<?php echo $description; ?>"/>
<?php } ?>
    <meta property="og:site_name" content="BNETDocs"/>
    <meta property="og:locale" content="en_US"/>
    <meta property="twitter:card" content="summary"/>
    <meta property="twitter:site" content="@BNETDocs"/>
    <meta property="og:title" content="<?php echo $title; ?>"/>
    <meta property="twitter:title" content="<?php echo $title; ?>"/>
<?php
    $ogimage = false; $ogtype = false;
    foreach ($this->opengraph as $og) {
      $ogkey = $og->getKey();
      $ogval = $og->getValue();
      if ($ogkey == "image") $ogimage = true;
      if ($ogkey == "type") $ogtype = true;
      if ($ogkey == "url" || $ogkey == "image") $ogval = Common::relativeUrlToAbsolute($ogval);
?>
    <meta property="og:<?php echo $ogkey; ?>" content="<?php echo $ogval; ?>"/>
<?php } if (!$ogimage) { ?>
    <meta property="og:image" content="<?php echo Common::relativeUrlToAbsolute("/a/eNoi70A.png"); ?>"/>
<?php } if (!$ogtype) { ?>
    <meta property="og:type" content="website"/>
<?php } ?>
  </head>
  <body>
    <header class="main-page"><a href="<?php echo Common::relativeUrlToAbsolute($_header_navigation_config->front_page); ?>"><img src="<?php echo Common::relativeUrlToAbsolute("/a/VSZX0bJ.png"); ?>" style="float:left;margin-right:6px;height:32px;"/> BNETDocs</a> <span id="mobile-nav">&#9776;</span><?php echo $_campaign_vultr; ?></header>
<?php if (!(isset($slim_ui) && $slim_ui)) { ?>
    <nav>
      <a>Info Hub</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/welcome"); ?>">Welcome</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/credits"); ?>">Contributors</a>
<?php if (Common::$config->discord->enabled) { ?>
      <a href="<?php echo Common::relativeUrlToAbsolute("/discord"); ?>">Discord</a>
<?php } ?>
      <a href="<?php echo Common::relativeUrlToAbsolute("/donate"); ?>">Donate</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/user/index"); ?>">Members</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/news"); ?>">News</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/servers"); ?>">Servers</a>
      <a>Account</a>
<?php if ($_header_user) { ?>
      <a href="<?php echo Common::relativeUrlToAbsolute("/user/logout"); ?>">Logout</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/user/changepassword"); ?>">Change Password</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/user/update"); ?>">Update Profile</a>
      <a href="<?php echo Common::relativeUrlToAbsolute($_header_user_url); ?>">View Profile</a>
<?php } else { ?>
      <a href="<?php echo Common::relativeUrlToAbsolute("/user/login"); ?>">Log In</a>
<?php if (!$_header_user_register_disabled) { ?>
      <a href="<?php echo Common::relativeUrlToAbsolute("/user/register"); ?>">Create</a>
<?php } ?>
<?php } ?>
      <a>The Docs</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/document/index"); ?>">Document Index</a>
<?php if (!$_header_navigation_config->hide_search_documents) { ?>
      <a href="<?php echo Common::relativeUrlToAbsolute("/document/search"); ?>">Search Documents</a>
<?php } ?>
<?php if (!$_header_navigation_config->hide_popular_documents) { ?>
      <a href="<?php echo Common::relativeUrlToAbsolute("/document/popular"); ?>">Popular Documents</a>
<?php } ?>
      <a href="<?php echo Common::relativeUrlToAbsolute("/packet/index"); ?>">Packet Index</a>
<?php if (!$_header_navigation_config->hide_search_packets) { ?>
      <a href="<?php echo Common::relativeUrlToAbsolute("/packet/search"); ?>">Search Packets</a>
<?php } ?>
<?php if (!$_header_navigation_config->hide_popular_packets) { ?>
      <a href="<?php echo Common::relativeUrlToAbsolute("/packet/popular"); ?>">Popular Packets</a>
<?php } ?>
      <a>Other Pages</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("//files.bnetdocs.org/"); ?>">File Archive</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/legal"); ?>">Legal Policies</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("//redux.bnetdocs.org/"); ?>">BNETDocs Redux</a>
<?php if ($_header_staff) { ?>
      <a>Site Admin</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/document/create"); ?>">Create Document</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/news/create"); ?>">Create News Post</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/packet/create"); ?>">Create Packet</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/server/create"); ?>">Create Server</a>
      <a href="<?php echo Common::relativeUrlToAbsolute("/eventlog/index"); ?>">Event Log</a>
<?php } ?>
    </nav>
    <main>
<?php } else { ?>
    <main class="slim">
<?php } ?>
