<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates;
$title = 'Maintenance';
$description = $this->getContext()->message;
require('./header.inc.phtml'); ?>
<div class="container">
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><?=$title?></h4>
    <p class="mb-0"><?=$description?></p>
  </div>
</div>
<?php require('./footer.inc.phtml'); ?>
