<?php
namespace BNETDocs\Templates;

use \CarlBennett\MVC\Libraries\Common;
?>
<?xml version="1.0"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <atom:link href="<?php echo Common::relativeUrlToAbsolute("/news.rss"); ?>" rel="self" type="application/rss+xml" />
    <title>BNETDocs News</title>
    <link><?php echo Common::relativeUrlToAbsolute("/news"); ?></link>
    <description>The community that maintains Battle.net&#8482; protocol documentation for the purpose of educating the public of how enterprise protocols work.</description>
    <language>en-us</language>
    <docs>http://www.tutorialspoint.com/rss</docs>
    <ttl>300</ttl>
<?php foreach ($this->context->news_posts as $news_post) { ?>
    <item>
      <title><?php echo htmlentities($news_post->getTitle(), ENT_XML1, "UTF-8"); ?></title>
      <link><?php echo htmlentities($news_post->getURI(), ENT_XML1, "UTF-8"); ?></link>
      <category><?php echo htmlentities($news_post->getCategory()->getLabel(), ENT_XML1, "UTF-8"); ?></category>
      <description><?php echo htmlentities(html_entity_decode($news_post->getContent(true), ENT_HTML5, "UTF-8"), ENT_XML1, "UTF-8"); ?></description>
      <pubDate><?php echo htmlentities($news_post->getPublishedDateTime()->format("r"), ENT_XML1, "UTF-8"); ?></pubDate>
      <guid><?php echo htmlentities(Common::relativeUrlToAbsolute("/news/" . $news_post->getId()), ENT_XML1, "UTF-8"); ?></guid>
    </item>
<?php } ?>
  </channel>
</rss>
