<?php /* vim: set colorcolumn=: */
namespace BNETDocs\Templates;
$title = 'Page Not Found';
$description = 'The requested resource does not exist or could not be found.';
require('./header.inc.phtml'); ?>
<div class="container">
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><?=$title?></h4>
    <p class="mb-0"><?=$description?></p>
  </div>
</div>
<?php require('./footer.inc.phtml'); ?>
