<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;

$title = 'Privacy Notice';
$this->opengraph->attach(new Pair('url', '/privacy'));
$this->opengraph->attach(new Pair('type', 'article'));

$data_location = $this->getContext()->data_location;
$email_domain = $this->getContext()->email_domain;
$email_mailbox = $this->getContext()->email_mailbox;
$org = $this->getContext()->organization;
$description = sprintf('%s is committed to privacy and security for all of its users. This privacy notice will explain how %s uses the personal data collected from you when you use the site.', $org, $org);

require('./header.inc.phtml'); ?>
<div class="container">
  <h1><?=$title?></h1>
    <p><?=$description?></p>
    <h2 class="font-weight-bold">Topics</h2>
    <p><ul>
      <li><a href="#what-data-is-collected">What data is collected?</a></li>
      <li><a href="#how-is-your-data-collected">How is your data collected?</a></li>
      <li><a href="#how-will-your-data-be-used">How will your data be used?</a></li>
      <li><a href="#how-is-your-data-stored">How is your data stored?</a></li>
      <li><a href="#what-are-your-data-protection-rights">What are your data protection rights?</a></li>
      <li><a href="#what-are-cookies">What are cookies?</a></li>
      <li><a href="#how-are-cookies-used">How are cookies used?</a></li>
      <li><a href="#what-types-of-cookies-are-used">What types of cookies are used?</a></li>
      <li><a href="#how-to-manage-your-cookies">How to manage your cookies</a></li>
      <li><a href="#privacy-policies-of-other-websites">Privacy policies of other websites</a></li>
      <li><a href="#changes-to-the-privacy-notice">Changes to the privacy notice</a></li>
      <li><a href="#how-to-contact">How to contact</a></li>
    </ul></p>

    <h2><a id="what-data-is-collected">What data is collected?</a></h2>
    <p>The following private data is collected:<ul>
      <li>The IP address, user agent, and requested url of all clients accessing the site, used for logging and tracking of actions on the site.</li>
      <li>A person's email address and username, used for user account authentication and identification on the site.</li>
      <li>A user account password, used for authentication.</li>
      <li>An optional alternative custom name different from the username, used for identification on the site.</li>
      <li>Contact and social media information, freely given by the user during updates to their public user profile, and not necessary for the function of the site nor their user account.</li>
    </ul></p>

    <h2><a id="how-is-your-data-collected">How is your data collected?</a></h2>
    <p>You directly provide <?=$org?> with most of the data that is collected. <?=$org?> collects data and processes data when you:</p>
    <p><ul>
      <li>Create a user account on the site, or modify your user profile on the site.</li>
      <li>Submit, post, or upload media and/or content to the site.</li>
    </ul></p>

    <h2><a id="how-will-your-data-be-used">How will your data be used?</a></h2>
    <p><?=$org?> collects your data for the following purposes:</p>
    <p><ul>
      <li>To process your requests in cooperation with site features.</li>
      <li>To track user actions taken on the site.</li>
    </ul></p>

    <h2><a id="how-is-your-data-stored">How is your data stored?</a></h2>
    <p><?=$org?> uses a relational database schema hosted in <?=filter_var($data_location, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>. The full system is backed up via machine snapshots, and the data is not accessible without two-factor authentication. A firewall exists between the online database and the rest of the Internet, which by its nature prevents any unknown traffic from reaching the data. Database backups are created at regular intervals via cronjob or similar automated processes, and the backups are uploaded to an authenticated third-party redundant location.</p>

    <h2><a id="what-are-your-data-protection-rights">What are your data protection rights?</a></h2>
    <p><?=$org?> would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:</p>
    <p><ul>
      <li>The right to access – You have the right to request <?=$org?> for copies of your personal data.</li>
      <li>The right to rectification – You have the right to request that <?=$org?> correct any information you believe is inaccurate. You also have the right to request <?=$org?> to complete the information you believe is incomplete.</li>
      <li>The right to erasure – You have the right to request that <?=$org?> erase your personal data, under certain conditions.</li>
      <li>The right to restrict processing – You have the right to request that <?=$org?> restrict the processing of your personal data, under certain conditions.</li>
      <li>The right to object to processing – You have the right to object to <?=$org?>'s processing of your personal data, under certain conditions.</li>
      <li>The right to data portability – You have the right to request that <?=$org?> transfer the data that we have collected to another organization, or directly to you, under certain conditions.</li>
    </ul></p>
    <p>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please <a href="#how-to-contact">make contact</a> using the information below.</p>

    <h2><a id="what-are-cookies">What are cookies?</a></h2>
    <p>Cookies are text files placed on your computer to collect standard Internet log information and visitor behavior information. When you visit the site, some information from you may be collected automatically through cookies or similar technology.</p>
    <p>For further information, visit <a href="https://allaboutcookies.org/">allaboutcookies.org</a>.</p>

    <h2><a id="how-are-cookies-used">How are cookies used?</a></h2>
    <p><?=$org?> uses cookies for the following purposes:</p>
    <p><ul>
      <li>To record cookie preferences for the site.</li>
      <li>To identify you as a returning user of the site, so you may stay logged in to your user account between visits.</li>
    </ul></p>

    <h2><a id="what-types-of-cookies-are-used">What types of cookies are used?</a></h2>
    <p><?=$org?> uses functional cookies so that the site will recognize you and remember your previously selected preferences. All important cookies are first-party cookies, any and all third-party cookies may be allowed as desired.</p>

    <h2><a id="how-to-manage-your-cookies">How to manage your cookies</a></h2>
    <p>You can set your browser not to accept cookies, and the website <a href="https://allaboutcookies.org/">allaboutcookies.org</a> tells you how to remove cookies from your browser. However, some of the site features may not function as a result.</p>

    <h2><a id="privacy-policies-of-other-websites">Privacy policies of other websites</a></h2>
    <p>The website may contain links to other websites. This privacy notice applies only to this site, so if you click on a link to another website, you should read their privacy policy or notice.</p>

    <h2><a id="changes-to-the-privacy-notice">Changes to the privacy notice</a></h2>
    <p>If you have any questions about this privacy notice, the data held on you, or you would like to exercise one of your data protection rights, please do not hesitate to get in contact.</p>

    <h2><a id="how-to-contact">How to contact</a></h2>
    <p>You may send an email message to the site owner. Please write to <?=filter_var($email_mailbox, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?><img width="13" height="13" alt="&#64;" src="<?=Common::relativeUrlToAbsolute('/a/svg/at-sign-white.svg' . $_unique_asset)?>"/><?=filter_var($email_domain, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>, it will reach the appropriate person.</p>
<? if (Common::$config->discord->enabled) { ?>
    <p>Alternatively, you may try reaching <?=$org?> staff via <a href="<?=Common::relativeUrlToAbsolute('/discord')?>">Discord</a>.</p>
<? } ?>
</div>
<? require('./footer.inc.phtml'); ?>
