<?php namespace BNETDocs\Templates; $title = "Soft Redirect"; ?>
<?php require("./header.inc.phtml"); ?>
      <article>
        <header><?=$title?></header>
        <section>
          Location has moved, please follow this link:<br/>
          <br/>
          <a href="<?=$this->getContext()->location?>"><?=$this->getContext()->location?></a><br/>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
