<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates;
$title = 'Soft Redirect';
require('./header.inc.phtml'); ?>
<div class="container">
  <h1><?=$title?></h1>
  <div class="alert alert-warning">
    <p>Location has moved, please follow this link:</p>
    <p><a href="<?=$this->getContext()->location?>"><?=$this->getContext()->location?></a></p>
  </div>
</div>
<? require('./footer.inc.phtml'); ?>
