<?php /* vim: set colorcolumn=: */
namespace BNETDocs\Templates;
use \BNETDocs\Libraries\Server;
use \BNETDocs\Libraries\ServerType;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Servers';
$description = 'A list of servers that our automated system checks the status of. The status represents if the port is opened or closed, not if the service is functioning correctly.';
$this->opengraph->attach(new Pair('url', '/servers'));

$servers_by_type = [];
foreach ($this->context->servers as $server) {
  $servers_by_type[$server->getTypeId()][] = $server;
}
ksort($servers_by_type);

require('./header.inc.phtml');
?>
<div class="container mb-3">
  <h1>Server List</h1>
  <div class="row"><div class="col">
    <p>Below is a list of servers that our automated system checks the status of. The status represents if the port is opened or closed, not if the service is functioning correctly.</p>
    <p>We have a total of <strong><? echo number_format(count($this->context->servers)); ?> servers</strong> that we monitor. <a href="<? echo Common::relativeUrlToAbsolute("/servers.json"); ?>">Click here</a> to see this list in JSON format.</p>
  </div></div>
  <div class="row"><div class="col">
    <table class="table table-hover table-sm table-striped" id="servers_tbl">
      <thead><tr><th scope="col">Status</th><th scope="col">Label</th><th scope="col">Address</th><th scope="col"></th></tr></thead><tbody>
<?    foreach ($servers_by_type as $type_id => $servers)
      {
        $server_type = new ServerType($type_id);
        echo '<tr><th colspan="4">' . filter_var($server_type->getLabel(), FILTER_SANITIZE_FULL_SPECIAL_CHARS) . '</th></tr>';
        foreach ($servers as $server)
        {
          $status_bitmask = $server->getStatusBitmask();
          if ($status_bitmask & Server::STATUS_ONLINE) {
            $status_subclass = 'success'; $status = 'Online';
          } else if ($status_bitmask & Server::STATUS_DISABLED) {
            $status_subclass = 'danger'; $status = 'Disabled';
          } else {
            $status_subclass = 'danger'; $status = 'Offline';
          } ?>
        <tr>
          <td class="text-center"><span class="text-<?=$status_subclass?>"><?=$status?></span></td>
          <td><?=($server->getLabel() != $server->getAddress() && !empty($server->getLabel()) ? $server->getLabel() : '&nbsp;')?></td>
          <td><code><? echo $server->getAddress(); ?>:<? echo $server->getPort(); ?></code></td>
          <td><a class="btn btn-sm btn-primary" href="<? echo $server->getURI(); ?>" title="Details">ℹ</a></td>
        </tr>
<?      }
      } ?>
      </tbody>
    </table>
  </div></div>
</div>
<? ob_start(); ?>
  <script type="text/javascript">
    $(document).ready(function(){
      $('#servers_tbl').DataTable({
        "language": {"zeroRecords": "No matching servers found"},
        "responsive": true,
      });
    });
  </script>
<? $_footer_script = ob_get_clean(); require('./footer.inc.phtml'); ?>
