<?php

namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Server;
use \BNETDocs\Libraries\ServerType;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;

$title       = "Servers";
$description = "A list of servers that our automated system checks the status of. The status represents if the port is opened or closed, not if the service is functioning correctly.";
$this->opengraph->attach(new Pair("url", "/servers"));

$servers_by_type = [];
foreach ($this->context->servers as $server) {
  $servers_by_type[$server->getTypeId()][] = $server;
}
ksort($servers_by_type);

$this->additional_css[] = "/a/servers.css";
require("./header.inc.phtml");
?>
      <article>
        <header>Server List</header>
        <section>
          <p>Below is a list of servers that our automated system checks the status of. The status represents if the port is opened or closed, not if the service is functioning correctly.</p>
          <p>We have a total of <strong><?php echo number_format(count($this->context->servers)); ?> servers</strong> that we monitor. <a href="<?php echo Common::relativeUrlToAbsolute("/servers.json"); ?>">Click here</a> to see this list in JSON format.</p>
        </section>
        <section>
          <table class="servers">
            <thead>
              <tr>
                <th class="status">Status</th>
                <th class="label">Label</th>
                <th class="address">Address</th>
                <th class="details"></th>
              </tr>
            </thead>
            <tbody>
<?php foreach ($servers_by_type as $type_id => $servers) {
        $server_type = new ServerType($type_id);
?>
              <tr><th colspan="4"><?php echo $server_type->getLabel(); ?></th></tr>
<?php   foreach ($servers as $server) {
          $status_bitmask = $server->getStatusBitmask();
          if ($status_bitmask & Server::STATUS_ONLINE) {
            $status_subclass = "online"; $status = "Online";
          } else if ($status_bitmask & Server::STATUS_DISABLED) {
            $status_subclass = "disabled"; $status = "Disabled";
          } else {
            $status_subclass = "offline"; $status = "Offline";
          }
?>
              <tr>
                <td class="status center <?php echo $status_subclass; ?>"><?php echo $status; ?></td>
                <td class="label"><?php echo ($server->getLabel() != $server->getAddress() && !empty($server->getLabel()) ? $server->getLabel() : "&nbsp;"); ?></td>
                <td class="address" onclick="bnetdocs.fSelectText(this);"><?php echo $server->getAddress(); ?>:<?php echo $server->getPort(); ?></td>
                <td class="details center"><a href="<?php echo $server->getURI(); ?>">View Details</a></td>
              </tr>
<?php   } ?>
<?php } ?>
            </tbody>
          </table>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
