<?php
namespace BNETDocs\Templates;

use \CarlBennett\MVC\Libraries\Common;
use \BNETDocs\Libraries\Logger;
use \BNETDocs\Libraries\Pair;
use \BNETDocs\Libraries\User;

$title       = "Event Log Index";
$description = "The index for event logs on BNETDocs";
$this->opengraph->attach(new Pair("url", "/event-log/index"));

require("./header.inc.phtml");
?>
      <article>
<?php if ($this->getContext()->acl_allowed) { ?>
        <header>Event Log Index</header>
        <section>
<?php require("./NYI.inc.phtml"); ?>
        </section>
<?php } else { ?>
        <header class="red">Event Log Index</header>
        <section class="red">
          <p>You are not authorized to view this page.</p>
        </section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
