<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\EventLog;

use \BNETDocs\Libraries\Event;
use \BNETDocs\Libraries\Exceptions\UserNotFoundException;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;

$title = 'Event Logs';
$description = 'All triggered event logs on BNETDocs';
$this->opengraph->attach(new Pair('url', '/eventlog/index'));

$form_order_by = [
  'datetime-asc' => 'Timestamp (Ascending)',
  'datetime-desc' => 'Timestamp (Descending)',
  'id-asc' => 'Event Id (Ascending)',
  'id-desc' => 'Event Id (Descending)',
];

$page = $this->getContext()->page;
$pages = $this->getContext()->pages;
$limit = $this->getContext()->limit;
$order = $this->getContext()->order;

$no_prev = ($page <= 1);
$no_next = ($page >= $pages);

require('./header.inc.phtml'); ?>
<div class="container">
<? if (!$this->getContext()->acl_allowed) { ?>
  <div class="alert alert-danger">
    <h1><?=$title?></h1>
    <p class="mb-0">You are not authorized to view this page.</p>
  </div>
<? } else { ?>
  <h1><?=$title?></h1>
  <p><?=$description?></p>
  <form method="GET" class="m-2" id="filter_form">
    <input type="hidden" name="page" value="<? echo $page; ?>"/>
    <input type="hidden" name="limit" value="<? echo $limit; ?>"/>
    <label for="order" class="font-weight-bold m-1">Order by:</label>
    <select class="form-control form-control-sm" name="order" id="order" onchange="form.submit();" style="display:inline-block;width:200px;">
<?  foreach ($form_order_by as $item_value => $item_label) {
      $item_selected = ($order === $item_value ? ' selected="selected"' : '');
      echo sprintf('<option value="%s"%s>%s</option>' . PHP_EOL, $item_value, $item_selected, $item_label);
    } ?>
    </select>
    <input class="btn btn-sm btn-secondary" type="submit" value="Reorder"/>
  </form>
  <table class="table table-hover table-sm table-striped">
    <thead>
      <tr>
        <th class="text-right">Id</th>
        <th>Event Type</th>
        <th>Timestamp</th>
        <th>User Account</th>
      </tr>
    </thead><tbody>
<? foreach ($this->getContext()->events as $event) {
      $e_id = $event->getId();
      try { $e_user = $event->getUser(); }
      catch ( UserNotFoundException $e ) { $e_user = null; }
      if ( is_null( $e_user ) ) { $e_user = '<em>(null)</em>'; }
      else {
        $e_user_url    = $e_user->getURI();
        $e_user_avatar = $e_user->getAvatarURI(22);
        $e_user        = filter_var( $e_user->getName(), FILTER_SANITIZE_FULL_SPECIAL_CHARS );
        $e_user        = '<a href="' . $e_user_url . '"><img class="mr-2 rounded" src="' . $e_user_avatar . '"/>' . $e_user . '</a>';
      }
?>
      <tr>
        <td class="text-right"><a href="<?=Common::relativeUrlToAbsolute('/eventlog/view?id=' . $e_id)?>"><?=$e_id?></a></td>
        <td><?=$event->getEventTypeName()?></td>
        <td><time datetime="<?=$event->getEventDateTime()->format('c')?>"><?=$event->getEventDateTime()->format('l, F j, Y')?></time></td>
        <td><?=$e_user?></td>
      </tr>
<? } ?>
  </tbody></table>
  <nav aria-label="User list navigation" class="d-flex justify-content-center">
    <ul class="pagination">
  <?  if (!$no_prev) { ?>
      <li class="page-item"><a class="page-link" href="<?=Common::relativeUrlToAbsolute('/eventlog/index?page=' . ($page - 1) . '&limit=' . $limit . '&order=' . $order)?>">Previous</a></li>
  <?  } else { ?>
      <li class="page-item disabled"><span class="page-link">Previous</span></li>
  <?  } ?>
      <li class="page-item disabled"><span class="page-link"><?=number_format($page)?> of <?=number_format($pages)?></span></li>
  <?  if (!$no_next) { ?>
      <li class="page-item"><a class="page-link" href="<?=Common::relativeUrlToAbsolute('/eventlog/index?page=' . ($page + 1) . '&limit=' . $limit . '&order=' . $order)?>">Next</a></li>
  <?  } else { ?>
      <li class="page-item disabled"><span class="page-link">Next</span></li>
  <?  } ?>
    </ul>
  </nav>
</div>
<? } ?>
<? require("./footer.inc.phtml"); ?>
