<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\EventLog;

use \BNETDocs\Libraries\Event;
use \BNETDocs\Libraries\Exceptions\UserNotFoundException;
use \BNETDocs\Libraries\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;

$title = 'Event Log Viewer';
$description = 'The event log viewer on BNETDocs';
$this->opengraph->attach( new Pair( 'url', '/eventlog/view' ));

$object_id = $this->getContext()->id;
$object = $this->getContext()->event;
$user = $this->getContext()->user;

$object_ip_address = ($object instanceof Event ? $object->getIPAddress() : null);
$object_metadata = ($object instanceof Event ? $object->getMetadata() : null);
$object_user = ($object instanceof Event ? $object->getUser() : null);
$object_user_id = ($object instanceof Event ? $object->getUserId() : null);

if (!$object instanceof Event)
{
  $title = 'Event Not Found';
  $description = 'The event you tried to access could not be found.';
}

$tpl_user = sprintf('(<code>Id:%d</code>) ', $object_user_id) . (
  is_null($object_user) ? '<em>(null)</em>' : sprintf(
    '<a href="%s"><img class="mr-2" src="%s"/>%s</a>',
    $object_user->getURI(),
    $object_user->getAvatarURI(22),
    filter_var($object_user->getName(), FILTER_SANITIZE_FULL_SPECIAL_CHARS)
  )
);

$tpl_metadata_j = @json_decode($object_metadata);
$tpl_metadata = (
  is_null($object_metadata) ? '<em>(null)</em>' :
  (
    '<pre><code style="white-space:pre-wrap;" class="language-' . (
      json_last_error() === JSON_ERROR_NONE ? 'json' : 'plaintext'
    ) . '">' . str_replace("\n", "<br/>\n", filter_var(
      json_encode($tpl_metadata_j, JSON_PRETTY_PRINT), FILTER_SANITIZE_FULL_SPECIAL_CHARS)
    ) . '</code></pre>'
  )
);

$tpl_referer = getenv('HTTP_REFERER');
if (!empty($tpl_referer))
{
  $tpl_referer = '<a href="' . filter_var($tpl_referer, FILTER_SANITIZE_FULL_SPECIAL_CHARS) . '">&lt;&lt; Back to Previous</a>';
}
if (stripos($tpl_referer, getenv('HTTP_HOST')) === false)
{
  $tpl_referer = '';
}
if (stripos($tpl_referer, '/eventlog/view?id=' . $object_id) !== false)
{
  $tpl_referer = '';
}

require('./header.inc.phtml'); ?>
<div class="container">
<? if (!$this->getContext()->acl_allowed) { ?>
  <div class="alert alert-danger">
    <h1><?=$title?></h1>
    <p class="mb-0">You are not authorized to view this page.</p>
  </div>
<? } else if (is_null($object)) { ?>
  <div class="alert alert-danger">
    <h1><?=$title?></h1>
    <p><?=$description?></p>
<?=(!empty($tpl_referer) ? '    <p>' . $tpl_referer . '</p>' : '')?>
  </div>
<? } else { ?>
    <h1><?=$title?></h1>
    <table class="table table-hover table-striped">
      <thead></thead><tbody>
        <tr><th scope="row" class="text-right">Id</th><td><code><a href="<?=Common::relativeUrlToAbsolute('/eventlog/view?id=' . $object_id)?>"><?=$object_id?></a></code></td></tr>
        <tr><th scope="row" class="text-right">Event Type</th><td><?=$object->getEventTypeName()?></td></tr>
        <tr><th scope="row" class="text-right">Timestamp</th><td><time datetime='<?=$object->getEventDateTime()->format('c')?>'><?=$object->getEventDateTime()->format('l, F j, Y')?></time></td></tr>
        <tr><th scope="row" class="text-right">IP Address</th><td><?=($object_ip_address ? '<code>' . $object_ip_address . '</code>' : '<em>(null)</em>')?></td></tr>
        <tr><th scope="row" class="text-right">User Account</th><td><?=$tpl_user?></td></tr>
      </tbody>
    </table>
    <?=$tpl_metadata?>
<? if (!empty($tpl_referer)) { ?>
    <hr/><p><?=$tpl_referer?></p>
  <? } ?>
<? } ?>
</div>
<? require("./footer.inc.phtml"); ?>
