<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Server;
use \BNETDocs\Models\Server\Delete as DeleteModel;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Delete Server';
$description = 'This form allows an individual to delete a server.';
$this->opengraph->attach(new Pair('url', '/server/delete'));
$this->opengraph->attach(new Pair('type', 'article'));
$model = $this->getContext();
switch ($model->error)
{
  case DeleteModel::ERROR_ACCESS_DENIED: $message = 'You do not have the privilege to delete servers.'; break;
  case DeleteModel::ERROR_INTERNAL: $message = 'An internal error occurred while processing your request. Try again later.'; break;
  case DeleteModel::ERROR_INVALID_ID: $message = 'The id of the server is invalid.'; break;
  case DeleteModel::ERROR_SUCCESS: $message = 'The server has been deleted!'; break;
  default: $message = $model->error;
}
$id = $model->server ? $model->server->getId() : null;
$json = $model->server ? json_encode($model->server, \BNETDocs\Views\Server\ViewJson::jsonFlags()) : null;
require('./header.inc.phtml');
echo '<div class="container">';
if ($model->error === DeleteModel::ERROR_ACCESS_DENIED)
{
  require('./LoginRequired.inc.phtml');
}
else if ($model->error === DeleteModel::ERROR_SUCCESS)
{
  echo '<h1 class="text-success">Server Deleted</h1>';
  printf('<div class="alert alert-success"><p class="mb-0">%s</p></div>', $message);
  echo '<div class="form-group text-center">';
  printf('<a class="btn btn-success" tabindex="1" href="%s">Server List</a> ', \CarlBennett\MVC\Libraries\Common::relativeUrlToAbsolute('/servers'));
  echo '</div>';
}
else
{
  printf('<h1 class="text-danger">%s</h1>', $title);
  printf('<p class="text-danger">%s</p>', $description);
  if (!empty($message)) printf('<div class="alert alert-danger"><p class="mb-0">%s</p></div>', $message);
  if ($model->error !== DeleteModel::ERROR_INVALID_ID)
  {
    printf('<form method="POST" action="?id=%d">', $id);
    echo '<div class="alert alert-danger"><p class="mb-0">Are you sure you wish to delete this server?</p></div>';
    if (!empty($json)) printf('<pre><code class="language-objectivec">%s</code></pre>', filter_var($json, FILTER_SANITIZE_FULL_SPECIAL_CHARS));
    echo '<a class="btn btn-primary" tabindex="1" href="javascript:history.go(-1);">Back</a> ';
    printf('<a class="btn btn-success" tabindex="2" href="%s">Server List</a> ', \CarlBennett\MVC\Libraries\Common::relativeUrlToAbsolute('/servers'));
    echo '<input class="btn btn-danger" type="submit" value="Delete Server" tabindex="3" autofocus/>';
    echo '</form>';
  }
}
echo '</div>';
require('./footer.inc.phtml');
