<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Server;
use \BNETDocs\Libraries\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Server Not Found';
$description = 'The requested server does not exist or could not be found.';
$server = $this->getContext()->server;
if (!$server)
{
  $server_id = null;
  $server_type = null;
  $server_user = null;
  $url = null;
}
else
{
  $server_address = filter_var(sprintf('%s:%s', $server->getAddress(), $server->getPort()), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
  $server_id = $server->getId();
  $server_name = filter_var($server->getName(), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
  $server_label = !empty($server->getLabel()) ? filter_var($server->getLabel(), FILTER_SANITIZE_FULL_SPECIAL_CHARS) : '<em>(empty)</em>';
  $server_type = $server->getType();

  $title = $server_name;
  $description = sprintf('The server details and status for %s', $server_name);
  $url = $server->getURI();
  $url_json = sprintf('%s.json', $url);
  $url_txt = sprintf('%s.txt', $url);

  $server_type = $server->getType();
  $server_type_label = filter_var($server_type->getLabel(), FILTER_SANITIZE_FULL_SPECIAL_CHARS);

  $server_user = $server->getUser();
  if (!$server_user)
  {
    $server_user_string = 'Anonymous';
  }
  else
  {
    $server_user_avatar = $server_user->getAvatarURI(22);
    $server_user_name = filter_var($server_user->getName(), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
    $server_user_url = $server_user->getURI();
    $server_user_string = sprintf('<a href="%s"><img class="mr-2 rounded" src="%s"/>%s</a>', $server_user_url, $server_user_avatar, $server_user_name);
  }

  $server_online = $server->isOnline();
  $server_status = sprintf('<span class="text-%s">%s</span>', ($server_online ? 'success' : 'danger'), ($server_online ? 'Online' : 'Offline'));
  if ($server->isDisabled())
  {
    $server_status = '<span class="text-warning">Disabled</span>';
  }
  else
  {
    $server_status = sprintf('<span class="text-%s">%s</span>',
      ($server_online ? 'success' : 'danger'), ($server_online ? 'Online' : 'Offline')
    );
  }
}
$this->opengraph->attach(new Pair('type', 'article'));
if (!empty($url)) $this->opengraph->attach(new Pair('url', $url));
require('./header.inc.phtml'); ?>
<div class="container">
<? if (!$server) { ?>
  <h1 class="text-danger"><?=filter_var($title, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></h1>
  <div class="alert alert-danger"><?=filter_var($description, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></div></div>
<? } else { ?>
  <span class="float-right">
<?=($this->getContext()->active_user && $this->getContext()->active_user->getOption(User::OPTION_ACL_SERVER_MODIFY) ? sprintf('<a class="btn btn-sm btn-secondary" href="%s" title="Edit">📝</a>', Common::relativeUrlToAbsolute(sprintf('/server/edit?id=%d', $server_id))) : '')?>
    <a class="btn btn-sm btn-primary" href="<?=$url_json?>">JSON</a>
    <a class="btn btn-sm btn-primary" href="<?=$url_txt?>">TXT</a>
  </span>
  <h1><?=$title?></h1>
  <table class="table table-hover table-sm table-striped"><thead></thead><tbody>
    <tr><th class="text-right">Label</th><td><?=$server_label?></td></tr>
    <tr><th class="text-right">Address</th><td onclick="bnetdocs.fSelectText(this);"><code><?=$server_address?></code></td></tr>
    <tr><th class="text-right">Owner</th><td><?=$server_user_string?></td></tr>
    <tr><th class="text-right">Type</th><td><?=$server_type_label?></td></tr>
    <tr><th class="text-right">Current Status</th><td class="font-weight-bold"><?=$server_status?></td></tr>
  </tbody></table>
<? } ?>
</div>
<? require('./footer.inc.phtml'); ?>
