<?php
namespace BNETDocs\Templates\Email\User;
use \CarlBennett\MVC\Libraries\Common;
require('./Email/header.plain.inc.phtml');
?>
Hello <?=$this->getContext()->user->getName()?>,

Someone requested your password to be reset on BNETDocs. If this was you, copy
and paste the following into your web browser:

<?=Common::relativeUrlToAbsolute('/user/resetpassword?username=' . rawurlencode($this->getContext()->user->getUsername()) . '&t=' . rawurlencode($this->getContext()->token))?>

If this was not you, then you can safely ignore this email; no action will be
taken.
<?php require('./Email/footer.plain.inc.phtml'); ?>
