<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Email\User;
use \CarlBennett\MVC\Libraries\Common;
$name = $this->getContext()->username;
$url = Common::relativeUrlToAbsolute(sprintf('/user/resetpassword?email=%s&t=%s', rawurlencode($this->getContext()->email), rawurlencode($this->getContext()->token)));
require('./Email/header.plain.inc.phtml'); ?>
Hello <?=$name?>,

Someone requested your password to be reset on BNETDocs. If this was you, click
or copy and paste the link below into your web browser to reset your password.

<?=$url?>

**Note:** This link will only be available for a short duration.

If this was not you, then you can safely ignore this email; no action will be
taken.

You may also reply to this email if you believe there is an issue.
<?php require('./Email/footer.plain.inc.phtml'); ?>
