<?php
namespace BNETDocs\Templates\Email\User;
use \CarlBennett\MVC\Libraries\Common;
require('./Email/header.plain.inc.phtml');
?>
Hello <?=$this->getContext()->user->getName()?>,

Someone requested your password to be reset on BNETDocs. If this was you, click
or copy and paste the link below into your web browser to reset your password.

<?=Common::relativeUrlToAbsolute('/user/resetpassword?email=' . rawurlencode($this->getContext()->user->getEmail()) . '&t=' . rawurlencode($this->getContext()->token))?>


**Note:** This link will only be available for 24 hours.

If this was not you, then you can safely ignore this email; no action will be
taken.

You may also reply to this email if you believe there is an issue.
<?php require('./Email/footer.plain.inc.phtml'); ?>
