<?php /* vim: set colorcolumn=: */
namespace BNETDocs\Templates\Comment;
use \BNETDocs\Libraries\Comment;
use \BNETDocs\Libraries\User;
use \CarlBennett\MVC\Libraries\Common;
$c_edit_visible_admin = ($logged_in && ($logged_in->getOptionsBitmask() & User::OPTION_ACL_COMMENT_MODIFY));
$c_delete_visible_admin = ($logged_in && ($logged_in->getOptionsBitmask() & User::OPTION_ACL_COMMENT_DELETE));
?>
<div class="row mt-3">
  <div class="col">
    <h2><a name="comments">Comments</a></h2>
<? if (!$comments) { ?>
    <div class="border border-secondary rounded-pill p-2"><p class="text-center mb-0"><em>no one has commented yet.</em></p></div>
<? } else { ?>
    <table class="table table-striped"><tbody>
<?    foreach ($comments as $c) {
        $c_created_dt  = $c->getCreatedDateTime();
        $c_id          = rawurlencode($c->getId());
        $c_parent_url  = $c->getParentUrl();
        $c_user        = $c->getUser();
        $c_user_id     = $c->getUserId();
        $c_user_url    = ($c_user ? $c_user->getURI() : '');
        $c_user_avatar = ($c_user ? $c_user->getAvatarURI(22) : '');
        $c_user_name   = ($c_user ? filter_var($c_user->getName(), FILTER_SANITIZE_FULL_SPECIAL_CHARS) : 'Anonymous');

        $c_user_string = ($c_user ? sprintf('<a href="%s"><img src="%s"/> %s</a>', $c_user_url, $c_user_avatar, $c_user_name) : $c_user_name);

        $c_edit_visible = ($c_user_id == $logged_in_id || $c_edit_visible_admin);
        $c_delete_visible = ($c_user_id == $logged_in_id || $c_delete_visible_admin); ?>
      <tr><td>
        <?=$c_user_string?><br/>
        <time datetime="<?=$c_created_dt->format('c')?>"><?=$c_created_dt->format('D M j, Y g:ia T')?></time>
      </td><td>
<?    if ($c_delete_visible) { ?>
        <a class="btn btn-sm btn-danger float-right m-1" href="<?=Common::relativeUrlToAbsolute('/comment/delete?id=' . $c_id)?>" title="Delete">❌</a>
<?    } if ($c_edit_visible) { ?>
        <a class="btn btn-sm btn-secondary float-right m-1" href="<?=Common::relativeUrlToAbsolute('/comment/edit?id=' . $c_id)?>" title="Edit">📝</a>
<?    } ?>
        <?=$c->getContent(true)?>
      </td></tr>
<? } ?>
    </tbody></table>
<? } ?>
  </div>
</div>
<? if ($logged_in) { ?>
<div class="row mt-3">
  <div class="col-2"></div>
  <div class="col-8">
    <form method="POST" action="<?=Common::relativeUrlToAbsolute('/comment/create')?>">
      <input type="hidden" name="parent_type" value="<?=$comment_parent_type?>"/>
      <input type="hidden" name="parent_id" value="<?=$object_id?>"/>
      <div class="form-group">
        <label for="comment-content" class="font-weight-bold">Make a Comment:</label>
        <textarea id="comment-content" class="border border-secondary form-control bg-dark text-light" name="content"></textarea>
      </div>
      <input class="btn btn-sm btn-secondary" type="submit" value="Comment"/>
    </form>
  </div>
  <div class="col-2"></div>
</div>
<? } ?>
