<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Common;
use \BNETDocs\Libraries\Gravatar;
use \BNETDocs\Libraries\Pair;

$title       = "Create News Post";
$description = "This form allows an individual to create a news post.";

$this->opengraph->attach(new Pair("url", "/news/create"));
$this->opengraph->attach(new Pair("type", "article"));

switch ($this->getContext()->error) {
  case "ACL_NOT_SET":
    $message = "You do not have the privilege to create news posts.";
    break;
  case "INVALID_CSRF":
    $message = "The Cross-Site Request Forgery token was invalid. "
      . "Either the create news post form expired, or "
      . "this may have been a malicious attempt to create a news post.";
    break;
  case "EMPTY_TITLE":
    $message = "The title of the news post is required.";
    break;
  case "EMPTY_CONTENT":
    $message = "The content of the news post is required.";
    break;
  case "INTERNAL_ERROR":
    $message = "An internal error occurred while processing your request. "
      . "Our staff has been notified of the issue. Try again later.";
    break;
  default:
    $message = $this->getContext()->error;
}

$this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
<?php if ($this->getContext()->error !== false) { ?>
        <header>Create News Post</header>
        <section><?php require("./NYI.inc.phtml"); ?></section>
<?php if (!empty($message)) { ?>
        <section class="red"><p><?php echo $message; ?></p></section>
<?php } ?>
        <form method="POST" action="?">
          <input type="hidden" name="csrf_id" value="<?php echo
            htmlspecialchars($this->getContext()->csrf_id, ENT_HTML5, "UTF-8");
          ?>"/>
          <input type="hidden" name="csrf_token" value="<?php echo
            htmlspecialchars($this->getContext()->csrf_token, ENT_HTML5, "UTF-8");
          ?>"/>
          <section>
            <label for="title">Title:</label><br/>
            <input type="text" name="title" id="title" tabindex="1" required
              autofocus="autofocus"
              value="<?php echo
                htmlspecialchars($this->getContext()->title, ENT_HTML5, "UTF-8");
              ?>"/>
          </section>
          <section>
            <label for="content">Content:</label>
            <span style="float:right;">
              <label for="markdown" title="Use markdown or use raw HTML">Markdown</label>
              <input type="checkbox" name="markdown" id="markdown" tabindex="3"
                title="Use markdown or use raw HTML" value="1"<?php
                  if ($this->getContext()->markdown)
                    echo " checked=\"checked\"";
                ?>/>
            </span>
            <textarea name="content" id="content" tabindex="2" required
              style="height:200px;"><?php echo
                htmlspecialchars($this->getContext()->content, ENT_HTML5, "UTF-8");
              ?></textarea>
          </section>
          <section>
            <input type="submit" name="publish" value="Publish"/>
            <input type="submit" name="save" value="Save as Draft"/>
          </section>
        </form>
<?php } else { ?>
        <header class="green">Create News Post</header>
        <section class="green">
          <p>Your news post has been created.</p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
