<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Common;
use \BNETDocs\Libraries\Gravatar;
use \BNETDocs\Libraries\NewsPost;
use \BNETDocs\Libraries\Pair;
use \BNETDocs\Libraries\User;

$object       = $this->getContext()->news_post;
$object_id    = $this->getContext()->news_post_id;
$user_session = $this->getContext()->user_session;
$logged_in    = ($user_session ? new User($user_session->user_id) : null);

$title       = ($object ? $object->getTitle() : "News Post Not Found");
$description = Common::stripUpTo(trim(filter_var(
  ($object ? $object->getContent(true) : "The requested news post does not exist or could not be found."),
  FILTER_SANITIZE_STRING
)), "\n", 300);

$this->opengraph->attach(new Pair("url", "/news/" . urlencode($object_id)));
$this->opengraph->attach(new Pair("type", "article"));
if ($object) {
  $this->opengraph->attach(new Pair("image", "/a/news_categories/" . $object->getCategory()->getFilename()));
  $this->opengraph->attach(new Pair("article:published_time", $object->getCreatedDateTime()->format("c")));
  if (!is_null($object->getEditedDateTime())) {
    $this->opengraph->attach(new Pair("article:modified_time", $object->getEditedDateTime()->format("c")));
  }
  $this->opengraph->attach(new Pair("article:author:username", $object->getUser()->getName()));
  $this->opengraph->attach(new Pair("article:section", $object->getCategory()->getLabel()));
}

$url            = Common::relativeUrlToAbsolute("/news/" . urlencode($object_id));
$edit_url       = Common::relativeUrlToAbsolute("/news/edit?id=" . urlencode($object_id));
$delete_url     = Common::relativeUrlToAbsolute("/news/delete?id=" . urlencode($object_id));
$edit_visible   = ($logged_in && ($logged_in->getOptionsBitmask()
                & User::OPTION_ACL_NEWS_MODIFY));
$delete_visible = ($logged_in && ($logged_in->getOptionsBitmask()
                & User::OPTION_ACL_NEWS_DELETE));

if ($object) {
  $url        .= "/" . Common::sanitizeForUrl($object->getTitle(), true);
  $user_name   = $object->getUser()->getName();
  $user_id     = $object->getUserId();
  $user_url    = Common::relativeUrlToAbsolute("/user/" . $user_id . "/" . Common::sanitizeForUrl($user_name, true));
  $user_avatar = "https:" . (new Gravatar($object->getUser()->getEmail()))->getUrl(22, "identicon");
}

$this->additional_css[] = "/a/news.css";
require("./header.inc.phtml");
?>
      <article>
<?php if ($object) { ?>
        <a href="https://plus.google.com/share?url=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-gplus-24px.png"); ?>"/></a>
        <a href="https://twitter.com/share?text=<?php echo urlencode($object->getTitle()); ?>&amp;url=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-twitter-24px.png"); ?>"/></a>
        <a href="https://facebook.com/sharer/sharer.php?u=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-facebook-24px.png"); ?>"/></a>
<?php if ($edit_visible) { ?>
        <a href="<?php echo $edit_url; ?>" class="header-button float-right">Edit</a>
<?php } ?>
<?php if ($delete_visible) { ?>
        <a href="<?php echo $delete_url; ?>" class="header-button float-right">Delete</a>
<?php } ?>
        <header><a href="<?php echo $url; ?>"><?php echo $object->getTitle(); ?></a></header>
<?php if (!($object->getOptionsBitmask() & NewsPost::OPTION_PUBLISHED)) { ?>
        <section class="red"><p><strong>Warning:</strong> This news post is not yet published. You can view this because you are allowed to create, modify, or delete news posts.</p></section>
<?php } ?>
        <section class="news"><img class="category" alt="<?php echo $object->getCategory()->getLabel(); ?>" title="<?php echo $object->getCategory()->getLabel(); ?>" src="<?php echo Common::relativeUrlToAbsolute("/a/news_categories/" . $object->getCategory()->getFilename()); ?>"/><?php echo $object->getContent(true); ?></section>
        <footer>
          <span class="float-left"><a href="<?php echo $user_url; ?>"><img class="avatar" src="<?php echo $user_avatar; ?>"/> <?php echo htmlspecialchars($user_name, ENT_HTML5, "UTF-8"); ?></a></span>
          <span class="float-right"><?php echo $object->getPublishedDateTime()->format("l, F j, Y"); ?></span>
        </footer>
      </article>
      <article>
        <header>Comments</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
          <p class="center">If you'd like to leave a suggestion or concern, you can do so <a href="https://github.com/BNETDocs/bnetdocs-web/issues/new?labels[]=bnetdocs-phoenix&labels[]=question&body=<?php echo rawurlencode("Hi,\n\n<fill in your question here>\n\nThanks!\n\nReference: " . $url); ?>" rel="external">over on GitHub</a>. Sorry for the trouble!</p>
        </section>
<?php } else { ?>
        <header class="red"><?php echo htmlspecialchars($title, ENT_HTML5, "UTF-8"); ?></header>
        <section class="red"><?php echo htmlspecialchars($description, ENT_HTML5, "UTF-8"); ?></section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
