<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Common;
use \BNETDocs\Libraries\Pair;

$title       = $this->context->news_post->getTitle();
$description = Common::stripUpTo(filter_var($this->context->news_post->getContent(true), FILTER_SANITIZE_STRING), "\n", 300);

$this->opengraph->attach(new Pair("url", "https://dev.bnetdocs.org/news/" . $this->context->news_post_id));
$this->opengraph->attach(new Pair("type", "article"));
$this->opengraph->attach(new Pair("article:published_time", $this->context->news_post->getPostDate()->format("c")));
if (!is_null($this->context->news_post->getEditDate())) {
  $this->opengraph->attach(new Pair("article:modified_time", $this->context->news_post->getEditDate()->format("c")));
}
$this->opengraph->attach(new Pair("article:author:username", $this->context->news_post->getUser()->getName()));

$url = "https://dev.bnetdocs.org/news/" . urlencode($this->context->news_post->getId());
$url .= "/" . Common::sanitizeForUrl($this->context->news_post->getTitle(), true);

require("./header.inc.phtml");
?>
      <article>
        <a href="https://plus.google.com/share?url=<?php echo urlencode($url); ?>" rel="external"><img class="social-btn float-right" src="https://dev.bnetdocs.org/a/social-gplus-24px.png"/></a>
        <a href="https://twitter.com/share?text=<?php echo urlencode($this->context->news_post->getTitle()); ?>&amp;url=<?php echo urlencode($url); ?>" rel="external"><img class="social-btn float-right" src="https://dev.bnetdocs.org/a/social-twitter-24px.png"/></a>
        <a href="https://facebook.com/sharer/sharer.php?u=<?php echo urlencode($url); ?>" rel="external"><img class="social-btn float-right" src="https://dev.bnetdocs.org/a/social-facebook-24px.png"/></a>
        <header><a href="<?php echo $url; ?>"><?php echo $this->context->news_post->getTitle(); ?></a></header>
        <section><?php echo $this->context->news_post->getContent(true); ?></section>
        <footer>
          <span class="float-left"><?php echo $this->context->news_post->getUser()->getName(); ?></span>
          <span class="float-right"><?php echo $this->context->news_post->getPublishDate()->format("l, F j, Y"); ?></span>
        </footer>
      </article>
<?php require("./footer.inc.phtml"); ?>
