
--
BNETDocs Staff

BNETDocs is a documentation and discussion website for Blizzard Entertainment's
Battle.net™ and in-game protocols. You hereby acknowledge that BNETDocs content
is offered as is and without warranty. BNETDocs content may be inaccurate as it
is solely from third-party observations. BNETDocs is not affiliated or partnered
with Blizzard Entertainment in absolutely any way. Battle.net™, Starcraft™,
Warcraft™, and Diablo™ are trademarks or registered trademarks of Blizzard
Entertainment, Inc., in the U.S. and/or other countries. See our Legal page
<https://bnetdocs.org/legal> for more info.
