<?php

namespace BNETDocs\Views\Packet;

use \BNETDocs\Libraries\Common;
use \BNETDocs\Libraries\Exceptions\IncorrectModelException;
use \BNETDocs\Libraries\Model;
use \BNETDocs\Libraries\View;
use \BNETDocs\Models\Packet\Index as PacketIndexModel;

class IndexVB extends View {

  public function getMimeType() {
    return "text/x-vb;charset=utf-8";
  }

  public function render(Model &$model) {
    if (!$model instanceof PacketIndexModel) {
      throw new IncorrectModelException();
    }
    echo "' BNETDocs: Phoenix\n";
    echo "' Copyright (C) 2003-2016 BNETDocs CC-BY-NC-SA 4.0\n";
    echo "' <" . Common::relativeUrlToAbsolute("/legal") . ">\n";
    echo "'\n";
    echo "' Packet ID constants for Visual Basic 6\n";
    echo "' Generated by BNETDocs on "
      . $model->timestamp->format("r") . "\n";
    echo "\n";
    foreach ($model->packets as $pkt) {
      echo "CONST " . $pkt->getPacketName() . "& = &H"
        . substr("0" . strtoupper(dechex($pkt->getPacketId())), -2) . "\n";
    }
  }

}
