<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Pair;

$title       = "Contributors";
$description = "Contributors to the BNETDocs documentation";
$this->opengraph->attach(new Pair("url", "https://dev.bnetdocs.org/credits"));

require("./header.inc.phtml");
?>
      <article>
        <header>Contributors</header>
        <section>
          <p>We have a total of <?php echo number_format($this->context->total_users); ?> users, of which the following are our top contributors grouped by content.</p>
        </section>
        <header>Documents</header>
        <section>
          <ol type="1">
<?php foreach ($this->context->top_contributors_by_documents as $item) {
        if (is_null($item->user_id)) {
          $pfx = ""; $sfx = "";
        } else {
          $pfx = "<a href=\"https://dev.bnetdocs.org/user/" . urlencode($item->user_id) . "\">";
          $sfx = "</a>";
        }
?>
            <li><?php echo $pfx.$item->name.$sfx; ?> with <?php echo number_format($item->documents_authored); ?> document(s)</li>
<?php } ?>
          </ol>
        </section>
        <header>News Posts</header>
        <section>
          <ol type="1">
<?php foreach ($this->context->top_contributors_by_news_posts as $item) {
        if (is_null($item->user_id)) {
          $pfx = ""; $sfx = "";
        } else {
          $pfx = "<a href=\"https://dev.bnetdocs.org/user/" . urlencode($item->user_id) . "\">";
          $sfx = "</a>";
        }
?>
            <li><?php echo $pfx.$item->name.$sfx; ?> with <?php echo number_format($item->news_posts_created); ?> news post(s)</li>
<?php } ?>
          </ol>
        </section>
        <header>Packets</header>
        <section>
          <ol type="1">
<?php foreach ($this->context->top_contributors_by_packets as $item) {
        if (is_null($item->user_id)) {
          $pfx = ""; $sfx = "";
        } else {
          $pfx = "<a href=\"https://dev.bnetdocs.org/user/" . urlencode($item->user_id) . "\">";
          $sfx = "</a>";
        }
?>
            <li><?php echo $pfx.$item->name.$sfx; ?> with <?php echo number_format($item->packets_authored); ?> packet(s)</li>
<?php } ?>
          </ol>
        </section>
        <header>Servers</header>
        <section>
          <ol type="1">
<?php foreach ($this->context->top_contributors_by_servers as $item) {
        if (is_null($item->user_id)) {
          $pfx = ""; $sfx = "";
        } else {
          $pfx = "<a href=\"https://dev.bnetdocs.org/user/" . urlencode($item->user_id) . "\">";
          $sfx = "</a>";
        }
?>
            <li><?php echo $pfx.$item->name.$sfx; ?> with <?php echo number_format($item->servers_owned); ?> server(s)</li>
<?php } ?>
          </ol>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
