    </main>
    <footer>
      Copyright &copy; 2003-2015 BNETDocs <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.txt" rel="external">CC-BY-NC-SA 4.0</a><br/>
      BNETDocs is in no way affiliated with or endorsed by Blizzard Entertainment&trade; or its brands, and is not intended to compete with or undermine Blizzard Entertainment&trade; or Battle.net&trade;. Persons using this software understand that the information provided within is collected knowledge from years of observations and may be inaccurate.<br/>
      All aforementioned trademarks are the property of their respectful owners.<br/>
    </footer>
  </body>
</html>
