<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title><?php echo $title; ?> - BNETDocs</title>
    <link rel="stylesheet" href="https://dev.bnetdocs.org/main.css" type="text/css" media="all"/>
<?php foreach ($this->additional_css as $path) { ?>
    <link rel="stylesheet" type="text/css" href="https://dev.bnetdocs.org<?php echo $path; ?>" media="all"/>
<?php } ?>
    <link rel="icon" href="https://dev.bnetdocs.org/favicon.png" type="image/png" sizes="48x48"/>
    <link rel="stylesheet" type="text/css" href="https://static.carlbennett.me/font/SourceSansPro-Regular-201508251844.css"/>
    <link rel="stylesheet" type="text/css" href="https://static.carlbennett.me/font/SourceCodePro-Regular-201508251844.css"/>
  </head>
  <body>
    <header>BNETDocs: Phoenix</header>
<?php if (!(isset($slim_ui) && $slim_ui)) { ?>
    <nav>
      <a>Portal</a>
      <a href="https://dev.bnetdocs.org/news">News</a>
      <a href="https://dev.bnetdocs.org/credits">Contributors</a>
      <a href="https://dev.bnetdocs.org/legal">Terms of Service</a>
      <a>Account Management</a>
      <a href="https://dev.bnetdocs.org/user/login">Account Login</a>
      <a href="https://dev.bnetdocs.org/user/register">Create Account</a>
      <a>Documentation</a>
      <a href="https://dev.bnetdocs.org/document/search">Search Documents</a>
      <a href="https://dev.bnetdocs.org/packet/search">Search Packets</a>
      <a href="https://dev.bnetdocs.org/document/popular">Popular Documents</a>
      <a href="https://dev.bnetdocs.org/packet/popular">Popular Packets</a>
    </nav>
    <main>
<?php } else { ?>
    <main class="slim">
<?php } ?>
