<!DOCTYPE html>
<html>
  <head>
    <title><?php echo $title; ?> - BNETDocs</title>
    <link rel="stylesheet" href="https://dev.bnetdocs.org/main.css" type="text/css" media="all" />
    <link rel="icon" href="https://dev.bnetdocs.org/favicon.png" type="image/png" sizes="48x48" />
  </head>
  <body>
    <header>BNETDocs: Phoenix</header>
    <main>
      <nav>
        <a>Portal</a>
        <a href="https://dev.bnetdocs.org/">Home</a>
        <a href="https://dev.bnetdocs.org/news">News</a>
        <a>Documentation</a>
        <a href="https://dev.bnetdocs.org/search">Search</a>
        <a>Administration</a>
        <a href="https://dev.bnetdocs.org/document/create">Create Document</a>
        <a href="https://dev.bnetdocs.org/packet/create">Create Packet</a>
      </nav>
