<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Pair;

$title = "Terms of Service";
$this->opengraph->attach(new Pair("description", "BNETDocs Terms of Service & Privacy Policy"));

require("./header.inc.phtml");
?>
      <article>
        <header>Terms of Service</header>
        <section class="fixed-width-text"><?php
          echo htmlspecialchars(file_get_contents("../LICENSE"));
        ?></section>
      </article>
<?php require("./footer.inc.phtml"); ?>
