<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Common;
use \BNETDocs\Libraries\Gravatar;
use \BNETDocs\Libraries\Pair;
use \BNETDocs\Libraries\User;

$title       = "News";
$description = "BNETDocs News";
$this->opengraph->attach(new Pair("url", "https://dev.bnetdocs.org/news"));

$this->additional_css[] = "/a/news.css";
require("./header.inc.phtml");

$avatars = [];
$getAvatar = function(&$avatars, $user_id) {
  if (isset($avatars[$user_id])) {
    return $avatars[$user_id];
  }
  $avatars[$user_id] = new Gravatar((new User($user_id))->getEmail());
  return $avatars[$user_id];
};

$users = [];
foreach ($this->context->news_posts as $news_post) {
  $url = "https://dev.bnetdocs.org/news/" . urlencode($news_post->getId());
  $url .= "/" . Common::sanitizeForUrl($news_post->getTitle(), true);
  $user_id = $news_post->getUserId();
  $avatar = "https:" . $getAvatar($avatars, $user_id)->getUrl(22, "identicon");
  if (!isset($users[$user_id])) $users[$user_id] = new User($user_id);
?>
      <article>
        <a href="https://plus.google.com/share?url=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="social-btn float-right" src="https://dev.bnetdocs.org/a/social-gplus-24px.png"/></a>
        <a href="https://twitter.com/share?text=<?php echo urlencode($news_post->getTitle()); ?>&amp;url=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="social-btn float-right" src="https://dev.bnetdocs.org/a/social-twitter-24px.png"/></a>
        <a href="https://facebook.com/sharer/sharer.php?u=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="social-btn float-right" src="https://dev.bnetdocs.org/a/social-facebook-24px.png"/></a>
        <header><a href="<?php echo $url; ?>"><?php echo $news_post->getTitle(); ?></a></header>
        <section class="news"><img class="category" alt="<?php echo $news_post->getCategory()->getLabel(); ?>" title="<?php echo $news_post->getCategory()->getLabel(); ?>" src="https://dev.bnetdocs.org/a/news_categories/<?php echo $news_post->getCategory()->getFilename(); ?>"/><?php echo $news_post->getContent(true); ?></section>
        <footer>
          <span class="float-left"><a href="https://dev.bnetdocs.org/user/<?php echo urlencode($user_id); ?>/<?php echo Common::sanitizeForUrl($users[$user_id]->getName(), true); ?>"><img class="avatar" src="<?php echo $avatar; ?>"/> <?php echo htmlspecialchars($users[$user_id]->getName(), ENT_HTML5, "UTF-8"); ?></a></span>
          <span class="float-right"><?php echo $news_post->getPublishedDateTime()->format("l, F j, Y"); ?></span>
        </footer>
      </article>
<?php }
require("./footer.inc.phtml"); ?>
