<?php

namespace BNETDocs\Templates;

$title       = "Page Not Found";
$description = "The requested resource does not exist or could not be found.";

require("./header.inc.phtml");
?>
      <article>
        <header class="red">Page Not Found</header>
        <section class="red">
          <p><?php echo htmlspecialchars($description, ENT_HTML5, "UTF-8"); ?></p>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
