<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Pair;

$title       = "Popular Documents";
$description = "The popular documents on BNETDocs";
$this->opengraph->attach(new Pair("url", "https://dev.bnetdocs.org/document/popular"));

require("./header.inc.phtml");
?>
      <article>
        <header>Popular Documents</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
