<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Common;
use \BNETDocs\Libraries\Document;
use \BNETDocs\Libraries\Pair;

$title       = "Search Documents";
$description = "Search the documents on BNETDocs";
$this->opengraph->attach(new Pair("url", "/document/search"));

require("./header.inc.phtml");
?>
      <article>
        <header>Search Documents</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
      <article>
        <header>Suggestion</header>
        <section>
          <p><a href="<?php echo Common::relativeUrlToAbsolute("/document/index"); ?>">Click here</a> to see all of the documents.</p>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
