<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Pair;

$title       = "Search Documents";
$description = "Search the documents on BNETDocs";
$this->opengraph->attach(new Pair("url", "/document/search"));

require("./header.inc.phtml");
?>
      <article>
        <header>Search Documents</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
