<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Common;
use \BNETDocs\Libraries\Pair;

$object_id = $this->getContext()->document_id;
$object    = $this->getContext()->document;

$title       = "Document Not Found";
$description = "The requested document does not exist or could not be found.";

$this->opengraph->attach(new Pair("type", "article"));

$url = Common::relativeUrlToAbsolute("/document/" . urlencode($object_id));
if ($object) {
  $url .= "/" . Common::sanitizeForUrl($object->getTitle(), true);
  $this->opengraph->attach(new Pair("url", "/document/" . urlencode($object_id)
    . "/" . Common::sanitizeForUrl($object->getTitle(), true)));
  $title = htmlspecialchars($object->getTitle(), ENT_HTML5, "UTF-8");
  $description = Common::stripUpTo(trim(filter_var(
    $object->getContent(true), FILTER_SANITIZE_STRING
  )), "\n", 300);
} else {
  $this->opengraph->attach(new Pair("url", "/document/" . urlencode($object_id)));
}

#$this->additional_css[] = "/a/document.css";
require("./header.inc.phtml");
?>
      <article>
<?php if ($object) { ?>
        <a href="https://plus.google.com/share?url=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="social-btn float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-gplus-24px.png"); ?>"/></a>
        <a href="https://twitter.com/share?text=<?php echo urlencode($object->getTitle()); ?>&amp;url=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="social-btn float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-twitter-24px.png"); ?>"/></a>
        <a href="https://facebook.com/sharer/sharer.php?u=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="social-btn float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-facebook-24px.png"); ?>"/></a>
        <header><a href="<?php echo $url; ?>"><?php echo $title; ?></a></header>
        <section>
<?php echo $object->getContent(true); ?>
        </section>
      </article>
      <article>
        <header>Comments</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
          <p class="center">If you'd like to leave a suggestion or concern, you can do so <a href="https://github.com/BNETDocs/bnetdocs-web/issues/new?labels[]=bnetdocs-phoenix&labels[]=question&body=<?php echo rawurlencode("Hi,\n\n<fill in your question here>\n\nThanks!\n\nReference: " . $url); ?>" rel="external">over on GitHub</a>. Sorry for the trouble!</p>
        </section>
<?php } else { ?>
        <header class="red"><?php echo htmlspecialchars($title, ENT_HTML5, "UTF-8"); ?></header>
        <section class="red"><?php echo htmlspecialchars($description, ENT_HTML5, "UTF-8"); ?></section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
