<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Packet;
use \BNETDocs\Libraries\Packet;
use \BNETDocs\Models\Packet\Form as FormModel;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Create Packet';
$description = 'Create a new Packet on the site.';
$this->opengraph->attach(new Pair('url', '/packet/edit'));
$this->opengraph->attach(new Pair('type', 'article'));
$active_user = $this->getContext()->active_user;
$comments = null;
$error = $this->getContext()->error;
switch ($error)
{
  case FormModel::ERROR_ACL_DENIED: $message = 'You do not have the privilege to create packets.'; break;
  case FormModel::ERROR_INTERNAL: $message = 'An internal error occurred. Try again later.'; break;
  case FormModel::ERROR_NONE: $message = null; break;
  case FormModel::ERROR_NOT_FOUND: $message = 'The requested packet does not exist or could not be found.'; break;
  case FormModel::ERROR_OUTOFBOUNDS_APPLICATION_LAYER_ID: $message = sprintf('The application layer must be between 0-%d.', Packet::MAX_APPLICATION_LAYER_ID); break;
  case FormModel::ERROR_OUTOFBOUNDS_DIRECTION: $message = sprintf('The direction must be between 0-%d.', Packet::MAX_DIRECTION); break;
  case FormModel::ERROR_OUTOFBOUNDS_FORMAT: $message = sprintf('The format length must be between 1-%d.', Packet::MAX_FORMAT); break;
  case FormModel::ERROR_OUTOFBOUNDS_ID: $message = sprintf('The id must be between 0-%d.', Packet::MAX_ID); break;
  case FormModel::ERROR_OUTOFBOUNDS_NAME: $message = sprintf('The name length must be between 1-%d.', Packet::MAX_NAME); break;
  case FormModel::ERROR_OUTOFBOUNDS_PACKET_ID: $message = sprintf('The packet id must be between 0-%d.', Packet::MAX_PACKET_ID); break;
  case FormModel::ERROR_OUTOFBOUNDS_REMARKS: $message = sprintf('The remarks length must be between 0-%d.', Packet::MAX_REMARKS); break;
  case FormModel::ERROR_OUTOFBOUNDS_TRANSPORT_LAYER_ID: $message = sprintf('The transport layer must be between 0-%d.', Packet::MAX_TRANSPORT_LAYER_ID); break;
  case FormModel::ERROR_OUTOFBOUNDS_USED_BY: $message = 'The products selected as using this packet were invalid.'; break;
  case FormModel::ERROR_SUCCESS: $message = 'The packet has been created successfully!'; break;
  default: $message = $error;
}
$form_fields = $this->getContext()->form_fields;
$form_products = $this->getContext()->products;
$packet = $this->getContext()->packet;
require('./header.inc.phtml');
echo '<div class="container">' . PHP_EOL;
if ($error === FormModel::ERROR_ACL_DENIED)
{
  require('./LoginRequired.inc.phtml');
}
else if ($error === FormModel::ERROR_SUCCESS)
{
  printf('<h1 class="text-success">%s</h1>%s', $title, PHP_EOL);
  printf('<div class="alert alert-success"><p class="mb-0">%s</p></div>%s', $message, PHP_EOL);
  printf('<div class="text-center">%s', PHP_EOL);
  printf('<a class="btn btn-primary" href="javascript:history.go(-1);">Back</a>%s', PHP_EOL);
  if (isset($packet))
  {
    printf('<a class="btn btn-success" href="%s">View Packet</a>%s', $packet->getURI(), PHP_EOL);
  }
  printf('<a class="btn btn-info ml-2" href="%s">All Packets</a>%s', Common::relativeUrlToAbsolute('/packet/index'), PHP_EOL);
  printf('</div>%s', PHP_EOL);
}
else
{
  printf('<h1>%s</h1>%s<p>%s</p>%s', $title, PHP_EOL, $description, PHP_EOL);
  if (!empty($message))
  {
    printf('<div class="alert alert-danger"><p class="mb-0">%s</p></div>%s', $message, PHP_EOL);
  }
  require('./Packet/Form.inc.phtml');
}
echo '</div>' . PHP_EOL;
require('./footer.inc.phtml');
