<?php

namespace BNETDocs\Templates\Packet;

use \CarlBennett\MVC\Libraries\Pair;

$title       = "Delete Packet";
$description = "This form allows an individual to delete a packet.";

$this->opengraph->attach(new Pair("url", "/packet/delete"));
$this->opengraph->attach(new Pair("type", "article"));

switch ($this->getContext()->error) {
  case "ACL_NOT_SET":
    $message = "You do not have the privilege to delete packets.";
    break;
  case "NOT_FOUND":
    $message = "Cannot find packet by that id.";
    break;
  case "NOT_LOGGED_IN":
    $message = "You must be logged in to delete packets.";
    break;
  case "INTERNAL_ERROR":
    $message = "An internal error occurred while processing your request. "
      . "Our staff have been notified of the issue. Try again later.";
    break;
  default:
    $message = $this->getContext()->error;
}

$this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
<?php if (is_null($this->getContext()->error)) { ?>
        <header>Delete Packet</header>
        <form method="POST" action="?id=<?php echo
            htmlspecialchars($this->getContext()->id, ENT_HTML5, "UTF-8"); ?>">
          <section>
            <p>Are you sure you wish to delete this packet?</p>
            <p><input type="text" readonly="readonly" value="<?php echo filter_var($this->getContext()->title, FILTER_SANITIZE_STRING); ?>" tabindex="1"/></p>
            <p><input type="submit" value="Delete Packet" tabindex="2" autofocus="autofocus"/></p>
          </section>
        </form>
<?php } else if ($this->getContext()->error === false) { ?>
        <header class="green">Packet Deleted</header>
        <section class="green">
          <p>You have successfully deleted the packet!</p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } else { ?>
        <header class="red">Delete Packet</header>
        <section class="red">
          <p>An error occurred while attempting to delete the packet.</p>
          <p><?php echo $message; ?></p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
