<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Packet;
use \BNETDocs\Libraries\Comment;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Edit Packet';
$description = 'This form allows an individual to edit a packet.';
$this->opengraph->attach(new Pair('url', '/packet/edit'));
$this->opengraph->attach(new Pair('type', 'article'));
$comments = $this->getContext()->comments;
$error = $this->getContext()->error;
switch ($error)
{
  case 'ACL_NOT_SET': $message = 'You do not have the privilege to edit packets.'; break;
  case 'NOT_FOUND': $message = 'Cannot find packet by that id.'; break;
  case 'EMPTY_NAME': $message = 'The name of the packet is required.'; break;
  case 'EMPTY_FORMAT': $message = 'The format of the packet is required.'; break;
  case 'EMPTY_REMARKS': $message = 'The remarks of the packet is required.'; break;
  case 'INTERNAL_ERROR': $message = 'An internal error occurred while processing your request. Our staff have been notified of the issue. Try again later.'; break;
  default: $message = $error;
}
$id = filter_var($this->getContext()->id, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$packet_format = filter_var($this->getContext()->format, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$packet_id = filter_var($this->getContext()->packet_id, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$packet_name = filter_var($this->getContext()->name, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$packet_remarks = filter_var($this->getContext()->remarks, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$packet_used_by = $this->getContext()->used_by;
$products = $this->getContext()->products;
require('./header.inc.phtml'); ?>
<div class="container">
<? if ($error !== false) { ?>
  <h1>Edit Packet</h1>
<? if (!empty($message)) { ?>
  <div class="alert alert-danger"><p class="mb-0"><?=$message?></p></div>
<? } ?>
<? if ($error != 'NOT_FOUND') { ?>
  <form method="POST" action="?id=<?=$packet_id?>">
    <div class="row">
      <div class="col-md-3">
        <div class="form-group">
          <label class="font-weight-bold" for="id">Id:</label>
          <input class="bg-dark border border-primary form-control text-light" type="text" name="id" id="id" placeholder="Enter the message id here" tabindex="1" required  autofocus="autofocus" value="<?=$id?>"/>
        </div>
      </div><div class="col-md-6">
        <div class="form-group">
          <label class="font-weight-bold" for="name">Name:</label>
          <input class="bg-dark border border-primary form-control text-light" type="text" name="name" id="name" placeholder="Enter the message name here" tabindex="2" required value="<?=$packet_name?>"/>
        </div>
      </div><div class="col-md-3">
        <div class="form-group">
          <label class="font-weight-bold">Options:</label>
          <div class="custom-control custom-switch"><input class="custom-control-input" type="checkbox" id="deprecated" name="deprecated" value="1"<?=($this->getContext()->deprecated?' checked="checked"':'')?> tabindex="6"/><label class="custom-control-label text-danger" for="deprecated">Deprecated</label></div>
          <div class="custom-control custom-switch"><input class="custom-control-input" type="checkbox" id="research" name="research" value="1"<?=($this->getContext()->research?' checked="checked"':'')?> tabindex="7"/> <label class="custom-control-label text-warning" for="research">In Research</label></div>
          <div class="custom-control custom-switch"><input class="custom-control-input" type="checkbox" id="published" name="published" value="1"<?=($this->getContext()->published?' checked="checked"':'')?> tabindex="8"/> <label class="custom-control-label text-success" for="published">Published</label></div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="font-weight-bold" for="format">Format:</label>
      <textarea class="bg-dark border border-primary form-control language-objectivec text-light text-monospace" style="height:120px;" name="format" id="format" tabindex="3" required><?=$packet_format?></textarea>
    </div>
    <div class="form-group">
      <label class="font-weight-bold">Used by:</label>
      <table class="table table-sm">
        <thead></thead><tbody>
<?      $product_ubound = count($products);
        for ($product_i = 0; $product_i < $product_ubound; ++$product_i)
        {
          if ($product_i % 2 === 0) echo '<tr>';
          $p = $products[$product_i];
          $p_id = $p->getBnetProductId();
          $p_label = $p->getLabel();
          printf('<td><div class="custom-control custom-switch"><input class="custom-control-input" type="checkbox" id="used_by_%s" name="used_by[]" value="%s"%s/><label class="custom-control-label" for="used_by_%s">%s</label></div></td>', $p_id, $p_id, (in_array($p, $packet_used_by) ? ' checked="checked"' : ''), $p_id, $p_label);
          if ($product_i % 2 === 1) echo '</tr>';
        } ?>
        </tbody>
      </table>
    </div>
    <div class="form-group">
      <label class="font-weight-bold" for="remarks">Remarks:</label>
      <span class="float-right">
        <div class="custom-control custom-switch">
          <input class="custom-control-input" type="checkbox" name="markdown" id="markdown" tabindex="5"
          title="Use markdown or use raw HTML" value="1"<?=($this->getContext()->markdown?' checked="checked"':'')?>/>
          <label class="custom-control-label" for="markdown" title="Use markdown or use raw HTML">Markdown</label>
        </div>
      </span>
      <textarea class="bg-dark border border-primary form-control text-light" style="height:200px;" name="remarks" id="remarks" tabindex="4" required><?=$packet_remarks?></textarea>
    </div>
    <div class="form-group text-center">
      <input class="btn btn-success" type="submit" value="Save" tabindex="9"/>
    </div>
  </form>
<? $comment_parent_type = Comment::PARENT_TYPE_PACKET; $comment_parent_id = $packet_id; require('./Comment/Section.inc.phtml'); } ?>
<? } else { ?>
  <h1 class="text-success">Edit Packet</h1>
  <div class="alert alert-success"><p class="mb-0">Your packet has been edited.</p></div>
<? } ?>
</div>
<? require('./footer.inc.phtml'); ?>
