<?php

namespace BNETDocs\Templates\Packet;

use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;

$title       = "Edit Packet";
$description = "This form allows an individual to edit a packet.";

$this->opengraph->attach(new Pair("url", "/packet/edit"));
$this->opengraph->attach(new Pair("type", "article"));

switch ($this->getContext()->error) {
  case "ACL_NOT_SET":
    $message = "You do not have the privilege to edit packets.";
    break;
  case "NOT_FOUND":
    $message = "Cannot find packet by that id.";
    break;
  case "INVALID_CSRF":
    $message = "The Cross-Site Request Forgery token was invalid. Either the"
      . "edit packet form expired, or this may have been a malicious attempt"
      . "to create a packet.";
    break;
  case "EMPTY_NAME":
    $message = "The name of the packet is required.";
    break;
  case "EMPTY_FORMAT":
    $message = "The format of the packet is required.";
    break;
  case "EMPTY_REMARKS":
    $message = "The remarks of the packet is required.";
    break;
  case "INTERNAL_ERROR":
    $message = "An internal error occurred while processing your request. "
      . "Our staff has been notified of the issue. Try again later.";
    break;
  default:
    $message = $this->getContext()->error;
}

$this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
<?php if ($this->getContext()->error !== false) { ?>
        <header>Edit Packet</header>
<?php if (!empty($message)) { ?>
        <section class="red"><p><?php echo $message; ?></p></section>
<?php } ?>
<?php if ($this->getContext()->error != "NOT_FOUND") { ?>
        <form method="POST" action="?id=<?php echo
            htmlspecialchars($this->getContext()->packet_id, ENT_HTML5, "UTF-8"); ?>">
          <input type="hidden" name="csrf_id" value="<?php echo
            htmlspecialchars($this->getContext()->csrf_id, ENT_HTML5, "UTF-8");
          ?>"/>
          <input type="hidden" name="csrf_token" value="<?php echo
            htmlspecialchars($this->getContext()->csrf_token, ENT_HTML5, "UTF-8");
          ?>"/>
          <section>
            <label for="title">Name:</label><br/>
            <input type="text" name="name" id="name" tabindex="1" required
              autofocus="autofocus" value="<?php echo
                filter_var($this->getContext()->name, FILTER_SANITIZE_STRING);
              ?>"/>
          </section>
          <section>
            <label for="format">Remarks:</label>
            <textarea name="format" id="format" tabindex="2" required
              style="height:200px;"><?php echo
                htmlspecialchars($this->getContext()->format, ENT_HTML5, "UTF-8");
              ?></textarea>
          </section>
          <section>
            <label for="remarks">Remarks:</label>
            <span style="float:right;">
              <label for="markdown" title="Use markdown or use raw HTML">Markdown</label>
              <input type="checkbox" name="markdown" id="markdown" tabindex="4"
                title="Use markdown or use raw HTML" value="1"<?php
                  if ($this->getContext()->markdown)
                    echo " checked=\"checked\"";
                ?>/>
            </span>
            <textarea name="remarks" id="remarks" tabindex="3" required
              style="height:200px;"><?php echo
                htmlspecialchars($this->getContext()->remarks, ENT_HTML5, "UTF-8");
              ?></textarea>
          </section>
          <section>
            <input type="submit" name="publish" value="Publish" tabindex="5"/>
            <input type="submit" name="save" value="Unpublish" tabindex="6"/>
          </section>
        </form>
<?php } ?>
<?php } else { ?>
        <header class="green">Edit Packet</header>
        <section class="green">
          <p>Your packet has been edited.</p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
