<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Packet;
use \BNETDocs\Libraries\Comment;
use \BNETDocs\Libraries\Packet;
use \BNETDocs\Libraries\Packet\Application as PacketAppLayer;
use \BNETDocs\Libraries\Packet\Transport as PacketTransportLayer;
use \CarlBennett\MVC\Libraries\Common; ?>
<form method="POST">
  <div class="row">
    <div class="col-lg-3">
      <div class="form-group">
        <label class="font-weight-bold" for="direction">Direction:</label>
        <select class="bg-dark border border-primary custom-select text-light" name="direction" id="direction" tabindex="1">
          <option value="<?=Packet::DIRECTION_CLIENT_SERVER?>"<?=($form_fields['direction'] ?? null === Packet::DIRECTION_CLIENT_SERVER ? ' selected' : '')?>>Client to Server</option>
          <option value="<?=Packet::DIRECTION_SERVER_CLIENT?>"<?=($form_fields['direction'] ?? null === Packet::DIRECTION_SERVER_CLIENT ? ' selected' : '')?>>Server to Client</option>
          <option value="<?=Packet::DIRECTION_PEER_TO_PEER?>"<?=($form_fields['direction'] ?? null === Packet::DIRECTION_PEER_TO_PEER ? ' selected' : '')?>>Peer to Peer</option>
        </select>
      </div>
    </div><div class="col-lg-3">
      <div class="form-group">
        <label class="font-weight-bold" for="packet_id">Id: <span class="small text-muted">(supports prefixes like &amp;h, 0x, etc.)</span></label>
        <input class="bg-dark border border-primary form-control text-light" type="text" name="packet_id" id="packet_id" placeholder="Enter the message id here" tabindex="2" required  autofocus="autofocus" value="<?=filter_var($form_fields['packet_id'] ?? null, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>"/>
      </div>
    </div><div class="col-lg-4">
      <div class="form-group">
        <label class="font-weight-bold" for="name">Name: <span class="small text-muted">(e.g. SID_NULL)</span></label>
        <input class="bg-dark border border-primary form-control text-light" type="text" name="name" id="name" placeholder="Enter the message name here" tabindex="3" required value="<?=$form_fields['name'] ?? ''?>"/>
      </div>
    </div><div class="col-lg-2">
      <div class="form-group">
        <label class="font-weight-bold">Options:</label>
        <div class="custom-control custom-switch"><input class="custom-control-input" type="checkbox" id="deprecated" name="deprecated" value="1"<?=($form_fields['deprecated'] ?? null ? ' selected' : '')?> tabindex="4"/><label class="custom-control-label text-danger" for="deprecated">Deprecated</label></div>
        <div class="custom-control custom-switch"><input class="custom-control-input" type="checkbox" id="research" name="research" value="1"<?=($form_fields['research'] ?? null ? ' selected' : '')?> tabindex="5"/> <label class="custom-control-label text-warning" for="research">In Research</label></div>
        <div class="custom-control custom-switch"><input class="custom-control-input" type="checkbox" id="published" name="published" value="1"<?=($form_fields['published'] ?? null ? ' selected' : '')?> tabindex="6"/> <label class="custom-control-label text-success" for="published">Published</label></div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="form-group">
        <label class="font-weight-bold" for="transport_layer">Transport layer:</label>
        <select class="bg-dark border border-primary custom-select text-light" name="transport_layer" id="transport_layer" tabindex="7">
<?      foreach (PacketTransportLayer::getAllAsArray() as $id => $label)
        {
          printf('<option value="%s"%s>%s (%s)</option>',
            $id, ($id === ($form_fields['transport_layer'] ?? null) ? ' selected' : ''), $label[1], $label[0]
          );
        } ?>
        </select>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="form-group">
        <label class="font-weight-bold" for="application_layer">Application layer:</label>
        <select class="bg-dark border border-primary custom-select text-light" name="application_layer" id="application_layer" tabindex="7">
<?      foreach (PacketAppLayer::getAllAsArray() as $id => $label)
        {
          printf('<option value="%s"%s>%s (%s)</option>',
            $id, ($id === ($form_fields['application_layer'] ?? null) ? ' selected' : ''), $label[1], $label[0]
          );
        } ?>
        </select>
      </div>
    </div>
  </div>
  <div class="form-group">
    <label class="font-weight-bold" for="format">Format: <span class="small text-muted">(see <a rel="external" href="https://bnetdocs.org/document/19/notational-convention-sizes-types">Notational Convention</a> for help or <code>[blank]</code> for none)</span></label>
    <textarea class="bg-dark border border-primary form-control language-objectivec text-light text-monospace" style="height:120px;" name="format" id="format" placeholder="Enter the message format here" tabindex="3" required><?=filter_var($form_fields['format'] ?? null, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></textarea>
  </div>
  <div class="form-group">
    <label class="font-weight-bold">Used by: <span class="small text-muted">(products that currently use or have used this packet)</span></label>
    <table class="table table-borderless table-sm">
      <thead></thead><tbody>
<?      $p_ubound = count($form_products);
      for ($p_i = 0; $p_i < $p_ubound; ++$p_i)
      {
        if ($p_i % 2 === 0) echo '<tr>';
        $p = $form_products[$p_i];
        $p_id = $p->getBnetProductId();
        $p_label = $p->getLabel();
        printf('<td><div class="custom-control custom-switch"><input class="custom-control-input" type="checkbox" id="used_by_%s" name="used_by[]" value="%s"%s/><label class="custom-control-label" for="used_by_%s">%s</label></div></td>', $p_id, $p_id, (in_array($p, $form_fields['used_by'] ?? []) ? ' selected' : ''), $p_id, $p_label);
        if ($p_i % 2 === 1) echo '</tr>';
      } ?>
      </tbody>
    </table>
  </div>
  <div class="form-group">
    <label class="font-weight-bold" for="remarks">Remarks: <span class="small text-muted">(a description of what, when, where, and why this packet is used, and any related info)</span></label>
    <span class="float-right">
      <div class="custom-control custom-switch">
        <input class="custom-control-input" type="checkbox" name="markdown" id="markdown" tabindex="5"
        title="Use markdown or use raw HTML" value="1"<?=($form_fields['markdown'] ?? null ? ' selected' : '')?>/>
        <label class="custom-control-label" for="markdown" title="Use markdown or use raw HTML">Markdown</label>
      </div>
    </span>
    <textarea class="bg-dark border border-primary form-control text-light" style="height:200px;" name="remarks" id="remarks" placeholder="Enter the message remarks here" tabindex="4" required><?=filter_var($form_fields['remarks'] ?? null, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></textarea>
  </div>
  <div class="form-group text-center">
    <input class="btn btn-success" type="submit" value="Save" tabindex="9"/>
  </div>
</form>
<? if (isset($comments)) { $comment_parent_type = Comment::PARENT_TYPE_PACKET; $comment_parent_id = $form_fields['packet_id'] ?? null; require('./Comment/Section.inc.phtml'); } ?>
