<?php
namespace BNETDocs\Templates;

use \CarlBennett\MVC\Libraries\Common;
use \BNETDocs\Libraries\Packet;
use \BNETDocs\Libraries\Pair;
use \BNETDocs\Libraries\User;

$title       = "Packet Index";
$description = "The index for packets on BNETDocs";
$this->opengraph->attach(new Pair("url", "/packet/index"));

require("./header.inc.phtml");
?>
      <article>
        <header>Packet Index</header>
        <section>
          <p>These packets are also available as constants in
            <a href="<?php echo Common::relativeUrlToAbsolute("/packet/index.cpp"); ?>">C++</a>,
            <a href="<?php echo Common::relativeUrlToAbsolute("/packet/index.java"); ?>">Java</a>,
            <a href="<?php echo Common::relativeUrlToAbsolute("/packet/index.json"); ?>">JSON</a>,
            <a href="<?php echo Common::relativeUrlToAbsolute("/packet/index.php"); ?>">PHP</a>, and
            <a href="<?php echo Common::relativeUrlToAbsolute("/packet/index.vb"); ?>">VB6</a>.
          </p>
          <table>
            <thead>
              <tr>
                <th class="left">Found <?php echo number_format($this->getContext()->sum_packets); ?> packet<?php echo ($this->getContext()->sum_packets != 1 ? "s" : ""); ?></th>
                <th class="left">Author</th>
              </tr>
            </thead><tbody>
<?php foreach ($this->getContext()->packets as $packet) {
        $user         = $packet->getUser();
        if ($user) {
          $user_url   = $user->getURI();
          $avatar_url = $user->getAvatarURI(22);
        }
        $packet_id = $packet->getPacketId(true);
?>
              <tr>
                <td><strong><a href="<?php echo $packet->getURI(); ?>"><?php echo htmlspecialchars($packet->getPacketDirectionTag() . " " . $packet_id . " " . $packet->getPacketName(), ENT_HTML5, "UTF-8"); ?></a></strong><br/><span style="color:#aaa;"><?php echo rtrim(Common::stripUpTo(Common::stripUpTo(trim(filter_var($packet->getPacketRemarks(true), FILTER_SANITIZE_STRING)), "\n", 90), ". ", 90), "."); ?></span></td>
                <td><?php if ($user) { ?><a href="<?php echo $user_url; ?>"><img class="avatar" src="<?php echo $avatar_url; ?>"/> <?php echo htmlspecialchars($user->getName(), ENT_HTML5, "UTF-8"); ?></a><?php } else { ?>Anonymous<?php } ?></td>
              </tr>
<?php } ?>
          </tbody></table>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
