<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Packet;
use \BNETDocs\Libraries\Packet;
use \BNETDocs\Libraries\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'All Packets';
$description = 'The index for all of the packets documented on BNETDocs';
$this->opengraph->attach(new Pair('url', '/packet/index'));
$order = $this->getContext()->order;
$form_order_by = [
  'created-datetime-asc' => 'Created Timestamp (Ascending)',
  'created-datetime-desc' => 'Created Timestamp (Descending)',
  'id-asc' => 'Database Id (Ascending)',
  'id-desc' => 'Database Id (Descending)',
  'packet-id-asc' => 'Packet Id (Ascending)',
  'packet-id-desc' => 'Packet Id (Descending)',
  'user-id-asc' => 'User Id (Ascending)',
  'user-id-desc' => 'User Id (Descending)',
];
require_once('./MarkdownBootstrapFix.inc.php');
require('./header.inc.phtml'); ?>
<div class="container">
  <h2><?=$title?></h2>
  <p><?=$description?></p>
  <form method="GET" class="m-2" id="filter_form">
    <div class="form-group" id="order_by_form">
      <label for="order" class="font-weight-bold m-1">Order by:</label>
      <select class="form-control form-control-sm m-1" name="order" id="order" onchange="form.submit();" style="display:inline-block;width:200px;">
<?    foreach ($form_order_by as $item_value => $item_label) {
        $item_selected = ($order === $item_value ? ' selected="selected"' : '');
        echo sprintf('<option value="%s"%s>%s</option>' . PHP_EOL, $item_value, $item_selected, $item_label);
      } ?>
      </select>
    </div>
    <div class="form-group">
      <table class="table table-borderless table-sm d-inline-block"><thead><tr><th colspan="3" class="text-center">Packet Types</th></tr></thead><tbody>
<?    $x = 0;
      foreach ($this->getContext()->application_layers as $layer)
      {
        $id = 'pktapplayer-' . $layer->getId();
        $chk = in_array($layer->getId(), $this->getContext()->pktapplayer);
        if ( $x % 3 == 0 ) { echo '<tr>'; }
        echo sprintf(
          '<td><div class="custom-control custom-switch"><input class="custom-control-input" type="checkbox" name="pktapplayer[]" id="%s" value="%s"%s><label class="custom-control-label" for="%s">%s</label></div></td>',
          $id, $layer->getId(), ($chk ? ' checked="checked"' : ''), $id, $layer->getTag()
        );
        if ( $x % 3 == 2 ) { echo '</tr>'; }
        $x++;
      }
      if ( $x % 3 > 0 ) { echo '</tr>'; } ?>
        <tr><td colspan="3" class="text-center"><input class="btn btn-sm btn-secondary" type="submit" value="Set Filter"/></td></tr>
      </tbody></table>
    </div>
  </form>
  <table class="table table-hover table-striped" id="packets_tbl">
    <thead><tr><th>Packet</th><th>Author</th></tr></thead><tbody>
<?  foreach ($this->getContext()->packets as $packet)
    {
      $user = $packet->getUser();
      if ($user)
      {
        $avatar_url = $user->getAvatarURI(22);
        $user_url = $user->getURI();
      }
      $brief = $packet->getBrief(true);
      $deprecated = $packet->isDeprecated();
      $packet_id = $packet->getPacketId(true);
      $published = $packet->isPublished();
      $remarks = $packet->getRemarks(true);
      $research = $packet->isInResearch();

      if (!empty($brief))
      {
        $brief = \BNETDocs\Templates\MarkdownBootstrapFix($brief, true, true);
      }
      else
      {
        $brief = rtrim(Common::stripUpTo(Common::stripUpTo(trim(filter_var($remarks, FILTER_SANITIZE_STRING)), "\n", 128), '. ', 128), '.');
      }

      ob_start();
      if ($deprecated) require('./Deprecated.inc.phtml');
      if ($research) require('./InResearch.inc.phtml');
      if (!$published) require('./Draft.inc.phtml');
      $tpl_packet_flags = ob_get_clean();
      if (!empty($tpl_packet_flags)) $tpl_packet_flags = ' ' . $tpl_packet_flags;

      echo '<tr>';
      printf('<td><strong><a href="%s">%s</a></strong>%s<br/><span class="text-muted">%s</span></td>',
        $packet->getURI(),
        filter_var($packet->getLabel(), FILTER_SANITIZE_FULL_SPECIAL_CHARS),
        $tpl_packet_flags,
        $brief
      );
      printf('<td>%s</td>', (
        $user ? sprintf('<a href="%s"><img class="mr-2 rounded" src="%s">%s</a>',
          $user_url, $avatar_url, filter_var($user->getName(), FILTER_SANITIZE_STRING)
        ) : 'Anonymous')
      );
      echo '</tr>';
    } ?>
  </tbody></table>
  <p>These packets are also available as constants in
<? $q = getenv('QUERY_STRING'); if (!empty($q)) { $q = '?' . $q; } ?>
    <a href="<?=Common::relativeUrlToAbsolute('/packet/index.cpp' . $q)?>">C++</a>,
    <a href="<?=Common::relativeUrlToAbsolute('/packet/index.java' . $q)?>">Java</a>,
    <a href="<?=Common::relativeUrlToAbsolute('/packet/index.json' . $q)?>">JSON</a>,
    <a href="<?=Common::relativeUrlToAbsolute('/packet/index.php' . $q)?>">PHP</a>, and
    <a href="<?=Common::relativeUrlToAbsolute('/packet/index.vb' . $q)?>">VB6</a>.
  </p>
</div>
<? ob_start(); ?>
  <script type="text/javascript">
    $(document).ready(function(){
      $('#packets_tbl').DataTable({
        'aaSorting': [],
        'language': {'zeroRecords': 'No matching packets found'},
        'responsive': false,
      });
    });
  </script>
<? $_footer_script = ob_get_clean(); require('./footer.inc.phtml'); ?>
