<?php

namespace BNETDocs\Templates\Packet;

use \BNETDocs\Libraries\Packet;
use \BNETDocs\Libraries\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;

$title       = 'Packet Index';
$description = 'The index for packets on BNETDocs';
$this->opengraph->attach(new Pair('url', '/packet/index'));

$order = $this->getContext()->order;

$this->additional_css[] = '/a/forms.css';
require('./header.inc.phtml');
?>
      <article>
        <header>Packet Index</header>
        <section>
          <form method="GET">
            <div style="text-align:center;">
              <label for="order">Order by:</label>
              <select name="order" id="order" onchange="form.submit();"
                style="display:inline-block;width:200px;">
                <option value="created-datetime-asc"<?php
                  if ($order === 'created-datetime-asc') { echo ' selected="selected"';
                  } ?>>Created Timestamp (Ascending)</option>
                <option value="created-datetime-desc"<?php
                  if ($order === 'created-datetime-desc') { echo ' selected="selected"';
                  } ?>>Created Timestamp (Descending)</option>
                <option value="id-asc"<?php
                  if ($order === 'id-asc') { echo ' selected="selected"';
                  } ?>>Database Id (Ascending)</option>
                <option value="id-desc"<?php
                  if ($order === 'id-desc') { echo ' selected="selected"';
                  } ?>>Database Id (Descending)</option>
                <option value="packet-id-asc"<?php
                  if ($order === 'packet-id-asc') { echo ' selected="selected"';
                  } ?>>Packet Id (Ascending)</option>
                <option value="packet-id-desc"<?php
                  if ($order === 'packet-id-desc') { echo ' selected="selected"';
                  } ?>>Packet Id (Descending)</option>
                <option value="user-id-asc"<?php
                  if ($order === 'user-id-asc') { echo ' selected="selected"';
                  } ?>>User Id (Ascending)</option>
                <option value="user-id-desc"<?php
                  if ($order === 'user-id-desc') { echo ' selected="selected"';
                  } ?>>User Id (Descending)</option>
              </select>
            </div>
            <table><thead><tr><th colspan="3">Packet Types</th></tr></thead><tbody>
<?php $x = 0; foreach ($this->getContext()->application_layers as $layer) {
  $id = 'pktapplayer-' . $layer->getId();
  $chk = in_array( $layer->getId(), $this->getContext()->pktapplayer );
  if ( $x % 3 == 0 ) { ?>
              <tr>
<?php } ?>
                <td><input type="checkbox" name="pktapplayer[]" id="<?php echo $id; ?>" value="<?php echo $layer->getId(); ?>"<?php if ($chk) { ?> checked="checked"<?php } ?>> <label for="<?php echo $id; ?>"><?php echo $layer->getTag(); ?></label></td>
<?php if ( $x % 3 == 2 ) { ?>
              </tr>
<?php } ?>
<?php $x++; } ?>
<?php if ( $x % 3 > 0 ) { ?>
              </tr>
<?php } ?>
            </tbody></table>
            <div style="text-align:center;"><input type="submit" value="Submit"/></div>
          </form>
          <hr/>
          <table>
            <thead>
              <tr>
                <th class="left">Packet</th>
                <th class="left">Author</th>
              </tr>
            </thead><tbody>
<?php foreach ($this->getContext()->packets as $packet) {
        $user         = $packet->getUser();
        if ($user) {
          $user_url   = $user->getURI();
          $avatar_url = $user->getAvatarURI(22);
        }
        $packet_id = $packet->getPacketId(true);
?>
              <tr>
                <td><strong><a href="<?php echo $packet->getURI(); ?>"><?php echo filter_var($packet->getPacketDirectionTag() . " " . $packet_id . " " . $packet->getPacketName(), FILTER_SANITIZE_STRING); ?></a></strong><br/><span style="color:#aaa;"><?php echo rtrim(Common::stripUpTo(Common::stripUpTo(trim(filter_var($packet->getPacketRemarks(true), FILTER_SANITIZE_STRING)), "\n", 90), ". ", 90), "."); ?></span></td>
                <td><?php if ($user) { ?><a href="<?php echo $user_url; ?>"><img class="avatar" src="<?php echo $avatar_url; ?>"/>&nbsp;<?php echo filter_var($user->getName(), FILTER_SANITIZE_STRING); ?></a><?php } else { ?>Anonymous<?php } ?></td>
              </tr>
<?php } ?>
          </tbody></table>
        </section>
        <section>
          <p>These packets are also available as constants in
<?php $q = getenv('QUERY_STRING'); if (!empty($q)) { $q = '?' . $q; } ?>
            <a href="<?php echo Common::relativeUrlToAbsolute('/packet/index.cpp' . $q); ?>">C++</a>,
            <a href="<?php echo Common::relativeUrlToAbsolute('/packet/index.java' . $q); ?>">Java</a>,
            <a href="<?php echo Common::relativeUrlToAbsolute('/packet/index.json' . $q); ?>">JSON</a>,
            <a href="<?php echo Common::relativeUrlToAbsolute('/packet/index.php' . $q); ?>">PHP</a>, and
            <a href="<?php echo Common::relativeUrlToAbsolute('/packet/index.vb' . $q); ?>">VB6</a>.
          </p>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
