<?php

namespace BNETDocs\Templates\Packet;

use \CarlBennett\MVC\Libraries\Pair;

$title       = "Popular Packets";
$description = "The popular packets on BNETDocs";
$this->opengraph->attach(new Pair("url", "/packet/popular"));

require("./header.inc.phtml");
?>
      <article>
        <header>Popular Packets</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
