<?php

namespace BNETDocs\Templates\Packet;

use \BNETDocs\Libraries\Packet;
use \BNETDocs\Libraries\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;

$title       = "Search Packets";
$description = "Search the packets on BNETDocs";
$this->opengraph->attach(new Pair("url", "/packet/search"));

if (!empty($this->getContext()->query)) {
  $title = $this->getContext()->query . " - " . $title;
}

$this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
        <header>Search Packets</header>
        <section>
          <form method="GET">
            <input type="text" name="q" id="q" value="<?php echo htmlentities($this->getContext()->query, ENT_HTML5, "UTF-8"); ?>" tabindex="1" autofocus="autofocus"/>
            <input type="submit" value="Submit"/>
          </form>
<?php if (!is_null($this->getContext()->packets)) { ?>
          <table>
            <thead>
              <tr>
                <th class="left">Found <?php echo number_format($this->getContext()->sum_packets); ?> packet<?php echo ($this->getContext()->sum_packets != 1 ? "s" : ""); ?> matching: <?php echo htmlentities($this->getContext()->query, ENT_HTML5, "UTF-8"); ?></th>
                <th class="left">Author</th>
              </tr>
            </thead><tbody>
<?php foreach ($this->getContext()->packets as $packet) {
        $user         = $packet->getUser();
        if ($user) {
          $user_url   = $user->getURI();
          $avatar_url = $user->getAvatarURI(22);
        }
        $packet_id = $packet->getPacketId(true);
?>
              <tr>
                <td><strong><a href="<?php echo $packet->getURI(); ?>"><?php echo htmlspecialchars($packet->getPacketDirectionTag() . " " . $packet_id . " " . $packet->getPacketName(), ENT_HTML5, "UTF-8"); ?></a></strong><br/><span style="color:#aaa;"><?php echo rtrim(Common::stripUpTo(Common::stripUpTo(trim(filter_var($packet->getPacketRemarks(true), FILTER_SANITIZE_STRING)), "\n", 90), ". ", 90), "."); ?></span></td>
                <td><?php if ($user) { ?><a href="<?php echo $user_url; ?>"><img class="avatar" src="<?php echo $avatar_url; ?>"/> <?php echo htmlspecialchars($user->getName(), ENT_HTML5, "UTF-8"); ?></a><?php } else { ?>Anonymous<?php } ?></td>
              </tr>
<?php } ?>
          </tbody></table>
<?php } ?>
        </section>
      </article>
      <article>
        <header>Suggestion</header>
        <section>
          <p><a href="<?php echo Common::relativeUrlToAbsolute("/packet/index"); ?>">Click here</a> to see all of the packets.</p>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
