<?php

namespace BNETDocs\Templates\Packet;

use \BNETDocs\Libraries\Authentication;
use \BNETDocs\Libraries\Comment;
use \BNETDocs\Libraries\User;

use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;

$comments  = $this->getContext()->comments;
$object_id = $this->getContext()->packet_id;
$object    = $this->getContext()->packet;

$logged_in    = Authentication::$user;
$logged_in_id = ($logged_in ? $logged_in->getId() : null);

$title       = "Packet Not Found";
$description = "The requested packet does not exist or could not be found.";

$this->opengraph->attach(new Pair("type", "article"));

$url = Common::relativeUrlToAbsolute("/packet/" . urlencode($object_id));

if ($object) {

  $url       = $object->getURI();
  $packet_id = $object->getPacketId(true);

  $title = $object->getPacketDirectionTag() . ' '
    . $packet_id . ' '
    . $object->getPacketName();

  $description = Common::stripUpTo(trim(filter_var(
    $object->getPacketRemarks(true), FILTER_SANITIZE_STRING
  )), "\n", 300);

  if ($object->getUserId() !== null) {
    $user_name   = $object->getUser()->getName();
    $user_id     = $object->getUserId();
    $user_url    = $object->getUser()->getURI();
    $user_avatar = $object->getUser()->getAvatarURI(22);
  } else {
    $user_name   = null;
    $user_id     = null;
    $user_url    = null;
    $user_avatar = null;
  }

}

$this->opengraph->attach(new Pair("url", $url));

$edit_url       = Common::relativeUrlToAbsolute("/packet/edit?id=" . urlencode($object_id));
$delete_url     = Common::relativeUrlToAbsolute("/packet/delete?id=" . urlencode($object_id));
$edit_visible   = ($logged_in && ($logged_in->getOptionsBitmask()
                & User::OPTION_ACL_PACKET_MODIFY));
$delete_visible = ($logged_in && ($logged_in->getOptionsBitmask()
                & User::OPTION_ACL_PACKET_DELETE));

$this->additional_css[] = "/a/table-keypair.css";
$this->additional_css[] = "/a/comments.css";
if ($logged_in) $this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
<?php if ($object) { ?>
        <a href="https://twitter.com/share?text=<?php echo urlencode($packet_id . " " . $object->getPacketName()); ?>&amp;url=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-twitter-24px.png"); ?>"/></a>
        <a href="https://facebook.com/sharer/sharer.php?u=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-facebook-24px.png"); ?>"/></a>
<?php if ($edit_visible) { ?>
        <a href="<?php echo $edit_url; ?>" class="header-button float-right">Edit</a>
<?php } ?>
<?php if ($delete_visible) { ?>
        <a href="<?php echo $delete_url; ?>" class="header-button float-right">Delete</a>
<?php } ?>
        <header><a href="<?php echo $url; ?>"><?php echo filter_var($title, FILTER_SANITIZE_STRING); ?></a></header>
        <section>
          <table class="info"><tbody>
            <tr><th style="width:20%;">Message Id:</th><td><?php echo $packet_id; ?></td></tr>
            <tr><th>Message Name:</th><td><?php echo filter_var($object->getPacketName(), FILTER_SANITIZE_STRING); ?></td></tr>
            <tr><th>Direction:</th><td><?php echo filter_var($object->getPacketDirectionLabel(), FILTER_SANITIZE_STRING); ?></td></tr>
            <tr><th>Used By:</th><td><?php
              $products = $this->getContext()->used_by;
              if (count($products) == 0) {
                echo '<em>(nothing or unknown)</em>';
              } else if (count($products) == 1) {
                echo filter_var($products[0]->getLabel(), FILTER_SANITIZE_STRING);
              } else {
                $j = count($this->getContext()->used_by);
                for ($i = 0; $i < $j; ++$i) {
                  echo filter_var($this->getContext()->used_by[$i]->getLabel(), FILTER_SANITIZE_STRING);
                  if ($i + 1 < $j) {
                    ++$i;
                    echo ', ';
                    echo filter_var($this->getContext()->used_by[$i]->getLabel(), FILTER_SANITIZE_STRING) . "<br/>";
                  } else {
                    echo "<br/>";
                  }
                }
              }
            ?></td></tr>
            <tr><th>Format:</th><td><p><pre><code><?php echo $object->getPacketFormat(); ?></code></pre></p></td></tr>
          </tbody></table>
        </section>
        <header>Remarks</header>
        <section>
<?php echo $object->getPacketRemarks(true); ?>
        </section>
        <footer>
<?php if ($object->getEditedDateTime() !== null) { ?>
          <span class="float-right"><time datetime="<?php echo $object->getCreatedDateTime()->format('c'); ?>"><?php echo $object->getCreatedDateTime()->format("l, F j, Y"); ?></time> | Edited: <time datetime="<?php echo $object->getEditedDateTime()->format('c'); ?>"><?php echo $object->getEditedDateTime()->format("l, F j, Y"); ?></time></span>
<?php } else { ?>
          <span class="float-right"><time datetime="<?php echo $object->getCreatedDateTime()->format('c'); ?>"><?php echo $object->getCreatedDateTime()->format("l, F j, Y"); ?></time></span>
<?php } ?>
<?php if ($user_id !== null) { ?>
          <span><a href="<?php echo $user_url; ?>"><img class="avatar" src="<?php echo $user_avatar; ?>"/> <?php echo filter_var($user_name, FILTER_SANITIZE_STRING); ?></a></span>
<?php } ?>
        </footer>
      </article>
      <article>
<?php

$comment_parent_type = Comment::PARENT_TYPE_PACKET;
require("./Comment/Section.inc.phtml");

      } else { ?>
        <header class="red"><?php echo filter_var($title, FILTER_SANITIZE_STRING); ?></header>
        <section class="red"><?php echo filter_var($description, FILTER_SANITIZE_STRING); ?></section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
