<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Packet;
use \BNETDocs\Libraries\Comment;
use \BNETDocs\Libraries\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Packet Not Found';
$description = 'The requested packet does not exist or could not be found.';
$active_user = $this->getContext()->active_user;
$comments = $this->getContext()->comments;
$object = $this->getContext()->packet;
$object_id = $this->getContext()->packet_id;
$url = Common::relativeUrlToAbsolute('/packet/' . urlencode($object_id));
if ($object)
{
  $application_layer = $object->getApplicationLayer();
  $created_dt = $object->getCreatedDateTime();
  $deprecated = $object->isDeprecated();
  $brief = $object->getBrief(true);
  $edited_dt = $object->getEditedDateTime();
  $packet_id = $object->getPacketId(true);
  $published = $object->isPublished();
  $remarks = $object->getRemarks(true);
  $research = $object->isInResearch();
  $title = $object->getName();
  $transport_layer = $object->getTransportLayer();
  $url = $object->getURI();
  $user = $object->getUser();

  $description = filter_var($brief, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
  if (empty($description))
  {
    $description = rtrim(Common::stripUpTo(Common::stripUpTo(trim(filter_var($remarks, FILTER_SANITIZE_STRING)), "\n", 300), '. ', 300), '.');
  }

  if ($user)
  {
    $user_name   = $user->getName();
    $user_id     = $user->getId();
    $user_url    = $user->getURI();
    $user_avatar = $user->getAvatarURI(40);
  }
}

$this->opengraph->attach(new Pair('type', 'article'));
$this->opengraph->attach(new Pair('url', $url));

$edit_url = Common::relativeUrlToAbsolute('/packet/edit?id=' . urlencode($object_id));
$delete_url = Common::relativeUrlToAbsolute('/packet/delete?id=' . urlencode($object_id));
$edit_visible = ($active_user && $active_user->getOption(User::OPTION_ACL_PACKET_MODIFY));
$delete_visible = ($active_user && $active_user->getOption(User::OPTION_ACL_PACKET_DELETE));

require_once('./MarkdownBootstrapFix.inc.php');
require('./header.inc.phtml'); ?>
<div class="container">
<? if ($object) { ?>
  <a class="btn btn-sm btn-primary float-right mr-1" href="https://twitter.com/share?text=<?=urlencode($object->getLabel())?>&amp;url=<?=urlencode($url)?>" rel="external" data-popup="1"><img src="<?=Common::relativeUrlToAbsolute('/a/social-twitter-24px.png')?>"/></a>
  <a class="btn btn-sm btn-primary float-right mr-1" href="https://facebook.com/sharer/sharer.php?u=<?=urlencode($url)?>" rel="external" data-popup="1"><img src="<?=Common::relativeUrlToAbsolute('/a/social-facebook-24px.png')?>"/></a>
<? if ($delete_visible) { ?>
  <a class="btn btn-sm btn-danger float-right mr-1" href="<?=$delete_url?>" title="Delete">❌</a>
<? } if ($edit_visible) { ?>
  <a class="btn btn-sm btn-secondary float-right mr-1" href="<?=$edit_url?>" title="Edit">📝</a>
<? } ?>

  <h1><a href="<?=$url?>"><?=filter_var($title, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></a></h1>
  <table class="table table-striped"><tbody>
    <tr><th class="text-right">Transport Layer:</th><td><?=sprintf('%s (%s)', $transport_layer->getLabel(), $transport_layer->getTag())?></td></tr>
    <tr><th class="text-right">Application Layer:</th><td><?=sprintf('%s (%s)', $application_layer->getLabel(), $application_layer->getTag())?></td></tr>
    <tr><th class="text-right">Message Id:</th><td><code><?=$packet_id?></code></td></tr>
    <tr><th class="text-right">Message Name:</th><td><code><?=filter_var($object->getName(), FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></code></td></tr>
    <tr><th class="text-right">Direction:</th><td><?=filter_var($object->getDirectionLabel(), FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></td></tr>
<? if ($deprecated || $research || !$published) { ?>
    <tr><th class="text-right">Options:</th><td>
      <? if ($deprecated) require('./Deprecated.inc.phtml'); ?>
      <? if ($research) require('./InResearch.inc.phtml'); ?>
      <? if (!$published) require('./Draft.inc.phtml'); ?>
    </td></tr>
<? } ?>
    <tr><th class="text-right">Used By:</th><td><?
      $products = $this->getContext()->used_by;
      if (count($products) == 0) {
        echo '<em>(nothing or unknown)</em>';
      } else if (count($products) == 1) {
        echo filter_var($products[0]->getLabel(), FILTER_SANITIZE_STRING);
      } else {
        $j = count($this->getContext()->used_by);
        for ($i = 0; $i < $j; ++$i) {
          echo filter_var($this->getContext()->used_by[$i]->getLabel(), FILTER_SANITIZE_STRING);
          if ($i + 1 < $j) {
            ++$i;
            echo ', ';
            echo filter_var($this->getContext()->used_by[$i]->getLabel(), FILTER_SANITIZE_STRING) . "<br/>";
          } else {
            echo "<br/>";
          }
        }
      }
    ?></td></tr>
    <tr><th class="text-right">Message Format:<br/><sup class="text-muted">(does not include protocol header)</sup></th><td>
      <pre class="border border-primary overflow-auto rounded bg-dark text-light"><code class="language-objectivec"><?=$object->getFormat()?></code></pre>
    </td></tr>
<?=(!empty($brief) ? sprintf('<tr><th class="text-right">Brief:</th><td>%s</td></tr>', \BNETDocs\Templates\MarkdownBootstrapFix($brief, true, true)) : '')?>
  </tbody></table>

  <h1>Remarks</h1>
  <div class="container"><?=\BNETDocs\Templates\MarkdownBootstrapFix($remarks, true, false)?></div>

  <div class="card mt-3"><div class="card-body">
    <span class="float-right text-muted">
      <time datetime="<?=$created_dt->format('c')?>"><?=$created_dt->format('l, F j, Y')?></time>
<? if ($edited_dt) { ?>
      | <strong>Edited:</strong> <time datetime="<?=$edited_dt->format('c')?>"><?=$edited_dt->format('l, F j, Y'); ?></time>
<? } ?>
    </span>
<?  echo (!empty($user_url) && !empty($user_avatar) ?
      sprintf('<a href="%s"><img class="img-fluid rounded mr-2" src="%s"/>%s</a>',
        $user_url, $user_avatar, filter_var($user_name, FILTER_SANITIZE_FULL_SPECIAL_CHARS)
      ) : 'Anonymous'
    ); ?>
  </div></div>
<? $comment_parent_type = Comment::PARENT_TYPE_PACKET; $comment_parent_id = $object_id; require('./Comment/Section.inc.phtml');
  } else { ?>
  <h1 class="text-danger"><?=filter_var($title, FILTER_SANITIZE_STRING)?></h1>
  <div class="alert alert-danger"><?=filter_var($description, FILTER_SANITIZE_STRING)?></div></div>
<? } require('./footer.inc.phtml'); ?>
