<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Pair;

$title       = "Change Password";
$description = "This form allows an individual to change the password to their account.";
$this->opengraph->attach(new Pair("url", "/user/changepassword"));

require("./header.inc.phtml");
?>
      <article>
        <header>Change Password</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
