<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Pair;

$title       = "Account Login";
$description = "Log in to the BNETDocs website";
$this->opengraph->attach(new Pair("url", "https://dev.bnetdocs.org/user/login"));

$this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
<?php if (!isset($this->getContext()->user_session)) { ?>
        <header>Log In</header>
        <form method="POST" action="?">
          <section<?php if ($this->getContext()->bad_email) { ?> class="red"<?php } ?>>
<?php if (is_string($this->getContext()->bad_email)) { ?>
            <p class="center"><?php echo $this->getContext()->bad_email; ?></p>
<?php } ?>
            <label for="email">Email address:</label><br/>
            <input
              type="email"
              name="email"
              id="email"
              value="<?php echo htmlspecialchars($this->getContext()->email, ENT_HTML5, "UTF-8"); ?>"
              tabindex="1"
            />
          </section>
          <section<?php if ($this->getContext()->bad_password) { ?> class="red"<?php } ?>>
<?php if (is_string($this->getContext()->bad_password)) { ?>
            <p class="center"><?php echo $this->getContext()->bad_password; ?></p>
<?php } ?>
            <label for="password">Password:</label><br/>
            <input
              type="password"
              name="password"
              id="password"
              value="<?php echo htmlspecialchars($this->getContext()->password, ENT_HTML5, "UTF-8"); ?>"
              tabindex="2"
            />
          </section>
          <section>
            <input
              type="submit"
              value="Log In"
              tabindex="3"
            />
          </section>
        </form>
<?php } else { ?>
        <header>Logged In</header>
        <section class="green">
          <p>You have successfully logged in to the account!</p>
          <p>If you'd like to logout, click the link on the left.</p>
        </section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
