<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Pair;

$title       = "Logout";
$description = "Log out of the BNETDocs website";
$this->opengraph->attach(new Pair("url", "/user/logout"));

switch ($this->getContext()->error) {
  case "NOT_LOGGED_IN":
    $message = "You were not logged in to begin with.";
    break;
  case "INVALID_CSRF":
    $message = "The Cross-Site Request Forgery token was invalid. "
      . "Either the log out form expired, or "
      . "this may have been a malicious attempt to log you out.";
    break;
  default:
    $message = $this->getContext()->error;
}

$this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
<?php if (is_null($this->getContext()->error)) { ?>
        <header>Log Out</header>
        <form method="POST" action="?">
          <input type="hidden" name="csrf_id" value="<?php echo $this->getContext()->csrf_id; ?>"/>
          <input type="hidden" name="csrf_token" value="<?php echo $this->getContext()->csrf_token; ?>"/>
          <section>
            <p>If you are sure you wish to log out, press the button below.</p>
            <p><input type="submit" value="Logout"/></p>
          </section>
        </form>
<?php } else if ($this->getContext()->error === false) { ?>
        <header class="green">Logged Out</header>
        <section class="green">
          <p>You have been successfully logged out!</p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } else { ?>
        <header class="red">Log out failure</header>
        <section class="red">
          <p>An error occurred while attempting to log out.</p>
          <p><?php echo $message; ?></p>
          <p>Use the navigation to the left to move to another page.</p>
        </section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
