<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Pair;

$title       = "Create Account";
$description = "This form allows an individual to create an account on BNETDocs";
$this->opengraph->attach(new Pair("url", "https://dev.bnetdocs.org/user/register"));

$this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
<?php if (!isset($this->getContext()->user_session)) { ?>
        <header>Create Account</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
<?php } else { ?>
        <header class="red">Create Account</header>
        <section class="red">
          <p>You are currently logged in to an account. You must first logout of your account before using this form.</p>
          <p><a class="button" href="https://dev.bnetdocs.org/user/logout">Logout</a></p>
        </section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
