<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Pair;

$title       = "Create Account";
$description = "Create an account on the BNETDocs website";
$this->opengraph->attach(new Pair("url", "https://dev.bnetdocs.org/user/register"));

$this->additional_css[] = "/a/forms.css";
require("./header.inc.phtml");
?>
      <article>
        <header>Create Account</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
