<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Pair;

$title       = "Reset Password";
$description = "This form allows an individual to reset the password to their account.";
$this->opengraph->attach(new Pair("url", "https://dev.bnetdocs.org/user/resetpassword"));

require("./header.inc.phtml");
?>
      <article>
        <header>Reset Password</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
