<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Pair;

$title       = "View Account";
$description = $this->getContext()->user->getName() . " on BNETDocs website";
$this->opengraph->attach(new Pair("url", "https://dev.bnetdocs.org/user/" . $this->getContext()->user_id));
$this->opengraph->attach(new Pair("type", "profile"));
$this->opengraph->attach(new Pair("profile:username", $this->getContext()->user->getName()));

$safe_name = htmlspecialchars($this->getContext()->user->getName(), ENT_HTML5, "UTF-8");

$contributions = 0;
$contributions += $this->getContext()->sum_documents;
$contributions += $this->getContext()->sum_news_posts;
$contributions += $this->getContext()->sum_packets;
$contributions += $this->getContext()->sum_servers;

require("./header.inc.phtml");
?>
      <article>
        <header>View Account</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
        <header>User Profile</header>
        <section>
<?php if (!$this->getContext()->user_profile) { ?>
          <p class="center">Unfortunately, <strong><?php echo $safe_name; ?></strong> does not have a user profile.</p>
<?php } else { ?>
          <table style="width:100%;"><tbody>
<?php // TODO: Check for NULL profile fields and handle them appropriately. ?>
            <tr><th class="right" style="width:128px;">Biography:</th><td class="left"><?php echo $this->getContext()->user_profile->getBiography(); ?></td></tr>
            <tr><th class="right">GitHub:</th><td class="left"><a href="https://github.com/<?php echo $this->getContext()->user_profile->getGitHubUsername(); ?>"><?php echo $this->getContext()->user_profile->getGitHubUsername(); ?></a></td></tr>
            <tr><th class="right">Facebook:</th><td class="left"><a href="https://www.facebook.com/<?php echo $this->getContext()->user_profile->getFacebookUsername(); ?>"><?php echo $this->getContext()->user_profile->getFacebookUsername(); ?></a></td></tr>
            <tr><th class="right">Twitter:</th><td class="left"><a href="https://twitter.com/<?php echo $this->getContext()->user_profile->getTwitterUsername(); ?>"><?php echo $this->getContext()->user_profile->getTwitterUsername(); ?></a></td></tr>
            <tr><th class="right">Instagram:</th><td class="left"><a href="https://instagram.com/<?php echo $this->getContext()->user_profile->getInstagramUsername(); ?>"><?php echo $this->getContext()->user_profile->getInstagramUsername(); ?></a></td></tr>
            <tr><th class="right">Skype:</th><td class="left"><?php echo $this->getContext()->user_profile->getSkypeUsername(); ?></td></tr>
            <tr><th class="right">Website:</th><td class="left"><a href="<?php echo $this->getContext()->user_profile->getWebsite(); ?>"><?php echo $this->getContext()->user_profile->getWebsite(); ?></a></td></tr>
          </tbody></table>
<?php } ?>
        </section>
        <header>User Statistics</header>
        <section>
          <ul>
            <li><strong><?php echo $safe_name; ?></strong> has been a member for <?php echo $this->getContext()->user_est; ?> (since <time datetime="<?php echo $this->getContext()->user->getCreatedDateTime()->format("c"); ?>"><?php echo $this->getContext()->user->getCreatedDateTime()->format("l, F j, Y"); ?></time>).</li>
<?php if ($contributions == 0) { ?>
            <li><strong><?php echo $safe_name; ?></strong> has not made any contributions to BNETDocs.</li>
<?php } else { ?>
            <li><strong><?php echo $safe_name; ?></strong> is the owner or author of:
              <ul>
                <li><?php echo number_format($this->getContext()->sum_documents);  ?> document<?php  echo ($this->getContext()->sum_documents  != 1 ? "s" : ""); ?></li>
                <li><?php echo number_format($this->getContext()->sum_news_posts); ?> news post<?php echo ($this->getContext()->sum_news_posts != 1 ? "s" : ""); ?></li>
                <li><?php echo number_format($this->getContext()->sum_packets);    ?> packet<?php    echo ($this->getContext()->sum_packets    != 1 ? "s" : ""); ?></li>
                <li><?php echo number_format($this->getContext()->sum_servers);    ?> server<?php    echo ($this->getContext()->sum_servers    != 1 ? "s" : ""); ?></li>
              </ul>
            </li>
          </ul>
<?php } ?>
        </section>
      </article>
<?php if (isset($this->getContext()->documents)) { ?>
      <article>
        <header>Documents</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php } ?>
<?php if (isset($this->getContext()->news_posts)) { ?>
      <article>
        <header>News Posts</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php } ?>
<?php if (isset($this->getContext()->packets)) { ?>
      <article>
        <header>Packets</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php } ?>
<?php if (isset($this->getContext()->servers)) { ?>
      <article>
        <header>Servers</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php } ?>
<?php require("./footer.inc.phtml"); ?>
