<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Gravatar;
use \BNETDocs\Libraries\Pair;

$title       = "View Account";
$description = $this->getContext()->user->getName() . " on BNETDocs website";
$this->opengraph->attach(new Pair("url", "https://dev.bnetdocs.org/user/" . $this->getContext()->user_id));
$this->opengraph->attach(new Pair("type", "profile"));
$this->opengraph->attach(new Pair("profile:username", $this->getContext()->user->getName()));

$gravatar = new Gravatar($this->getContext()->user->getEmail());
$this->opengraph->attach(new Pair("image", "https:" . $gravatar->getUrl(null, "identicon")));

$safe_name = htmlspecialchars($this->getContext()->user->getName(), ENT_HTML5, "UTF-8");

$biography      = ($this->getContext()->user_profile && $this->getContext()->user_profile->getBiography() ?
                   $this->getContext()->user_profile->getBiography() : null);
$safe_biography = htmlspecialchars($biography, ENT_HTML5, "UTF-8");
$github         = ($this->getContext()->user_profile && $this->getContext()->user_profile->getGitHubUsername() ?
                   $this->getContext()->user_profile->getGitHubUsername() : null);
$facebook       = ($this->getContext()->user_profile && $this->getContext()->user_profile->getFacebookUsername() ?
                   $this->getContext()->user_profile->getFacebookUsername() : null);
$twitter        = ($this->getContext()->user_profile && $this->getContext()->user_profile->getTwitterUsername() ?
                   $this->getContext()->user_profile->getTwitterUsername() : null);
$instagram      = ($this->getContext()->user_profile && $this->getContext()->user_profile->getInstagramUsername() ?
                   $this->getContext()->user_profile->getInstagramUsername() : null);
$skype          = ($this->getContext()->user_profile && $this->getContext()->user_profile->getSkypeUsername() ?
                   $this->getContext()->user_profile->getSkypeUsername() : null);
$website        = ($this->getContext()->user_profile && $this->getContext()->user_profile->getWebsite() ?
                   $this->getContext()->user_profile->getWebsite() : null);

$profiledata = (
  $github || $facebook || $twitter || $instagram || $skype || $website
);

$contributions = 0;
$contributions += $this->getContext()->sum_documents;
$contributions += $this->getContext()->sum_news_posts;
$contributions += $this->getContext()->sum_packets;
$contributions += $this->getContext()->sum_servers;

$this->additional_css[] = "/a/userprofile.css";
require("./header.inc.phtml");
?>
      <article>
        <header>User Profile</header>
        <section class="accountinfo">
          <img class="avatar" src="https:<?php echo $gravatar->getUrl(75, "identicon"); ?>" />
          <strong><?php echo $safe_name; ?></strong><br />
<?php if (!$biography) { ?>
          <p><em style="font-size:smaller;">(no biography information.)</em></p>
<?php } else { ?>
          <p><?php echo $safe_biography; ?></p>
<?php } ?>
<?php if ($profiledata) { ?>
          <table style="clear:left;"><tbody>
<?php if ($github) { ?>
            <tr><th class="right">GitHub:</th><td class="left"><a href="https://github.com/<?php echo rawurlencode($github) ?>"><?php echo htmlspecialchars($github, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
<?php if ($facebook) { ?>
            <tr><th class="right">Facebook:</th><td class="left"><a href="https://www.facebook.com/<?php echo rawurlencode($facebook); ?>"><?php echo htmlspecialchars($facebook, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
<?php if ($twitter) { ?>
            <tr><th class="right">Twitter:</th><td class="left"><a href="https://twitter.com/<?php echo rawurlencode($twitter); ?>"><?php echo htmlspecialchars($twitter, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
<?php if ($instagram) { ?>
            <tr><th class="right">Instagram:</th><td class="left"><a href="https://instagram.com/<?php echo rawurlencode($instagram); ?>"><?php echo htmlspecialchars($instagram, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
<?php if ($skype) { ?>
            <tr><th class="right">Skype:</th><td class="left"><a href="skype:<?php echo rawurlencode($skype); ?>?call"><?php echo htmlspecialchars($skype, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
<?php if ($website) { ?>
            <tr><th class="right">Website:</th><td class="left"><a href="<?php echo $website; ?>"><?php echo htmlspecialchars($website, ENT_HTML5, "UTF-8"); ?></a></td></tr>
<?php } ?>
          </tbody></table>
<?php } ?>
        </section>
        <header>User Statistics</header>
        <section>
          <ul>
            <li><strong><?php echo $safe_name; ?></strong> has been a member for <?php echo $this->getContext()->user_est; ?> (since <time datetime="<?php echo $this->getContext()->user->getCreatedDateTime()->format("c"); ?>"><?php echo $this->getContext()->user->getCreatedDateTime()->format("l, F j, Y"); ?></time>).</li>
<?php if ($contributions == 0) { ?>
            <li><strong><?php echo $safe_name; ?></strong> has not made any contributions to BNETDocs.</li>
<?php } else { ?>
            <li><strong><?php echo $safe_name; ?></strong> is the owner or author of:
              <ul>
<?php if ($this->getContext()->sum_documents) { ?>
                <li><?php echo number_format($this->getContext()->sum_documents);  ?> document<?php  echo ($this->getContext()->sum_documents  != 1 ? "s" : ""); ?></li>
<?php } ?>
<?php if ($this->getContext()->sum_news_posts) { ?>
                <li><?php echo number_format($this->getContext()->sum_news_posts); ?> news post<?php echo ($this->getContext()->sum_news_posts != 1 ? "s" : ""); ?></li>
<?php } ?>
<?php if ($this->getContext()->sum_packets) { ?>
                <li><?php echo number_format($this->getContext()->sum_packets);    ?> packet<?php    echo ($this->getContext()->sum_packets    != 1 ? "s" : ""); ?></li>
<?php } ?>
<?php if ($this->getContext()->sum_servers) { ?>
                <li><?php echo number_format($this->getContext()->sum_servers);    ?> server<?php    echo ($this->getContext()->sum_servers    != 1 ? "s" : ""); ?></li>
<?php } ?>
              </ul>
            </li>
          </ul>
<?php } ?>
        </section>
      </article>
<?php if (isset($this->getContext()->documents)) { ?>
      <article>
        <header>Documents</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php } ?>
<?php if (isset($this->getContext()->news_posts)) { ?>
      <article>
        <header>News Posts</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php } ?>
<?php if (isset($this->getContext()->packets)) { ?>
      <article>
        <header>Packets</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php } ?>
<?php if (isset($this->getContext()->servers)) { ?>
      <article>
        <header>Servers</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php } ?>
<?php require("./footer.inc.phtml"); ?>
