<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Pair;

$title = "Popular Packets";
$this->opengraph->attach(new Pair("description", "The popular packets on BNETDocs"));
$this->opengraph->attach(new Pair("url", "https://dev.bnetdocs.org/packet/popular"));

require("./header.inc.phtml");
?>
      <article>
        <header>Popular Packets</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
