
--

BNETDocs: Phoenix

Copyright © 2003-2015 BNETDocs CC-BY-NC-SA 4.0 <https://dev.bnetdocs.org/legal>

BNETDocs is in no way affiliated with or endorsed by Blizzard Entertainment™ or
its brands, and is not intended to compete with or undermine Blizzard
Entertainment™ or Battle.net™. Persons using this software understand that the
information provided within is collected knowledge from years of observations
and may be inaccurate. All aforementioned trademarks are the property of their
respectful owners.
