<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Document;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Create Document';
$description = 'This page enables a user to create documents on the site.';
$this->opengraph->attach(new Pair('url', '/document/create'));
$this->opengraph->attach(new Pair('type', 'article'));
$document_id = null;
$document_url = null;
$error = $this->getContext()->error;
switch ($error)
{
  case 'ACL_NOT_SET': $message = 'You do not have the privilege to create documents.'; break;
  case 'EMPTY_TITLE': $message = 'The title of the document is required.'; break;
  case 'EMPTY_CONTENT': $message = 'The content of the document is required.'; break;
  case 'INTERNAL_ERROR': $message = 'An internal error occurred while processing your request. Our staff have been notified of the issue. Try again later.'; break;
  default: $message = $error;
}
$form_content = filter_var($this->getContext()->content, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$form_markdown = $this->getContext()->markdown;
$form_title = filter_var($this->getContext()->title, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
require('./header.inc.phtml'); ?>
<div class="container mb-3">
  <h1><?=$title?></h1>
  <p><?=$description?></p>
<?  if ($error !== false) {
      if (!empty($message)) { ?>
  <div class="alert alert-danger">
    <p class="mb-0"><?=$message?></p>
  </div>
<?    }
      require('./Document/Form.inc.phtml'); 
    } else { ?>
  <div class="alert alert-success">
    <p class="mb-0">The document has been created.</p>
  </div>
<?  } ?>
</div>
<? require('./footer.inc.phtml'); ?>
