<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Document;
use \BNETDocs\Models\Document\Delete as DeleteModel;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Delete Document';
$description = 'This form allows an individual to delete a document.';
$this->opengraph->attach(new Pair('url', '/document/delete'));
$this->opengraph->attach(new Pair('type', 'article'));
$error = $this->getContext()->error;
$id = $this->getContext()->id;
$doc_title = $this->getContext()->title;
switch ($error)
{
  case DeleteModel::ERROR_ACCESS_DENIED: $message = 'You do not have the privilege to delete documents.'; break;
  case DeleteModel::ERROR_INTERNAL: $message = 'An internal error occurred while processing your request. Try again later.'; break;
  case DeleteModel::ERROR_NOT_FOUND: $message = 'Cannot find document by that id.'; break;
  case DeleteModel::ERROR_SUCCESS: $message = 'You have successfully deleted the document!'; break;
  default: $message = $error;
}
require('./header.inc.phtml'); ?>
<div class="container">
<? if ($error === DeleteModel::ERROR_ACCESS_DENIED) { ?>
<? require('./LoginRequired.inc.phtml'); ?>
<? } else if ($error === DeleteModel::ERROR_NONE) { ?>
  <h1 class="text-danger">Delete Document</h1>
  <form method="POST" action="?id=<?=filter_var($id, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>">
    <div class="form-group">
      <p class="text-danger">Are you sure you wish to delete this document?</p>
      <div class="card text-light"><div class="card-body"><?=filter_var($doc_title, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></div></div>
    </div>
    <div class="form-group text-center">
      <a class="btn btn-primary" href="javascript:history.go(-1);" tabindex="1">Back</a>
      <input class="btn btn-danger" type="submit" value="Delete Document" tabindex="2" autofocus="autofocus"/>
    </div>
  </form>
<? } else if ($error === DeleteModel::ERROR_SUCCESS) { ?>
  <h1 class="text-success">Document Deleted</h1>
  <div class="alert alert-success">
    <p class="mb-0"><?=$message?></p>
  </div>
<? } else { ?>
  <h1 class="text-danger">Delete Document</h1>
  <div class="alert alert-danger">
    <p>An error occurred while attempting to delete the document.</p>
    <p class="mb-0"><?=$message?></p>
  </div>
<? } ?>
</div>
<? require('./footer.inc.phtml'); ?>
