<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Document;
use \BNETDocs\Libraries\Comment;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'Edit Document';
$description = 'This form allows an individual to edit a document.';
$this->opengraph->attach(new Pair('url', '/document/edit'));
$this->opengraph->attach(new Pair('type', 'article'));
$comments = $this->getContext()->comments;
$document_id = $this->getContext()->document_id;
$document_url = ($this->getContext()->document ? $this->getContext()->document->getURI() : Common::relativeUrlToAbsolute('/document/' . rawurlencode($document_id)));
$error = $this->getContext()->error;
switch ($error)
{
  case 'ACL_NOT_SET': $message = 'You do not have the privilege to edit documents.'; break;
  case 'NOT_FOUND': $message = 'Cannot find document by that id.'; break;
  case 'EMPTY_TITLE': $message = 'The title of the document is required.'; break;
  case 'EMPTY_CONTENT': $message = 'The content of the document is required.'; break;
  case 'INTERNAL_ERROR': $message = 'An internal error occurred while processing your request. Our staff have been notified of the issue. Try again later.'; break;
  default: $message = $error;
}
$form_content = filter_var($this->getContext()->content, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$form_markdown = $this->getContext()->markdown;
$form_title = filter_var($this->getContext()->title, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
require('./header.inc.phtml'); ?>
<div class="container">
<? if ($this->getContext()->acl_allowed) { ?>
  <h1><?=$title?></h1>
  <p><?=$description?></p>
<?  if (is_null($error) || $error == 'NOT_FOUND') {
      require('./Document/Form.inc.phtml');
      $comment_parent_type = Comment::PARENT_TYPE_DOCUMENT; $comment_parent_id = $document_id; require('./Comment/Section.inc.phtml');
    } else if ($error !== false) { ?>
  <div class="alert alert-danger">
    <p class="mb-0"><?=$message?></p>
  </div>
<?  } else { ?>
  <div class="alert alert-success">
    <p class="mb-0">The document was successfully edited!</p>
  </div>
  <div class="text-center">
    <a class="btn btn-primary" href="<?=Common::relativeUrlToAbsolute('/document/' . rawurlencode($document_id))?>"><img class="float-left" src="<?=Common::relativeUrlToAbsolute('/a/svg/chevron-right-white.svg' . $_unique_asset)?>"/> Return to Document</a>
  </div>
<?  }
  } else { require('./LoginRequired.inc.phtml'); } ?>
</div>
<? require('./footer.inc.phtml'); ?>
