<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Document;
use \BNETDocs\Libraries\Comment;
use \BNETDocs\Libraries\Core\UrlFormatter;
use \BNETDocs\Models\Document\Edit as EditModel;
$title = 'Edit Document';
$description = 'This form allows an individual to edit a document.';
$url = '/document/edit';
$comments = $this->getContext()->comments;
$document_id = $this->getContext()->document_id;
$document_url = ($this->getContext()->document ? $this->getContext()->document->getURI() : UrlFormatter::format('/document/' . rawurlencode($document_id ?? '')));
$error = $this->getContext()->error;
switch ($error)
{
  case EditModel::ERROR_ACL_NOT_SET: $message = 'You do not have the privilege to edit documents.'; break;
  case EditModel::ERROR_EMPTY_CONTENT: $message = 'The content of the document is required.'; break;
  case EditModel::ERROR_EMPTY_TITLE: $message = 'The title of the document is required.'; break;
  case EditModel::ERROR_INTERNAL: $message = 'An internal error occurred while processing your request. Our staff have been notified of the issue. Try again later.'; break;
  case EditModel::ERROR_NOT_FOUND: $message = 'Cannot find document by that id.'; break;
  case EditModel::ERROR_NOT_LOGGED_IN: $message = 'You must be logged in to edit documents.'; break;
  default: $message = $error;
}
$form_brief = filter_var($this->getContext()->brief, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$form_content = filter_var($this->getContext()->content, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$form_markdown = $this->getContext()->markdown;
$form_title = filter_var($this->getContext()->title, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
require('./Includes/header.inc.phtml'); ?>
<div class="container">
<? if ($this->getContext()->acl_allowed) { ?>
  <h1><?=$title?></h1>
  <p><?=$description?></p>
<?  if (is_null($error) || $error == EditModel::ERROR_NOT_FOUND) {
      require('./Document/Form.inc.phtml');
      $comment_parent_type = Comment::PARENT_TYPE_DOCUMENT; $comment_parent_id = $document_id; require('./Comment/Section.inc.phtml');
    } else if ($error !== false) { ?>
  <div class="alert alert-danger">
    <p class="mb-0"><?=$message?></p>
  </div>
<?  } else { ?>
  <div class="alert alert-success">
    <p class="mb-0">The document was successfully edited!</p>
  </div>
  <div class="text-center">
    <a class="btn btn-primary" href="<?=UrlFormatter::format('/document/' . rawurlencode($document_id))?>"><img class="float-left" src="<?=UrlFormatter::assetify('svg/chevron-right-white.svg')?>"/> Return to Document</a>
  </div>
<?  }
  } else { require('./Includes/LoginRequired.inc.phtml'); } ?>
</div>
<? require('./Includes/footer.inc.phtml'); ?>
