<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Document;
use \BNETDocs\Libraries\Document;
use \BNETDocs\Libraries\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$title = 'All Documents';
$description = 'The index for all of the document pages on BNETDocs';
$this->opengraph->attach(new Pair('url', '/document/index'));
$order = $this->getContext()->order;
$form_order_by = [
  'created-asc' => 'Created (Ascending)',
  'created-desc' => 'Created (Descending)',
  'id-asc' => 'Id (Ascending)',
  'id-desc' => 'Id (Descending)',
  'title-asc' => 'Title (Ascending)',
  'title-desc' => 'Title (Descending)',
  'updated-asc' => 'Updated (Ascending)',
  'updated-desc' => 'Updated (Descending)',
  'user-id-asc' => 'User Id (Ascending)',
  'user-id-desc' => 'User Id (Descending)',
];
require('./header.inc.phtml'); ?>
<div class="container mb-3">
  <h2><?=$title?></h2>
  <p><?=$description?></p>
  <form method="GET" class="m-2" id="order_by_form">
    <label for="order" class="font-weight-bold m-1">Order by:</label>
    <select class="form-control form-control-sm" name="order" id="order" onchange="form.submit();" style="display:inline-block;width:200px;">
<?  foreach ($form_order_by as $item_value => $item_label) {
      $item_selected = ($order === $item_value ? ' selected="selected"' : '');
      echo sprintf('<option value="%s"%s>%s</option>' . PHP_EOL, $item_value, $item_selected, $item_label);
    } ?>
    </select>
    <input class="btn btn-sm btn-secondary" type="submit" value="Reorder"/>
  </form>
  <table class="table table-hover table-striped" id="docs_tbl">
    <thead><tr><th class="left">Document</th><th class="left">Author</th></tr></thead><tbody>
<?  foreach ($this->getContext()->documents as $document)
    {
      $doc_title = filter_var($document->getTitle(), FILTER_SANITIZE_FULL_SPECIAL_CHARS);
      $doc_brief = rtrim(Common::stripUpTo(Common::stripUpTo(trim(filter_var($document->getContent(true), FILTER_SANITIZE_STRING)), "\n", 128), '. ', 128), '.');
      $doc_user = $document->getUser();
      $doc_user_string = ($doc_user ?
        sprintf('<a href="%s"><img class="img-fluid rounded mr-2" src="%s"/>%s</a>',
          $doc_user->getURI(), $doc_user->getAvatarURI(40), filter_var($doc_user->getName(), FILTER_SANITIZE_FULL_SPECIAL_CHARS)
        ) : 'Anonymous'
      );
      echo '<tr><td><strong><a href="' . $document->getURI() . '">' . $doc_title . '</a></strong><br/>'
        . '<span class="text-muted">' . $doc_brief . '</span></td><td>' . $doc_user_string . '</td></tr>';
    } ?>
  </tbody></table>
</div>
<? ob_start(); ?>
  <script type="text/javascript">
    $(document).ready(function(){
      $('#docs_tbl').DataTable({
        'aaSorting': [],
        "language": {"zeroRecords": "No matching documents found"},
        "responsive": true,
      });
    });
  </script>
<? $_footer_script = ob_get_clean(); require('./footer.inc.phtml'); ?>
