<?php
namespace BNETDocs\Templates;

use \CarlBennett\MVC\Libraries\Common;
use \BNETDocs\Libraries\Document;
use \BNETDocs\Libraries\Pair;
use \BNETDocs\Libraries\User;

$title       = "Document Index";
$description = "The index for documents on BNETDocs";
$this->opengraph->attach(new Pair("url", "/document/index"));

require("./header.inc.phtml");
?>
      <article>
        <header>Document Index</header>
        <section>
          <table>
            <thead>
              <tr>
                <th class="left">Found <?php echo number_format($this->getContext()->sum_documents); ?> document<?php echo ($this->getContext()->sum_documents != 1 ? "s" : ""); ?></th>
                <th class="left">Author</th>
              </tr>
            </thead><tbody>
<?php foreach ($this->getContext()->documents as $document) {
        $user       = $document->getUser();
        if ($user) {
          $user_url   = $user->getURI();
          $avatar_url = $user->getAvatarURI(22);
        }
?>
              <tr>
                <td><a href="<?php echo $document->getURI(); ?>"><?php echo htmlspecialchars($document->getTitle(), ENT_HTML5, "UTF-8"); ?></a></td>
                <td><?php if ($user) { ?><a href="<?php echo $user_url; ?>"><img class="avatar" src="<?php echo $avatar_url; ?>"/> <?php echo htmlspecialchars($user->getName(), ENT_HTML5, "UTF-8"); ?></a><?php } else { ?>Anonymous<?php } ?></td>
              </tr>
<?php } ?>
          </tbody></table>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
