<?php

namespace BNETDocs\Templates\Document;

use \CarlBennett\MVC\Libraries\Pair;

$title       = "Popular Documents";
$description = "The popular documents on BNETDocs";
$this->opengraph->attach(new Pair("url", "/document/popular"));

require("./header.inc.phtml");
?>
      <article>
        <header>Popular Documents</header>
        <section>
          <?php require("./NYI.inc.phtml"); ?>
        </section>
      </article>
<?php require("./footer.inc.phtml"); ?>
