<?php
namespace BNETDocs\Templates;

use \BNETDocs\Libraries\Common;
use \BNETDocs\Libraries\Gravatar;
use \BNETDocs\Libraries\Pair;

$comments  = $this->getContext()->comments;
$object_id = $this->getContext()->document_id;
$object    = $this->getContext()->document;

$title       = "Document Not Found";
$description = "The requested document does not exist or could not be found.";

$this->opengraph->attach(new Pair("type", "article"));

$url = Common::relativeUrlToAbsolute("/document/" . urlencode($object_id));
if ($object) {

  $url .= "/" . Common::sanitizeForUrl($object->getTitle(), true);
  $this->opengraph->attach(new Pair("url", "/document/" . urlencode($object_id)
    . "/" . Common::sanitizeForUrl($object->getTitle(), true)));

  $title       = htmlspecialchars($object->getTitle(), ENT_HTML5, "UTF-8");
  $description = Common::stripUpTo(trim(filter_var(
    $object->getContent(true), FILTER_SANITIZE_STRING
  )), "\n", 300);

  $user_name   = $object->getUser()->getName();
  $user_id     = $object->getUserId();
  $user_url    = Common::relativeUrlToAbsolute("/user/" . $user_id . "/" . Common::sanitizeForUrl($user_name, true));
  $user_avatar = "https:" . (new Gravatar($object->getUser()->getEmail()))->getUrl(22, "identicon");

} else {
  $this->opengraph->attach(new Pair("url", "/document/" . urlencode($object_id)));
}

#$this->additional_css[] = "/a/document.css";
$this->additional_css[] = "/a/comments.css";
require("./header.inc.phtml");
?>
      <article>
<?php if ($object) { ?>
        <a href="https://plus.google.com/share?url=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-gplus-24px.png"); ?>"/></a>
        <a href="https://twitter.com/share?text=<?php echo urlencode($object->getTitle()); ?>&amp;url=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-twitter-24px.png"); ?>"/></a>
        <a href="https://facebook.com/sharer/sharer.php?u=<?php echo urlencode($url); ?>" rel="external" data-popup="1"><img class="header-button float-right" src="<?php echo Common::relativeUrlToAbsolute("/a/social-facebook-24px.png"); ?>"/></a>
        <header><a href="<?php echo $url; ?>"><?php echo $title; ?></a></header>
        <section>
<?php echo $object->getContent(true); ?>
        </section>
        <footer>
          <span class="float-left"><a href="<?php echo $user_url; ?>"><img class="avatar" src="<?php echo $user_avatar; ?>"/> <?php echo htmlspecialchars($user_name, ENT_HTML5, "UTF-8"); ?></a></span>
<?php if ($object->getEditedDateTime() !== null) { ?>
          <span class="float-right"><?php echo $object->getCreatedDateTime()->format("l, F j, Y"); ?> | Edited: <?php echo $object->getEditedDateTime()->format("l, F j, Y"); ?></span>
<?php } else { ?>
          <span class="float-right"><?php echo $object->getCreatedDateTime()->format("l, F j, Y"); ?></span>
<?php } ?>
        </footer>
      </article>
      <article>
        <header>Comments</header>
        <section>
<?php if (!$comments) { ?>
          <p class="center"><em>no one has commented yet.</em></p>
<?php } else { ?>
          <table class="comments"><tbody>
<?php foreach ($comments as $c) {
        $c_user        = $c->getUser();
        $c_user_name   = $c_user->getName();
        $c_user_id     = $c->getUserId();
        $c_user_url    = Common::relativeUrlToAbsolute("/user/" . $c_user_id . "/" . Common::sanitizeForUrl($c_user_name, true));
        $c_user_avatar = "https:" . (new Gravatar($c_user->getEmail()))->getUrl(22, "identicon");
?>
            <tr><td><a href="<?php echo $c_user_url; ?>"><img class="avatar" src="<?php echo $c_user_avatar; ?>"/> <?php echo htmlspecialchars($c_user_name, ENT_HTML5, "UTF-8"); ?></a><br/><time class="comment_timestamp" datetime="<?php echo $c->getCreatedDateTime()->format("c"); ?>"><?php echo $c->getCreatedDateTime()->format("D M j, Y g:ia T"); ?></time></td><td><?php echo $c->getContent(true); ?></td></tr>
<?php } ?>
          </tbody></table>
<?php } ?>
        </section>
<?php } else { ?>
        <header class="red"><?php echo htmlspecialchars($title, ENT_HTML5, "UTF-8"); ?></header>
        <section class="red"><?php echo htmlspecialchars($description, ENT_HTML5, "UTF-8"); ?></section>
<?php } ?>
      </article>
<?php require("./footer.inc.phtml"); ?>
