<?php /* vim: set colorcolumn=: */
namespace BNETDocs\Templates\Document;
use \BNETDocs\Libraries\Authentication;
use \BNETDocs\Libraries\Comment;
use \BNETDocs\Libraries\User;
use \CarlBennett\MVC\Libraries\Common;
use \CarlBennett\MVC\Libraries\Pair;
$comments = $this->getContext()->comments;
$object = $this->getContext()->document;
$object_id = $this->getContext()->document_id;
$logged_in = Authentication::$user;
$logged_in_id = ($logged_in ? $logged_in->getId() : null);
$title = 'Document Not Found';
$description = 'The requested document does not exist or could not be found.';
$this->opengraph->attach(new Pair('type', 'article'));
$url = Common::relativeUrlToAbsolute('/document/' . rawurlencode($object_id));
if ($object)
{
  $url = $object->getURI();
  $title = $object->getTitle();
  $description = Common::stripUpTo(trim(filter_var($object->getContent(true), FILTER_SANITIZE_STRING)), "\n", 300);
  $created_dt = $object->getCreatedDateTime();
  $edited_dt = $object->getEditedDateTime();
  $user = $object->getUser();
  $draft = !$object->isPublished();
}
$this->opengraph->attach(new Pair('url', $url));
$edit_url = Common::relativeUrlToAbsolute('/document/edit?id=' . rawurlencode($object_id));
$delete_url = Common::relativeUrlToAbsolute('/document/delete?id=' . rawurlencode($object_id));
$edit_visible = ($logged_in && ($logged_in->getOptionsBitmask() & User::OPTION_ACL_DOCUMENT_MODIFY));
$delete_visible = ($logged_in && ($logged_in->getOptionsBitmask() & User::OPTION_ACL_DOCUMENT_DELETE));
require_once('./MarkdownBootstrapFix.inc.php');
require('./header.inc.phtml'); ?>
<div class="container mb-3">
<? if ($object) {
    if ($draft) { ?>
  <div class="alert alert-warning">This document is marked as <strong>draft</strong>. Edit the document to <strong>publish</strong> it.</div>
<?  } ?>
  <span class="float-right ml-1"><a class="btn btn-sm btn-primary" href="https://twitter.com/share?text=<?=urlencode($title)?>&amp;url=<?=urlencode($url)?>" rel="external" data-popup="1"><img src="<?=Common::relativeUrlToAbsolute('/a/social-twitter-24px.png')?>"/></a></span>
  <span class="float-right ml-1"><a class="btn btn-sm btn-primary" href="https://facebook.com/sharer/sharer.php?u=<?=urlencode($url)?>" rel="external" data-popup="1"><img src="<?=Common::relativeUrlToAbsolute('/a/social-facebook-24px.png')?>"/></a></span>
<? if ($delete_visible) { ?>
  <span class="float-right ml-1"><a class="btn btn-sm btn-danger" href="<?=$delete_url?>" title="Delete">❌</a></span>
<? } if ($edit_visible) { ?>
  <span class="float-right ml-1"><a class="btn btn-sm btn-secondary" href="<?=$edit_url?>" title="Edit">📝</a></span>
<? } ?>

  <h1 class="display-4"><a href="<?=$url?>"><?=filter_var($title, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></a></h1>
  <?=\BNETDocs\Templates\MarkdownBootstrapFix($object->getContent(true))?>

  <div class="card"><div class="card-body">
    <span class="float-right">
      <time datetime="<?=$created_dt->format('c')?>"><?=$created_dt->format('l, F j, Y')?></time>
<? if ($edited_dt) { ?>
      | Edited: <time datetime="<?=$edited_dt->format('c')?>"><?=$edited_dt->format('l, F j, Y'); ?></time>
<? } ?>
    </span>
<? if ($user !== null) { ?>
    <span><a href="<?php echo $user->getURI(); ?>"><img class="avatar" src="<?php echo $user->getAvatarURI(22); ?>"/> <?php echo filter_var($user->getName(), FILTER_SANITIZE_STRING); ?></a></span>
<? } ?>
  </div></div>
<? $comment_parent_type = Comment::PARENT_TYPE_DOCUMENT; require('./Comment/Section.inc.phtml');
  } else { ?>
  <div class="alert alert-danger">
    <p><strong><?=filter_var($title, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></strong></p>
    <p class="mb-0"><?=filter_var($description, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></p>
  </div>
<? } ?>
</div>
<? require('./footer.inc.phtml'); ?>
