<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Document;
use \BNETDocs\Libraries\Comment;
use \BNETDocs\Libraries\Core\StringProcessor;
use \BNETDocs\Libraries\Core\UrlFormatter;
use \BNETDocs\Libraries\User\User;
$active_user = $this->getContext()->active_user;
$comments = $this->getContext()->comments;
$object = $this->getContext()->document;
$object_id = $this->getContext()->document_id;
if ($this->getContext()->_responseCode == 403)
{
  $title = 'Access Denied';
  $description = 'You do not have the required privileges to view this document.';
}
else
{
  $title = 'Document Not Found';
  $description = 'The requested document does not exist or could not be found.';
}
$_header_meta_properties = ['og:type' => 'article'];
$url = UrlFormatter::format('/document/' . rawurlencode($object_id ?? ''));
if ($object)
{
  $url = $object->getURI();
  $title = $object->getTitle();
  $brief = $object->getBrief(true);
  $content = $object->getContent(true);
  $created_dt = $object->getCreatedDateTime();
  $edited_dt = $object->getEditedDateTime();
  $tags = $object->getTags();
  $user = $object->getUser();
  $draft = !$object->isPublished();

  $description = filter_var($brief, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
  if (empty($description))
  {
    $description = rtrim(StringProcessor::stripUpTo(StringProcessor::stripUpTo(trim(strip_tags($content)), "\n", 128), '. ', 128), '.');
  }
}
$edit_url = UrlFormatter::format('/document/edit?id=' . rawurlencode($object_id));
$delete_url = UrlFormatter::format('/document/delete?id=' . rawurlencode($object_id));
$edit_visible = ($active_user && $active_user->getOption(User::OPTION_ACL_DOCUMENT_MODIFY));
$delete_visible = ($active_user && $active_user->getOption(User::OPTION_ACL_DOCUMENT_DELETE));
require_once('./Includes/MarkdownBootstrapFix.inc.php');
require('./Includes/header.inc.phtml'); ?>
<div class="container">
<? if ($object) {
   if ($draft) { ?>
  <div class="alert alert-warning">This document is marked as <strong>draft</strong>. Edit the document to <strong>publish</strong> it.</div>
<? } ?>
<? if ($delete_visible) { ?>
  <span class="float-right ml-1"><a class="btn btn-sm btn-danger" href="<?=$delete_url?>" title="Delete">❌</a></span>
<? } if ($edit_visible) { ?>
  <span class="float-right ml-1"><a class="btn btn-sm btn-secondary" href="<?=$edit_url?>" title="Edit">📝</a></span>
<? } ?>

  <h1 class="display-4"><a href="<?=$url?>"><?=filter_var($title, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></a></h1>
<?=(!empty($brief) ? sprintf('  <div class="alert alert-secondary"><span class="float-left font-weight-bold mr-1">Brief:</span> %s</div>', \BNETDocs\Templates\Includes\MarkdownBootstrapFix($brief, true, true)) : '')?>
  <?=\BNETDocs\Templates\Includes\MarkdownBootstrapFix($object->getContent(true), true)?>

<? require('./Includes/TagDisplay.inc.phtml'); ?>
  <div class="card"><div class="card-body">
    <span class="float-right text-muted">
      <time datetime="<?=$created_dt->format('c')?>"><?=$created_dt->format('l, F j, Y')?></time>
<? if ($edited_dt) { ?>
      | <strong>Edited:</strong> <time datetime="<?=$edited_dt->format('c')?>"><?=$edited_dt->format('l, F j, Y'); ?></time>
<? } ?>
    </span>
<?  echo ($user ?
      sprintf('<a href="%s"><img class="img-fluid rounded mr-2" src="%s"/>%s</a>',
        $user->getURI(), $user->getAvatarURI(40), filter_var($user->getName(), FILTER_SANITIZE_FULL_SPECIAL_CHARS)
      ) : 'Anonymous'
    ); ?>
  </div></div>
<? $comment_parent_type = Comment::PARENT_TYPE_DOCUMENT; $comment_parent_id = $object_id; require('./Comment/Section.inc.phtml');
  } else { ?>
  <h1 class="text-danger"><?=filter_var($title, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></h1>
  <div class="alert alert-danger"><?=filter_var($description, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></div></div>
<? } ?>
</div>
<? require('./Includes/footer.inc.phtml'); ?>
